### ISSUE TITLE
indexioned rule support

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#105]
i have alternative for this
https://github.com/NanoAdblocker/NanoCore/issues/91

you can add support to indexion rule

example.
`[V.2231] [E: ads] [S: ready] [P:2] [Q:75]`

`V - last version`, `E - element`, `S - status`, `P - priority 1-4`, `Q - sensitivity of blocking 1-100`

![2018-01-31-nano przegladarka filtrow](https://user-images.githubusercontent.com/5884000/35616708-59050bda-0676-11e8-882f-4fc4c748362e.png)
`https://github.com/KonoromiHimaries/polish-ads-filter/blob/master/inside-filters/adblock_wewnetrzne.txt`

it would be super useful to manage lists for ordinary people
using the scroll bar you could set the blocking degree

or choose only those elements that you want to block and others to disable. priority would prevent any irregularities

last version would help to set up outdated filters to carry out their cyclical updates by the filter maintainer

status can help you determine the progress of work on the rule

**Comment by jspenguin2017** [comment]
Is there a reasonable implementation that exist? 
There isn't a reasonable way to handle "priority", but it's possible to handle just a "level" value. Like rules above the set level are ignored.

**Comment by elypter** [comment]
i would also love to see a blocking level slider. you could combine stable filters and more risky, generic or experimental ones in the same list and adjust it if too many sites break. this was partially the reason for the feature to switch lists on or off for individual sites. the current level of the slider will also help to narrow down the filter in question in case of a bug report.

**Comment by jspenguin2017** [comment]
The "slider" will only control which filter to enable, which filter overrides which one will follow current rules, that will *not* change. 
I don't want to get things too bloated, although I understand that you want multi-function filters, I think there is a better system to organize this.

**Comment by jspenguin2017** [comment]
Most of these suggestions are result of the poor design of the 3rd party panel, which is horrifyingly hard to use once you have more than 5 custom filters. 
I think the correct way to fix problems like this is to have a proper filter lists manager, with groups, sorting, sifting, and batch action. 
Maybe also filter profiles like we discussed earlier. 

I think it's up to the filter maintainers to separate different functionalities to different files, I can probably add a "install filter package" but inline filter hints is not the right way to address the problem IMO. 

Either way, this is probably below the end of my todo list, as I have many other features I want to work on first.

**Comment by elypter** [comment]
i agree. i imagine it like this:

!&[L: 1-3]
*/ads/banner.jpg

!&[L: 4-10]
*/ads/*

**Comment by jspenguin2017** [comment]
Huh, that is actually something to consider. 
But I'll say no to the other options (type, quality, etc).

**Comment by jspenguin2017** [comment]
I honestly don't want to implement this, but I would accept a PR.

**Comment by Ravizz** [comment]
>  @jspenguin2017 : the poor design of the 3rd party panel, which is horrifyingly hard to use once you have more than 5 custom filters.

I agree, and this:  https://github.com/gorhill/uBlock/issues/3466 is an example of why.
Aanother usefull functionality declined, usefull for filter creators, because it helps to faster bisect/narrow broken filters, by disabling groups of filters lists, doing it one by one is cumbersome.

**Comment by jspenguin2017** [comment]
I'll remake the 3rd party panel, although the filter level hints are for another day.

**Comment by elypter** [comment]
that sounds like a good idea if you find something that is compatible with your new dashboard

**Comment by KonoromiHimaries** [comment]
> i would also love to see a blocking level slider

blocking level slider per one site 
in popup panel, this is the best : D

**Comment by KonoromiHimaries** [comment]
@ameshkov what your thinking about that idea?

**Comment by jspenguin2017** [comment]
I think it's ridiculous.

**Comment by Ravizz** [comment]
As for https://github.com/NanoAdblocker/NanoCore/issues/105#issuecomment-361522755 another example is here: https://github.com/gorhill/uBlock/issues/3480, no talk, no answer why, just closed.
