### ISSUE TITLE
consider a flush cache and add scroll bar button

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#106]
I think a flush (in memory browser) cache button in the dashboard can be useful. 
Also, an add scroll bar button to popup panel sounds good as well.

**Comment by elypter** [comment]
what do you mean by "add scroll bar button"? for the website or for the popup panel?

**Comment by jspenguin2017** [comment]
Clearly for website.

**Comment by jspenguin2017** [comment]
https://github.com/NanoAdblocker/NanoCore/pull/107
5 buttons can fit on a row, but since we are adding bug reporter soon, I'll make room for it now. 
I'm not sure which icon to use for force enable scroll. All available icons are here: https://fontawesome.com/v4.7.0/icons/

![image](https://user-images.githubusercontent.com/7283682/35714704-917c4486-078b-11e8-92fb-f144e2ac557f.png)
![image](https://user-images.githubusercontent.com/7283682/35714709-966e3f8a-078b-11e8-9f2d-e3603af7180f.png)

**Comment by elypter** [comment]
cant you use icons from other sources? i think something like this would be easier to understand:
https://ixquick-proxy.com/do/show_picture.pl?l=deutsch&rais=1&oiu=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Flinecons-layout%2F512%2Fscroll_bar-512.png&sp=1098ff5f6de3f9146d8961869815d84f

https://ixquick-proxy.com/do/show_picture.pl?l=deutsch&rais=1&oiu=https%3A%2F%2Fwww.iconexperience.com%2F_img%2Fo_collection_png%2Fgreen_dark_grey%2F512x512%2Fplain%2Fscroll_bar_vertical.png&sp=d73c8fb98395939e7e0948bad8a36235

https://ixquick-proxy.com/do/show_picture.pl?l=deutsch&rais=1&oiu=https%3A%2F%2Fcdn1.iconfinder.com%2Fdata%2Ficons%2Fuser-interface-11%2F100%2F34-512.png&sp=33213dab63b384d50c7714ef27a51b42

https://ixquick-proxy.com/do/show_picture.pl?l=deutsch&rais=1&oiu=https%3A%2F%2Fimage.freepik.com%2Ffree-icon%2Fscroll-bar_318-47541.jpg&sp=be04e3a3030a768e12f0dfeba7f43aad

if it has to be one from the list i would prefer the arrows-v icon

**Comment by elypter** [comment]
if you add this then you could also add a force zoom button. i made a userscript for that purpose but it doesnt seem to work and i dont know how to debug userscripts on mobile. maybe it still helps you a bit https://greasyfork.org/de/scripts/36755-freezoom

**Comment by jspenguin2017** [comment]
I don't want the icon to be an image, it doesn't scale well on different devices. 

For zoom, I think the meta is parsed when it is first seen and changing it won't do anything. Most browsers have an option to ignore no zoom directive though. 

I would add force enable right click and copy, if there is a clean way to do it. We can look at that later, but not in this issue. I created a new issue for that: https://github.com/NanoAdblocker/NanoCore/issues/109

**Comment by jspenguin2017** [comment]
Can someone alert me when gorhill uploads 1.15.0 to web store?

**Comment by reunicorn** [comment]
Sure, I'll let you know when I see 1.15.0 on Chrome's web store :)
BTW I assume you already know it's been uploaded to the [Firefox Add-on Page](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)?

**Comment by jspenguin2017** [comment]
Oh wow, I totally missed that. Thx, I'll publish new version now.

**Comment by jspenguin2017** [comment]
gorhill put the tag on the wrong commit... I pulled more than I wanted... Hum... hopefully it won't blow things up.

**Comment by jspenguin2017** [comment]
I question the usefulness of this... I'll keep it disabled for now. 
<details>

![image](https://user-images.githubusercontent.com/7283682/35763225-ac24358a-0864-11e8-9a21-1ee758303204.png)
![image](https://user-images.githubusercontent.com/7283682/35763234-c4cfed4a-0864-11e8-8b24-4552a4eb53a4.png)

</details>

**Comment by jspenguin2017** [comment]
I got the binaries built, but the Edge version is having some technical difficulties, I'll iron it out later. Looks like MS isn't reviewing my extension any time soon.

**Comment by jspenguin2017** [comment]
OK, now back to topic... Where should I place the flush cache button? If I put it in the dashboard the user will have to jump back to click it. 
I'm not sure how should I design it if I put it in the popup panel. As there is the other refresh button.

**Comment by jspenguin2017** [comment]
Edge build is fixed.

**Comment by jspenguin2017** [comment]
I'm not sure how useful a flush all cache button will be. I exposed the refresh button which allow you to refresh the active page while bypassing cache. I'll see how this goes, I can always add flush all cache button on the side if it turns out to be needed. 
https://github.com/NanoAdblocker/NanoCore/pull/117
