### ISSUE TITLE
add update all filter button in the popup panel

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#108]
suggested icon
https://fontawesome.com/v4.7.0/icon/refresh/

**Comment by jspenguin2017** [comment]
You shouldn't need to do that too often, I don't want to overload the popup panel.

**Comment by jspenguin2017** [comment]
Forcing a full update isn't something that you want more often than once a day. Adding a button for that does not make sense. I will only add useful buttons specific to the active page to the popup panel.
