### ISSUE TITLE
replace ad with a custom text communicat

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#115]
you can add new rule to i can replace any ad to a communicat ( with custom text )

example rule.
`www.wp.pl##.tayc7o0$replacetext=(I Don't can block this ad)`

example.
![2018-02-07-wirtualna polska - wszystko co wazne - www wp pl](https://user-images.githubusercontent.com/5884000/35916020-43891e84-0c09-11e8-8002-589dc3458fce.png)

replace with.
![2018-02-07-wirtualna polska - wszystko co wazne - www wp2](https://user-images.githubusercontent.com/5884000/35916140-b545ceb4-0c09-11e8-8a94-4d995e51908f.png)

**Comment by jspenguin2017** [comment]
Can you elaborate? What is it for?

**Comment by jspenguin2017** [comment]
I won't allow custom messages because that's too easy to abuse.

**Comment by KonoromiHimaries** [comment]
maybe you can use a prepared earlier labels.

**Comment by jspenguin2017** [comment]
First, it should be `I can't` and not `I don't can`. 
Second, do you have good examples where this is useful? If you need to match an element (`.tayc7o0` in your example), chances are something can be done to remove the ads already.

**Comment by jspenguin2017** [comment]
There are two problem with this proposal: 
- If you can place the message on an element, more likely than not you can block that element itself, in which case placing the message would be useless. 
- The time it takes for you to flag a website as "require Nano Defender" you already fixed it with filters. With Nano's extended script snippets, there are only a handful of websites that actually require a separate extension. 

I'll close this as I don't think it is useful and just expand attack surface.
