### ISSUE TITLE
how to force the animation to stop on force scroll mode

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#118]
on this site
`http://tkn24.pl/`

automove on force scroll mode still works. i dont can stopped this animation.

![2018-02-11-tkn24 _ konskie wiadomosci informacje wydarzenia video](https://user-images.githubusercontent.com/5884000/36071617-3337361e-0f11-11e8-816c-c2c6dfc32980.png)

**Comment by KonoromiHimaries** [comment]
force scroll mode don't work on this site
`https://augustowskireporter.pl/`

nothing
![2018-02-11-prasa regionalna - augustow - gazeta augustowski reporter kopia](https://user-images.githubusercontent.com/5884000/36075479-d3a41976-0f4f-11e8-8707-d7c84519d35d.png)

**Comment by jspenguin2017** [comment]
Force scroll will break layout, as stated in the tooltip, I don't have a good way to reliably force enable scrolling without the potential of breaking layout. Just refresh the page to revert the change. 

I don't see the problem with `augustowskireporter.pl`, can you elaborate?

**Comment by KonoromiHimaries** [comment]
**example 3.**

![2018-02-13-kolekcje dinaro ii - black red white](https://user-images.githubusercontent.com/5884000/36139253-1bba91ba-109d-11e8-9139-aca064c05e93.png)
`https://www.brw.com.pl/katalog-produktow/?k=437,dinaro-ii`

**Comment by jspenguin2017** [comment]
Force scroll mode isn't meant to be clicked for nothing, only if you need it.

**Comment by elypter** [comment]
i think an annoyance filter or a userscript might be better suited for a site specific problem

**Comment by jspenguin2017** [comment]
The force scroll is for when you zapped the anti-adblock overlay but the scrolling is locked. If the website scrolls fine to begin with, then *don't* mess with the scrolling. 

I'm not saying the implementation is good, but links you shown are not good test targets and the functionality is not designed to solve the problem you have. 

![image](https://user-images.githubusercontent.com/7283682/36182905-140b548a-10e9-11e8-8fe8-636cb2094bf2.png)

**Comment by KonoromiHimaries** [comment]
![2018-03-17-radio ziemi wielunskiej - jedyne takie radio](https://user-images.githubusercontent.com/5884000/37555186-0d9260ee-29e4-11e8-8fe4-0176a64593cf.png)
`http://radiozw.com.pl/`

**Comment by jspenguin2017** [comment]
If it breaks the website, then *don't* click it. That's all.
