### ISSUE TITLE
Nano Adblocker for MS Edge..

### ISSUE THREAD

**Issue by ghost** [NanoAdblocker/NanoCore#120]
### Describe the issue:
Hey there, i want to give MS Edge a try.. but uBlock origin doesn't works well so good with Edge's limitations, because i want to add (protection) to it (for disabling messages like: Please disable your Adblocker) but in uBlock you can't do much.. and with Nano Adblocker/Defender you can! but is Nano Adblocker/Defender the same as uBlock origin how it performs in ways.. and is it safe to use? :/ and i see uBlock filters are also listed in the Nano adblocker, and enabled, should i leave it so?

### Environment:
- Operating System and Version:  Windows 10 Version/Build: 1709 / 16299.214
- Browser and Version: Microsoft Edge 41.16299.15.0 / Microsoft EdgeHTML 16.16299
- Nano Adblocker Version: 1.0.0.30

**Comment by jspenguin2017** [comment]
First, you shouldn't ask me if it's safe to use because I wrote it, I obviously will tell you it's safe. It's ultimately up to you to verify the source code and judge by yourself. 

The configuration does not need to be changed, also, you should only use one adblocker at one time.

**Comment by Fl4m3ThR0wEr** [comment]
Just wanted to know, sorry :/ but when will Nano Adblocker/Defender will come available on Edge? because Edge does have Limitations and where is the github page for Chrome issues? :/ i can't find any related Chrome thread for isseus? :s and i'll hope Nano Adblocker/Defender will grow up and become popular :) your good dev. btw i like the Icons of Nano :D

**Comment by xlollomanx** [comment]
@Fl4m3ThR0wEr Firstly, I use addons developed from jspenguin2017 from many month and I can tell you that his work is amazing and completely safe. Secondly I think it's not fair ask for eta's, it will be ready when it ll be ready. Review from Microsoft can take very long time, as far as I know, but for now you can manually install Nano Adblock and Nano Defender on Edge.

**Comment by jspenguin2017** [comment]
It will be published when enough people requests Microsoft to do so: 
https://developer.microsoft.com/en-us/microsoft-edge/extensions/requests/

**Comment by Fl4m3ThR0wEr** [comment]
When i **download** the **ZIP.archive** from the releases site for Edge, and extract it in folder, and when i click **Load extension on Edge** i cant finy any of Nano Adblocker/Defender.. Whats the problem here? :/

**Comment by jspenguin2017** [comment]
Just click the folder and click select folder. It works for me: 
![image](https://user-images.githubusercontent.com/7283682/36175403-82ae4b30-10cc-11e8-9ea2-af0673b51248.png)

**Comment by Fl4m3ThR0wEr** [comment]
@jspenguin2017, when i try to load Nano Defender (Edge says: theres a Manifest.JSon problem can't load the extension) and i try it by all the releases of Defender it don't work :( is Nano Adblocker right now enough for Edge or do it need Defender to protect from (Please disable your adblocker) messages?

**Comment by ZZYSonny** [comment]
What should we write in the request page? Can we have an example one?

**Comment by jspenguin2017** [comment]
@Fl4m3ThR0wEr I thought I tested it... It'll be sorted out for sure after platform builder is working. Which website is showing the message? 

@ZZYSonny I guess anything reasonable, it's probably handled by a bot.

**Comment by ZZYSonny** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/extensions/requests/
This page is only for Developers, not for user to request new plugin. What we can do is only writing in Feedback Hub. (Does writing in Feedback Hub means asking MS to write the plugin?)

**Comment by jspenguin2017** [comment]
Well, there's a link there, I don't know more. 
![image](https://user-images.githubusercontent.com/7283682/36213350-b7200452-1163-11e8-9fc3-267a7c007653.png)

**Comment by kevin12314** [comment]
This is my feedback：https://aka.ms/Sddcys
You can click upvote to made Microsoft to notice this feedback.
But I still want someone add a feedback and share link here in United States region, because 
I still think Microsoft is more concerned about the United States region.

**Comment by ZZYSonny** [comment]
@kevin12314 voted.
