### ISSUE TITLE
Replace remote fonts instead of blocking them or html5 videos have missing icons

### ISSUE THREAD

**Issue by nitrocode** [NanoAdblocker/NanoCore#127]
### Describe the issue (Required)

Unsure if this is the right area to create this...

I enabled `Block remote fonts` and noticed that videos, in particular, were missing their respective play, mute, etc type icons. I was wondering, just like how certain scripts are replaced with dummy scripts, how difficult would it be to in leau of blocking remote fonts, replacing them with local ones instead?

### Screenshots (Required)

![adblock](https://i.imgur.com/39teAcq.png)

### URLs where this issue occurs (Required if applicable)

https://www.forbes.com/sites/forbestechcouncil/2017/12/21/13-top-tech-skills-in-high-demand-for-2018/

#### Environment (Required)

- Operating System and Version: ubuntu 16.04
- Browser and Version: chrome 64
- Nano Adblocker Version: latest
- Nano Defender Version (Optional if you are not using it): latest

#### Your filter lists (Required)

Default except for enabling `Block remote fonts` enabling

#### Your custom filters (Required if you have any)

None

**Comment by jspenguin2017** [comment]
Replace with what?

**Comment by nitrocode** [comment]
I'd imagine a script could detect the included source and then detect the `class` and / or the character used within the tag's `text`, then if it found a match, it could replace that icon with a similar local one.

**Comment by jspenguin2017** [comment]
I guess that would work for standard fonts, I guess what you are requesting fits https://github.com/Synzvato/decentraleyes better.
