### ISSUE TITLE
! Expires  Alternative 4 hosts?

### ISSUE THREAD

**Issue by Crystal-RainSlide** [NanoAdblocker/NanoCore#128]
### Describe the issue
Whether `# Expires` can be used to tag the update time for hosts like `! Expires` in filters?

**Comment by jspenguin2017** [comment]
No, but I can add that, should be easy enough.

**Comment by Crystal-RainSlide** [comment]
Great~
(Maybe feature like this should be add to some conspicuous place, so the maintainers can see that.

**Comment by jspenguin2017** [comment]
I currently have all my docs here: https://github.com/NanoAdblocker/NanoCore/tree/master/Notes

**Comment by jspenguin2017** [comment]
It's implemented, I still need to update the docs though.

**Comment by jspenguin2017** [comment]
I got proper docs up now. 
https://github.com/NanoAdblocker/NanoCore/blob/master/notes/filter-list-authoring.MD#filter-list-authoring

**Comment by jspenguin2017** [comment]
This is merged upstream: `https://github.com/gorhill/uBlock/pull/3679`
I'll see if I can get `ubo://` merged upstream too.
