### ISSUE TITLE
Odd filters count

### ISSUE THREAD

**Issue by Raaviz** [NanoAdblocker/NanoCore#132]
Didn't check but I guess the same happens in NA: https://github.com/gorhill/uBlock/issues/3575

**Comment by jspenguin2017** [comment]
It's by design, and I agree with gorhill's decision.

**Comment by Raaviz** [comment]
Whatever, but such odd filters count SUCKS.

**Comment by jspenguin2017** [comment]
If you think it can be done better, please fork and add necessary patches. I may change my mind after testing out your changes.
