### ISSUE TITLE
High memory footprint?

### ISSUE THREAD

**Issue by chelseaislan** [NanoAdblocker/NanoCore#133]
### Describe the issue (Required)
Is it normal when Nano Adblocker runs with high memory usage? My laptop has 4GB of RAM.

### Screenshots (Required)
![screenshot 46](https://user-images.githubusercontent.com/30471081/37189225-c70cefa4-2385-11e8-8181-1ed504550c67.png)

#### Environment (Required)

- Operating System and Version: Windows 10 1709
- Browser and Version: Chrome 65
- Nano Adblocker Version: 1.0.0.34
- Nano Defender Version (Optional if you are not using it): 13.42

#### Your filter lists (Required)
Default ones + ABPindo

**Comment by jspenguin2017** [comment]
Is that high?

**Comment by jspenguin2017** [comment]
The JavaScript heap is only 31 MiB though: 
![image](https://user-images.githubusercontent.com/7283682/37189785-497259c0-2313-11e8-9e46-14bebb563a40.png)

**Comment by jspenguin2017** [comment]
Could be a browser problem, seems fine on Canary. 
![image](https://user-images.githubusercontent.com/7283682/37189906-fae4ca3a-2313-11e8-9c3f-c5780aeefd36.png)

**Comment by jspenguin2017** [comment]
Maybe it's a browser bug maybe not, but either way, I wouldn't consider this to be a problem right now.
