### ISSUE TITLE
Choose what to block

### ISSUE THREAD

**Issue by sliperhr** [NanoAdblocker/NanoCore#134]
is the choose what to block option is gone?
![screenshot_1](https://user-images.githubusercontent.com/33209981/37359580-f4b0f60c-2728-11e8-9546-3224672ade4c.jpg)

**Comment by jspenguin2017** [comment]
What do you mean?

**Comment by sliperhr** [comment]
before this in the firewall panel there is two box with the + or- icon,we can choose to block some site that we dont want,where it is gone?

**Comment by jspenguin2017** [comment]
Dynamic filtering is only available in advanced mode.

**Comment by sliperhr** [comment]
thanks :)
