### ISSUE TITLE
Please add Safari support

### ISSUE THREAD

**Issue by yetisyny** [NanoAdblocker/NanoCore#135]
There is no issue for tracking support for the Safari web browser so I thought I would create it. Currently it seems nobody has ported Nano Adblocker to Safari. However, Nano Adblocker is based on uBlock Origin which HAS been ported to Safari, see here: [https://github.com/el1t/uBlock-Safari](https://github.com/el1t/uBlock-Safari).

So all that needs to be done is to merge Nano Adblocker with that Safari extension, since both are based on uBlock Origin. Merging them would create a Safari version of Nano Adblocker. I am not sure how difficult merging them would be, or how well it would work after that, though. Anyway, since Nano Adblocker already supports Chrome, Firefox, and Edge (3 of the 4 major browsers supported by uBlock Origin), it would be nice to get to 4 out of 4 and have Nano Adblocker support ALL of the same browsers uBlock Origin does.

Although it is possible that some of the more advanced functionality of Nano Adblocker not present in uBlock Origin relies on APIs that do not exist for Safari extensions which might make porting a bit harder since this would either mean some features not working on Safari or workarounds being necessary on Safari. So the difficulty of porting it to Safari is unknown. But I think having an issue to track support for Safari is useful.

I am talking about the macOS (Mac OS X) Safari, obviously, since that is what uBlock Origin supports. Supporting Safari for iOS would be a lot more difficult since uBlock Origin does not support that, and Safari for Windows is insecure abandonware that hasn’t been updated since version 5.1.7 in 2012, so this issue is only regarding a port to the macOS version of Safari, to try to get parity in number of browsers ported to with uBlock Origin which is based on the same code as Nano Defender.

**Comment by jspenguin2017** [comment]
I'm not rich enough. If you can sponsor me a development device and a developer license, then sure, I will try.

**Comment by yetisyny** [comment]
OK I understand the not supporting Safari thing, you don’t own a Mac, I didn’t mean that you personally need to support Safari.

If there is a developer out there who wants to port this to Mac, they can do it, I thought, we could leave this bug open and wait for a developer who owns a Mac and who has an Apple developer account to volunteer to work on it.

That is a good point though about how Nano Defender needs to be ported too, I forgot to mention Nano Defender in my original post. So whatever developer out there who is a fan of Nano Adblocker + Nano Defender who owns a Mac and wants to port it to Safari would have to do the porting work for Nano Defender from scratch since Nano Defender is something you wrote from scratch and is NOT based on uBlock Origin. They would BOTH need to be ported to Safari.

I happen to own a Mac myself, technically it is “unsupported” since it is a bit old, I use patcher tools from a guy named dosdude1 to use recent versions of macOS on the old hardware. And $99/year is too steep a price for me, if I had more money I would upgrade to newer hardware MUCH sooner than I would pay for an Apple developer account.

But there are people with more recent Macs who DO work on Safari extensions already and already have paid Apple developer accounts. All we need to do is find one of them and get one of them to help out. I already thought of somebody: the guy doing this for uBlock Origin, @el1t. He clearly has the expertise and knows the uBlock Origin codebase and has an Apple developer account and has ported uBlock Origin to Safari. Maybe he could do it for the 2 Nano extensions (Adblock and Defender) too. I have never talked to him and am not sure if he would be willing to do it, all I am saying is, he is definitely CAPABLE of doing it, he has the hardware, the developer account, and the skills. Maybe someone could even pay him to do it, that would be a good incentive.

And if he won’t do it we might be able to find someone else. Plenty of people out there have Apple developer accounts as well as Mac computers, we just need to find someone with the right skills who is willing to take on this job. I was kinda hoping this bug report would be a recruiting tool to help find someone willing to port these extensions. That was my main purpose in filing it. I did not expect the original extension author @jspenguin2017 to be the one to port it, I figured, multiple developers can have a division of labor, makes things easier for everyone than making just 1 developer do all the work, plus I figured, not very likely that the original extension author owns a Mac. Never my intention to make @jspenguin2017 do the work. Anyone can do it if they have the right skills at porting extensions from Chrome to Safari, a fairly recent Mac, and an Apple developer account, but best to find someone who already has all of those things already, makes things easier for everybody.

**Comment by jspenguin2017** [comment]
I don't think the issues tracker is the right place for recruitment posts. I do have it on the home page: 
![image](https://user-images.githubusercontent.com/7283682/38253839-eefc28fc-3714-11e8-8ebf-e41c8af8b068.png)

Also, Nano Defender is not written from scratch, it's based on Anti-Adblock Killer. Yes, it's a lot different now but over half of the code are from AAK.
