### ISSUE TITLE
Question about the "UBO Extra addon"

### ISSUE THREAD

**Issue by mikhoul** [NanoAdblocker/NanoCore#141]
I'm migrating slowly to chrome from Firefox and  since NC is a fork from UBO I'd like to know if I need to install "[Ublock Origin Extra](https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco)" to block "Instart Logic" and webRTC tracking/adds with NanoCore ? 

Regards :octocat:

**Comment by jspenguin2017** [comment]
You should stay with uBO if you plan on using Firefox.
