### ISSUE TITLE
Add support for blocking of Websockets/WebRTC based ads

### ISSUE THREAD

**Issue by sjclayton** [NanoAdblocker/NanoCore#143]
Something along the lines of what uBlock Origin Extra is / was designed to do...

Unless I'm missing something and there is already support for blocking these.

**Comment by jspenguin2017** [comment]
Can you be more specific?

**Comment by sjclayton** [comment]
I'm talking about the type of ad's that are injected into pages dynamically via Websockets or WebRTC, that normal filtering rules do not work on... because the code that is getting injected changes (hence the dynamic bit) every time the page is reloaded. 

I don't know how to explain it better than that, sorry.

**Comment by sjclayton** [comment]
I switched mainly for the anti-adblock component, as well as liking the direction you're going.

**Comment by jspenguin2017** [comment]
Chrome has native WebSocket filter event a while ago, so make sure to update your browser. 
WebRTC interception was removed from uBO-Extra a while ago as well. 
I'm unsure what you are referring to.

**Comment by mikhoul** [comment]
I'm pretty sure @sjclayton want to know if those protections  from **uBO-Extra** are included in **NanoAdblocker**: https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful

**Comment by jspenguin2017** [comment]
Ah, it's in Nano Defender.
