### ISSUE TITLE
[Minor] Popup: per-site switches partly invisible if Zoom 125% of Dashboard

### ISSUE THREAD

**Issue by BilBg** [NanoAdblocker/NanoCore#144]
### Describe the issue (Required)
I like to use Zoom 125% of Dashboard (which automatically zooms the Popup) - I prefer both to be that way for my monitor / resolution / eyes combination.

Because of more icons on Nano Adblocker (compared to uBlock Origin) the bottom of Popup is truncated.
(uBlock Origin Popup is OK up to 150%, "needs" 175% to become truncated.)

Possible cause: The maximum size of Popup allowed by the browser is reached.

Possible fix: If it's not that hard can you add setting to hide cache control section / button?
(I don't really need it as I use F5 Ctrl+F5 in rare cases when I want to reload page)

### Screenshots (Required)

Nano Adblocker v1.0.0.38 - Popup - Zoom 125%.png

![Nano Adblocker v1.0.0.38 - Popup - Zoom 125%.png](http://store.picbg.net/pubpic/CD/04/792f5fdd165acd04.png)

uBlock Origin v1.15.18 - Popup - Zoom 125%.png

![uBlock Origin v1.15.18 - Popup - Zoom 125%.png](http://store.picbg.net/pubpic/8B/9D/795c7a02400e8b9d.png)

uBlock Origin v1.15.18 - Popup - Zoom 175%.png

![uBlock Origin v1.15.18 - Popup - Zoom 175%.png](http://store.picbg.net/pubpic/29/4C/0b70ae70553a294c.png)

### Reproduction Steps (Optional if trivial)

1. Open the Dashboard 
2. Zoom it (`Ctrl`+`+` | `Ctrl`+`-` | `Ctrl`+`0`) to whatever % you want
3. Click the icon of Nano Adblocker and observe the Popup

### Anything else you believe to be useful (Optional):
Monitor: Philips 201B4 - CRT 21" - 1600 x 1200 @ 85 Hz

https://www.usa.philips.com/c-p/201B40_74H/53-cm-21-inch-qxga

The maximum size of Popup allowed by the browser seems to be 800 x 600 (internal size, without Popup's border)

#### Environment (Required)

- Operating System and Version: Windows XP
- Browser and Version: Chromium 50 (FlashPeak Slimjet 10.0.13.0 - last possible on Windows XP)
- Nano Adblocker Version: v1.0.0.38
- Nano Defender Version (Optional if you are not using it): --

#### Your filter lists (Required)

N/A

#### Your custom filters (Required if you have any)
N/A

**Comment by jspenguin2017** [comment]
Hum... Interesting problem, I never thought of that.

**Comment by BilBg** [comment]
I added some info under "Anything else you believe to be useful"

**Comment by jspenguin2017** [comment]
I can take a PR for this, otherwise, this will not be implemented as I don't need it.

**Comment by jspenguin2017** [comment]
Closing as fixed, in the next release, the popup panel will scroll vertically if it doesn't fit.
