### ISSUE TITLE
Use a translation service

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#147]

**Comment by jspenguin2017** [comment]
I'm considering crowdin.com that uBO is using.

**Comment by hawkeye116477** [comment]
Transifex doesn't accept messages.nano.js, I tried to upload it, but gives error. Lingohub is also alternative and has integration with GitHub.

**Comment by jspenguin2017** [comment]
Yea it's not a proper JSON, because I want to add comments to it, that's not a problem though, I can add a script to process it into a proper JSON.

**Comment by jspenguin2017** [comment]
The new locale file of Nano Core 2 uses kind of "macro expansion" in JSON. Some text are evaluated and generated on the fly. I don't think any translation service support that...

**Comment by jspenguin2017** [comment]
I think I have found a solution.

**Comment by jspenguin2017** [comment]
I still need to: 
- Port old translations over
- Make pulling changes automated

**Comment by jspenguin2017** [comment]
It's too much work to port translations over manually, I need to script it...

**Comment by jspenguin2017** [comment]
Also, we have a few more strings to translate, @DandelionSprout do you have some time to have a look?

**Comment by DandelionSprout** [comment]
Sure thing. 🙂

**Comment by jspenguin2017** [comment]
OK, I see why gorhill has a script to import changes now...
