### ISSUE TITLE
This extension failed to redirect a network request 

### ISSUE THREAD

**Issue by orschiro** [NanoAdblocker/NanoCore#148]
Dear all, 

Is it safe to allow another extension called [Sessionbox](https://chrome.google.com/webstore/detail/sessionbox-free-multi-log/megbklhjamjbcafknkgmokldgolkdfig) the redirect?

And if so, how do I solve this extension conflict?

Thank you for your help!

![image](https://user-images.githubusercontent.com/170947/38855231-374e7592-4223-11e8-8166-416f6fe4b490.png)

![image](https://user-images.githubusercontent.com/170947/38855241-3fb24236-4223-11e8-9b66-672947325b94.png)

**Comment by jspenguin2017** [comment]
I don't know if it is safe, if you think it is, just whitelist the file.

**Comment by orschiro** [comment]
@jspenguin2017 thank you!
