### ISSUE TITLE
script snippet error

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoCore#149]
when visiting vivo.sx video links eg: https://vivo.sx/f614d51a3b i get this error in the console

```
[Nano] Script Snippet :: 
TypeError: can't redefine non-configurable property "_0x773d"
Stack trace:
@https://vivo.sx/f614d51a3b:16:2
@https://vivo.sx/f614d51a3b:2:2
```
firefox 58.0.2, nano adblocker 1.0.0.41

**Comment by jspenguin2017** [comment]
Can't reproduce. Are you using other extensions?

**Comment by elypter** [comment]
i tried it on a fresh firefox profile with a fresh nano installation and nothing else.

linux mint mate 18.3 32bit, kernel: 4.16.2, i945 gpu with opengl 1.4 if any of that matters. location: germany.

**Comment by jspenguin2017** [comment]
Probably a conflicting script rule, it's fine as long as the webpage works.
