### ISSUE TITLE
So where do we go now for Nano Defender for Firefox?

### ISSUE THREAD

**Issue by Corruptinglyneedful** [NanoAdblocker/NanoCore#151]
With having officially closed the only discussion thread and having ended support for Firefox and Nano Defender; I want to know where I go next.

Does this also mean that Nano Adblocker is discontinued for Firefox as well?

**Comment by elypter** [comment]
here are backups of the last version that i could extract from my browser https://github.com/elypter/nano-adblocker-for-firefox-backup

**Comment by TonyTough** [comment]
> Looks like the only one is here: https://github.com/krystian3w/NanoDefenderFirefox

Works great for me with Firefox and Ublock Origin and finally supports auto-update since version 13.60

**Comment by gluons** [comment]
@jspenguin2017 Excuse me. I've seen your comment from [#41](https://github.com/NanoAdblocker/NanoCore/issues/41#issuecomment-383588819):

> The support for Firefox has officially ended. No more Firefox build will be produced.

Sorry to bother you.  
Could you tell my the reason that Firefox support ended?  
I really love your work. I've moved from uBlockOrigin to NanoAdblocker. It makes my life better.  
But now it's gone. 😭

**Comment by gluons** [comment]
@hawkeye116477 Thank you very much to let me know. I get it now.  
He really works hard. He does everything without accepting any donation.

**Comment by jspenguin2017** [comment]
I don't have time to deal with the weird policy from Mozilla. I know how to properly use `innerHTML` and I don't need to have a vetted DOM library. 
Also I don't want to maintain 3 different versions, the Edge build is a shim on top of Chromium build, unlike Firefox build which is completely different.

**Comment by elypter** [comment]
if the problem is to get the addon signed then you can go with an unsigned one as well. it works in firefox-unbranded developer edition and waterfox

**Comment by jspenguin2017** [comment]
Yes, I have unsigned official build here: https://github.com/jspenguin2017/uBlockProtector/releases

**Comment by Corruptinglyneedful** [comment]
Those builds are not official and they suffer from the same problems that
Mozilla is trying to fix.

**Comment by hawkeye116477** [comment]
But @gluons talked about Nano Adblocker. There are no newer Nano Adblocker's unsigned versions.

**Comment by TonyTough** [comment]
>but versions with updates.json are on krystian3w repo

The automatic updates work for me on windows 7, but not on a windows 10 system (all other add-ons update without problems).
Does it work for others on windows 10 ?

**Comment by jspenguin2017** [comment]
@TonyTough For that you need to report to @krystian3w . He didn't move to the new build engine BTW, I can't say about the quality of his builds.

**Comment by krystian3w** [comment]
On my Windows 10 works when manually find newest version.

Maybe change find new addons from 1 day to 6 hours in `about:config` correct this situation.

> `extension.update.interval` ➡ 21600 
>
> `extension.update.enabled` ➡ true

**Comment by xlollomanx** [comment]
@TonyTough @krystian3w Are you using kaspersky as antivirus? I found some times ago that if you are using Firefox you have to disable "Scan encrypted connections" in Settings>Advanced>Network, otherwise it will get some troubles even if you put this site in the exceptions . Maybe this affect even other AV. In this case if you disable that option, automatic update of Nano defender build from @krystian3w works. 

P.S. @krystian3w Sorry for not helping you to build ff nano defender. Atm I have my exams and I'm not very familiar with github so I think you can remove me from contribution because I'm afraid to mess it up
