### ISSUE TITLE
Small Request for the popup

### ISSUE THREAD

**Issue by mikhoul** [NanoAdblocker/NanoCore#155]
First thanks for your work :+1: 

Could you ad in the popup over the local/global columns a label to identify those 2 columns ?

Like this:

![GitHub Logo](https://i.imgur.com/CLvrCJg.png)

It would help to remember especially for the newbies and non tech people the purpose of those 2 columns.

Regards :octocat:

**Comment by jspenguin2017** [comment]
Eh, that would not be trivial... Newbies and non-tech aren't supposed to use advanced mode.

**Comment by mikhoul** [comment]
We all have to begin somewhere to learn more and it's a "low effort" change... 😉

**Comment by jspenguin2017** [comment]
Can you PR?

**Comment by mikhoul** [comment]
If you are to integrate it I will make the popup.html and popup.css modifications and send it.

Let me know.

Regards :octocat:

**Comment by jspenguin2017** [comment]
I will always consider good pull requests, if you can do it well there is no reason for me to not take it.

**Comment by mikhoul** [comment]
Good news :smile: .

I will take a look to see the better way to implant it so it will look good on "basic mode" and "advanced mode" since the formatting is not exactly the same. 

I have already done the CSS/HTML for the advanced mode so I just have to look to make it compatible with the "basic mode". 

Will be back soon to push it.  :octocat:

**Comment by jspenguin2017** [comment]
Sounds good. Keep these in mind: 
- Does it look good when the pane is collapsed? 
- Does it look good when advanced settings is off? 
- Does it look good on Edge? 
- Did you update locale entries?

**Comment by jspenguin2017** [comment]
I'll close this as won't fix. 
A proper fix is non-trivial, as you probably realized by now.

**Comment by gwarser** [comment]
First row have tooltips
