### ISSUE TITLE
Yandex browser is't be supported?

### ISSUE THREAD

**Issue by mat41997** [NanoAdblocker/NanoCore#16]
i don't can instal nano adblock on yandex browser in ( android  5.0 )

example. nano defender and ublock origin 1.14.20 has works normaly on yandex browser

see in reviews
```https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo/reviews```

to reproduct
+ try install the nano adblock on yandex

filters
this is dosen't matter
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ss
![screenshot_2017-12-10-13-55-18](https://user-images.githubusercontent.com/5884000/33805031-e585abb6-ddb1-11e7-9a28-52a1d984fea6.png)

**Comment by jspenguin2017** [comment]
It's a bug, I fixed it in the next version, I'm publishing it.

**Comment by jspenguin2017** [comment]
Just need to wait for Google to review it, probably will take a day again.
