### ISSUE TITLE
msn.com

### ISSUE THREAD

**Issue by det427** [NanoAdblocker/NanoCore#161]
### Describe the issue (Required)
The headline picture scroll page is blocked. It works if I turn off Nano Adblocker.

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/32418037/39676294-0ae889b2-511d-11e8-8c77-d1e1501d6189.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/32418037/39676376-9a0529ec-511e-11e8-99a8-830c0fe8155f.png)

### URLs where this issue occurs (Required if applicable)
https://www.msn.com/en-us

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 1803
- Browser and Version: Chrome 66.0.3359.139
- Nano Adblocker Version: 1.0.0.47
- Nano Defender Version (Optional if you are not using it): 14.8

#### Your filter lists (Required)
Default
List filters you have enabled or disabled from the default settings.
-->Fanboys Annoyance List

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
I can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/39676864-aeffc6b2-512e-11e8-8385-aad43c26dea8.png)

**Comment by det427** [comment]
The only way I can get it work is use an old link http://www.msn.com/
Then when it changes to https the problem happens!

**Comment by jspenguin2017** [comment]
All works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/39677250-ff2f5cd2-5134-11e8-99e3-0708caffd3b0.png)

**Comment by det427** [comment]
I uninstalled and reinstalled Nano Adblocker. Any idea what I can do?

**Comment by jspenguin2017** [comment]
Still can't reproduce even with a US proxy. I don't know what's wrong but it's likely to be a problem on your side.
