### ISSUE TITLE
Nano Adblocker for MS Edge bugs? 

### ISSUE THREAD

**Issue by seba2282** [NanoAdblocker/NanoCore#168]
I use Windows 10 1803 and Nano Adblocker for Edge official extension.
I added all filters without ignoring cosmetic filters. And I have few problems.
First: settings section privacy. all options (with webrtc) are inactive. 
Second: two filters don't work. integrated language DandelionSprouts Norske Filtre and Polish Cookies (if I add this filter from certyficate.it). The same is with Ublock Origin and only MS Edge. 

Can you help?

**Comment by jspenguin2017** [comment]
> settings section privacy. all options (with webrtc) are inactive.

That is a limitation of Edge. 

> two filters don't work. 

Can you give me links to them?

**Comment by seba2282** [comment]
I have screenshoot with this filters. Norske is integrated, cookies has link. Look on it. 
![norske filter](https://user-images.githubusercontent.com/16944478/40549756-96fead94-6038-11e8-8bc8-ec81ba2c1a18.png)

![polish cookies](https://user-images.githubusercontent.com/16944478/40549771-a2cb6bbc-6038-11e8-900b-be81eb5a01d6.png)

**Comment by jspenguin2017** [comment]
I'll test it. 
Can you copy the link? I don't want to type all that.

**Comment by seba2282** [comment]
Ok. Norske filter, you have in filters, languages, cookies filter polish here: https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/40551367-ea2298ee-5ff9-11e8-8b11-05abe1b43cc9.png)

**Comment by jspenguin2017** [comment]
Both work fine for me. It's a problem with your network connection. 
![image](https://user-images.githubusercontent.com/7283682/40551390-0037ff2a-5ffa-11e8-895a-ac2daee4d7f9.png)

**Comment by seba2282** [comment]
I try one more but doesn't work for me. I have Internet 250Mb/s, so I don't know why for me doesn't work, for you works...

**Comment by jspenguin2017** [comment]
The speed doesn't really matter, what matters is whether you can connect to the filter server or not.

**Comment by seba2282** [comment]
Region is a problem? You haven't problem. I have… How can I fix it?

**Comment by jspenguin2017** [comment]
I don't know, it's a problem on your side.

**Comment by seba2282** [comment]
Which filters you have active in Nano? I have all with cosmetic. Maybe any filter conflict with this filters?

**Comment by jspenguin2017** [comment]
That's not possible, Edge doesn't support listening to extension requests at all.
