### ISSUE TITLE
Nano Defender not compatible with Yandex Android

### ISSUE THREAD

**Issue by thewan056** [NanoAdblocker/NanoCore#169]
### Describe the issue (Required)
Chrome Store show not compatible when trying to download Nano Defender using Yandex for Android

### Screenshots (Required)
![yandexss](https://user-images.githubusercontent.com/24851051/40574513-3b5eee08-6106-11e8-891d-8056cd6a49b3.jpg)

#### Environment (Required)

- Operating System and Version:  Android 8.0
- Browser and Version: Yandex 18.4 based on Chromium 65
- Nano Adblocker Version: 1.0.0.51
- Nano Defender Version (Optional if you are not using it): 

Nano Adblocker installs and works as expected. uBO Extra installs and works also.

Both Nano Adblocker and Defender installs and works on Yandex for Windows.

**Comment by jspenguin2017** [comment]
The minimum required version in the manifest is 63, so if your browser is based on Chromium 65 I don't see why it won't let you install. Probably a browser bug.

**Comment by thewan056** [comment]
I just recalled a similar issue with HTTPS Everywhere. I couldn't install it via the chrome store. But if I visit the EFF website, I can install it directly from there. The chrome store link from the EFF website directly installs the extension on your browser without visiting the chrome store. Any idea how can I apply this work around to Nano Defender?

**Comment by jspenguin2017** [comment]
I'm not sure what they did, but you can find unsigned packages here: https://github.com/jspenguin2017/uBlockProtector/releases

**Comment by xlollomanx** [comment]
I read somewhere that yandex have something like a blacklist. I don't know why they do that but I experienced this with another addon: you can install by using chrome in developer mode but not from the store. 

more info here: https://github.com/gorhill/uBlock/issues/2071

**Comment by thewan056** [comment]
I have managed to install in via developer mode. Thanks @jspenguin2017 and @xlollomanx. 

Would like to add that Yandex blacklist pops up a not supported dialogue while attempting to install a blacklisted extension. It doesn't show the red Not Compatible button.

Also would like to add that EFF uses the Inline Installation feature shown [here](https://developer.chrome.com/webstore/inline_installation). It seems to workaround the Not Compatible issue while still having auto-updates compared to developer mode. Would like to have auto-updates but it looks like too much hassle to modify your website just for one browser that is not really widely used, so I'll give up on that and just update manually via developer mode.

Thanks again.

**Comment by jspenguin2017** [comment]
I won't enable inline install for Nano Defender, it will make review process longer.
