### ISSUE TITLE
Make "Update now" button more accessible

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#17]
every time i wan't actualize the filters i must scroll to down and back up to be click the actualize filters button.. this is a mistake

![2017-12-10 23_10_05-nano panel sterowania](https://user-images.githubusercontent.com/5884000/33810016-8aa9e1a0-ddff-11e7-9716-199c07c06044.png)

![2017-12-10 23_10_16-nano panel sterowania](https://user-images.githubusercontent.com/5884000/33810017-8f1c2e64-ddff-11e7-8cee-6db3034827c3.png)

Nano Adblocker 1.0.0.6
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by jspenguin2017** [comment]
It's not necessarily a "mistake" as uBO doesn't handle it better neither. But yea, I think I should move the button.

**Comment by jspenguin2017** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/7283682/33810365-e60555c8-ddc0-11e7-8310-d3b4ff21dd94.png)

**Comment by mat41997** [comment]
ymm

better not, there is a most probably of accidental clicks

**Comment by jspenguin2017** [comment]
I need to think about this, can be tricky.

**Comment by jspenguin2017** [comment]
Actually, this is a lot harder than it seems, I need to think about this.

**Comment by jspenguin2017** [comment]
Closed in favor of #33

**Comment by jspenguin2017** [comment]
The new dashboard is still quite a long way away... 
I can add a shortcut key, that should be a better solution.
