### ISSUE TITLE
Add button to disable extension on current site

### ISSUE THREAD

**Issue by Su-Well** [NanoAdblocker/NanoCore#171]
After installing Nano Defender, some sites are not loading correctly. This is probably confirmation bias on my part, but as of now there's no easy way to check if Nano Defender is the cause of any issues. Going into `Menu --> More Tools --> Extensions --> Nano Defender --> Disable` is impractical, and personally I end up opening the site in Firefox instead.

Therefore, I propose adding a on/off button similar to what uBlock has. The two main advantages are:
- It will increase the chance of users noticing and reporting bugs
- It will increase usability

Thanks

**Comment by jspenguin2017** [comment]
That's not possible.

**Comment by Piter432** [comment]
@Su-Well: You can use NooBoss or Extension Automation (if it still exists on Chrome Store) or other similar extension to temporarily disable the ND.
