### ISSUE TITLE
Shift key on Android works as backspace

### ISSUE THREAD

**Issue by hawkeye116477** [NanoAdblocker/NanoCore#172]
### Describe the issue (Required)
When I press on shift key on GBoard (Android keyboard) on My filter tab on Nano Adblocker, then it works as backspace, it removes letters.

### Screenshots (Required)
For this screenshot nothing gives, but I uploaded video :smile:.
[shift_movie.zip](https://github.com/NanoAdblocker/NanoCore/files/2062558/shift_movie.zip)

### Screenshot of console (Required, press `F12` to open the console)
I think that for this, it doesn't required.

#### Environment (Required)

- Operating System and Version: Android 7.1.2 (LOS 14.1)
- Browser and Version: Yandex Browser 18.4
- Nano Adblocker Version: 1.0.0.52
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

I think that for this, it doesn't required, because it's issue with Nano Adblocker itself and not with filters :smile:

**Comment by jspenguin2017** [comment]
I can't test on that platform. And it's likely a problem with Ace again.

**Comment by hawkeye116477** [comment]
Yes, cuz it works correctly on uBO. So for now I will just switch to uBO Dev to make same rules if necessary until this will be fixed :smile:.

**Comment by jspenguin2017** [comment]
Only Chromium, Chrome, and Edge are officially supported by me. Issues only affecting other Chromium forks are considered to be browser bugs.
