### ISSUE TITLE
XPI file for Nano Adblocker and Nano Defender

### ISSUE THREAD

**Issue by sevospl** [NanoAdblocker/NanoCore#173]
### Describe the issue (Required)

I'd like to install Nano Adblocker and Nano Defender on Firefox for Android, so I ask you to provide XPI file to install this extension using this method:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android

From "file:///mnt/sdcard" it's possible to click on XPI file and then install extension manually.

#### Environment (Required)

- Operating System and Version:  Android
- Browser and Version: Firefox for Android
- Nano Adblocker Version:  newest one
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
Nano Adblocker no longer support Firefox, you are welcomed to fork. I'm not sure how to create XPI file for Nano Defender, I thought ZIP file would work too.

**Comment by sevospl** [comment]
I just replaced "ZIP" with "XPI" in the name of file, it worked :) uBlock Origin works with Nano Defender well.
