### ISSUE TITLE
Consider migrating to another project platform

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoCore#175]
If you have't heard already Microsoft has just bought Github. If you want to migrate to gitlab then it is quite easy. https://www.youtube.com/watch?v=VYOXuOg9tQI however i would not trust Microsoft to keep the required API accessible forever.

**Comment by elypter** [comment]
so people cannot easily more to gitlab anymore

**Comment by jspenguin2017** [comment]
If I decide to move to GitLab, nothing can stop me. This is not a concern until it becomes a problem.
