### ISSUE TITLE
Does NanoAblocker remove Ublock Origin Tracking code?

### ISSUE THREAD

**Issue by rugabunda** [NanoAdblocker/NanoCore#176]
Ublock origin collects analytics via google analytics and discloses user information to law enforcement agencies https://www.ublock.org/privacy/

I am curious if NanoAdblocker removes these intrusive analytics features, and if not, if you will consider doing this in future releases?

**Comment by gwarser** [comment]
[uBlock Origin is completely unrelated to the web site ublock.org](https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org)

**Comment by rugabunda** [comment]
Awesome! Thank you SO MUCH for the reply! YOU ROCK! AND THANK GOD FOR THAT!

**Comment by rugabunda** [comment]
Perhaps I spoke too soon, Just curious as I notice Adblocker Genesis Plus, which is a fork of ublock origin and adblock plus combined, it states the following quote:

"OPEN SOURCE
This adblocker is a fork of the Adblock Plus and uBlock Origin, a community-driven project with hundreds of volunteers making sure that all ads are automatically blocked. The code is open source and used under GPL. Significant portion of the code was rewritten to make this extension faster, efficient and far more reliable. We also REMOVED any tracking code for your privacy."

https://chrome.google.com/webstore/detail/adblocker-genesis-plus/jacihiikpacjaggdldhcdfjpbibbfjmh

I am curious if you are aware of any kind of tracking code in the ublock extension. Thanks so much!

**Comment by rugabunda** [comment]
Great news! Thank you!
