### ISSUE TITLE
I had to disable russian to english text translation on rutracker.org to use the element picker properly.

### ISSUE THREAD

**Issue by streetsofrage47** [NanoAdblocker/NanoCore#177]
### Describe the issue (Required)
I had to disable russian to english text translation on rutracker.org to use the element picker properly. when it auto-translated, the element picker box would not respond to mouse clicks. and was very glitchy. I am also using nano defender, and 64 bit chrome and operating system.

### URLs where this issue occurs (Required if applicable)
rutracker.org with auto-translated russian to english.

http://rutracker.org/forum/index.php

#### Environment (Required)

- Operating System and Version:  windows 8.1 - 64 bit
- Browser and Version:  chrome 67 - 64 bit
- Nano Adblocker Version: v1.0.0.52
- Nano Defender Version (Optional if you are not using it): V14.44

#### Your custom filters (Required if you have any)
Custom (1/1)
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt​​​​​227 used out of 282​​​​

**Comment by jspenguin2017** [comment]
This is most likely a problem with the translator.

**Comment by jspenguin2017** [comment]
Which translation tool are you using?

**Comment by streetsofrage47** [comment]
just the normal default translation that google chrome does on a page that is not in english.

**Comment by jspenguin2017** [comment]
I'm having technical difficulties with my test setup, I'll test in a few days. 
If there are filter issues concerning that website, you can report them to NanoFilters repository.

**Comment by jspenguin2017** [comment]
I can't reproduce, it is working properly for me: 
![image](https://user-images.githubusercontent.com/7283682/41010347-0e9acc66-68f4-11e8-91a7-e75d25617fd4.png)

**Comment by jspenguin2017** [comment]
I still can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/42729512-da01032c-8797-11e8-9fbb-b3173755d36c.png)

Closing due to lack of response.
