### ISSUE TITLE
Privacy section in Settings is greyed out

### ISSUE THREAD

**Issue by thunderschnozzle** [NanoAdblocker/NanoCore#178]
### Describe the issue (Required)
The title pretty much sums it up. If you open the nano adblocker's dashboard and check the Settings tab you'll see that the Privacy tab is greyed out and therefore cannot be edited by the user

### Screenshots (Required)

![2018-06-09 1](https://user-images.githubusercontent.com/13940284/41198270-560f02ac-6c3b-11e8-8ebe-6f0f0af8a47f.png)

### Screenshot of console (Required, press `F12` to open the console)

![2018-06-09 2](https://user-images.githubusercontent.com/13940284/41198293-122f9b9a-6c3c-11e8-921c-256797085079.png)

#### Environment (Required)

- Operating System and Version: Windows 10 Pro version 1803 Build 17134.48
- Browser and Version: Microsoft Edge version 42.17134.1.0
- Nano Adblocker Version: 0.0.52.0
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

I didn't make any changes to the default settings

**Comment by jspenguin2017** [comment]
If they are greyed out it means your browser does not support them.
