### ISSUE TITLE
add custom profile

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#183]
https://github.com/NanoAdblocker/NanoCore/issues/105
https://github.com/NanoAdblocker/NanoCore/issues/56
https://github.com/gorhill/uBlock/issues/3651

example. custom parameter - profiling

```
!#if index_and_load_this_rule_if_your_custom-global-parameters_is(parameter:"example, profile-popup, profile-name, priority-2, release")
example.rule#example
```

```
!#set-global-parameter profile-popup(only-for-filterlist:"EasyList_Privacy,EasyList")
```

**Comment by KonoromiHimaries** [comment]
the potential benefits are amazing
- you can create packages of profiles and share them
- you can index rules and create better lists that allow you to create better adblocker

**Comment by jspenguin2017** [comment]
There are a few problems:
- Every time those global flags change, the entire build cache needs to be discarded
- You should not have more than 2 or 3 profiles, in which case you should use browser profiles instead
- How does custom `if` flags help index rules?
- Packages would not be implemented like that, it would be one metadata file pointing to many filters that the user can choose
