### ISSUE TITLE
[Breakage] cine.to

### ISSUE THREAD

**Issue by Esokrates** [NanoAdblocker/NanoCore#193]
### Reproduction Steps
1. Go to cine.to
2. Select a movie to watch and select the streaming source
3. Solve captcha if necessary
4. Observe that you are not directed to the video link

Maybe the workaround from issue #166 is to blame?
Disabling Nano Adblocker makes the redirection to the video work. Another thing worth noting is, that the annoying popups described in #166 seem to get caught by chromium itself now.

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/43234032-d93264de-9036-11e8-8428-8fc33c85aa91.png)

**Comment by jspenguin2017** [comment]
Also, for filter issues, send them here next time: 
https://github.com/NanoAdblocker/NanoFilters/issues

**Comment by Esokrates** [comment]
Hmmm. Very strange. Now it works for me too, I have changed nothing though.
Feel free to close, thanks!
