### ISSUE TITLE
how to install nanoAdblocker?

### ISSUE THREAD

**Issue by grysor** [NanoAdblocker/NanoCore#195]
hello i have a pc desktop im noob how to install nanoAdblocker in my web browser firefox please?
I do not understand how to do it, it installs with a file xpi? but there is no xpi file for download ...
I installed the extension "nano defender" in my firefox.But nanoAdblocker is something else?
thank you in advance for your help

**Comment by jspenguin2017** [comment]
There's no official Firefox port.
