### ISSUE TITLE
XPath applied as filters?

### ISSUE THREAD

**Issue by unicorntaco** [NanoAdblocker/NanoCore#196]
### Describe the issue (Required)
I am not versed enough to overcome 'randomized' div names from the picker.  I have installed this XPath extension

https://addons.mozilla.org/en-US/firefox/addon/truepath/

How do I use these results with your adblock extension?  

Yes, I will be using firefox to find the XPath to feed to your chromium extension.  The chromium store extensions seem way too complicated.

### Screenshots (Required)
![todays deals](https://user-images.githubusercontent.com/42160943/43752313-5b9ff7b0-99b5-11e8-877c-7c05309fdf27.png)

![xpath right click](https://user-images.githubusercontent.com/42160943/43752532-4d388a10-99b6-11e8-98ad-948d0ad9b6af.png)

### Screenshot of console (Required, press `F12` to open the console)
![todays deals f12](https://user-images.githubusercontent.com/42160943/43752318-6280c104-99b5-11e8-9d29-e72e7c19a2db.png)

### URLs where this issue occurs (Required if applicable)
https://www.amazon.com

I am logged in.  an amazon account is free.

### Reproduction Steps (Optional if trivial)

install truepath extension
visit page with rando div names
right click on blockable element
releavel xpath

get stuck on next step

#### Environment (Required)

- Operating System and Version:  W10 pro
- Browser and Version: Iridium Version 2018.4 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.60
- Nano Defender Version (Optional if you are not using it): 15.0.0.26

#### Your filter lists (Required)

default

**Comment by jspenguin2017** [comment]
The documentation is here: https://github.com/NanoAdblocker/NanoDoc/blob/master/en/Index.MD
Please make an effort to read it. 

Also, you can get XPath from Chromium console: 
![image](https://user-images.githubusercontent.com/7283682/43752929-89a08ae8-99c0-11e8-9c05-517e3ef7c3c0.png)

**Comment by jspenguin2017** [comment]
That's correct, don't put domain in Picker, it automatically adds the domain of the document it is attached to.
