### ISSUE TITLE
you can add a description to the filters?

### ISSUE THREAD

**Issue by mat41997** [NanoAdblocker/NanoCore#20]
example.
![2017-12-11 02_34_43-nano panel sterowania](https://user-images.githubusercontent.com/5884000/33812305-a0726bfc-de1c-11e7-8839-d9320f75698c.png)

**Comment by jspenguin2017** [comment]
Hum... this can be a bit difficult actually. But yea, I think it's a good idea. 
I need to add an entry to `assets.json` and carry it to the dashboard.

**Comment by mat41997** [comment]
ohh. and must be link to the issues page

**Comment by jspenguin2017** [comment]
I thought you mean a tooltip... 
Currently the "home" button takes you to the issues page. There can also be an information button, like this one: 
![image](https://user-images.githubusercontent.com/7283682/33813402-cec1d272-dde0-11e7-8945-018220e430fd.png)
Can the maintainer host an info page himself (like GitHub Pages)? 

Thinking about it, an description popup might not be that useful...

**Comment by mat41997** [comment]
> Can the maintainer host an info page himself (like GitHub Pages)?

yes, in wiki pages

**Comment by jspenguin2017** [comment]
Hum, that's more of a how-to guide, not quite a "description"...

**Comment by mat41997** [comment]
or that
![33812305-a0726bfc-de1c-11e7-8839-d9320f75698c 1](https://user-images.githubusercontent.com/5884000/33813891-09263c50-de27-11e7-9155-bee5f4fb0e7b.png)

**Comment by jspenguin2017** [comment]
Actually, I'll refuse this proposal, I don't see much value in adding a complex description page in dashboard, if required, the maintainer can host an info page where I can link from the dashboard.
