### ISSUE TITLE
Umatrix depreciates & Forces unsafe TLS Ciphers in Firefox, Chrome, and Waterfox according to SSLlabs tests

### ISSUE THREAD

**Issue by rugabunda** [NanoAdblocker/NanoCore#207]
Sorry for the semi/OT but Nano Adblocker and Ublock origin are tied at the hip with umatrix, and they will not allow me to mention this flaw on their github pages, so I thougt I would bring it to your attention here in hopes someone can fork this thing.

here is the issue
https://github.com/uBlockOrigin/uMatrix-issues/issues/52
if that disappears, here is another
https://www.wilderssecurity.com/threads/umatrix-the-http-switchboard-successor.369601/page-29#post-2781062

**Comment by rugabunda** [comment]
Prerequisites
[check] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
Your issue may already be reported.
[check] This is not a support issue or a question
Support issues and questions are handled at /r/uMatrix
I tried to reproduce the issue when...
[check] uMatrix is the only extension
[check] uMatrix with default lists/settings
[check] using a new, unmodified browser profile
[check] I am running the latest version of uMatrix
[check] I checked the documentation to understand that the issue I report is not a normal behavior
Description
Umatrix enables disabled, and depreciated ciphers; potentially a massive security problem. Around the same time I've also experienced tonnes of ERR_SSL_VERSION_INTERFERENCE errors, 5 out of 10 TLS connections fail.

Steps to Reproduce
1. Set Chrome and Firefox to use Tls1.2-Tls1.3 strictly!
2. Simply Enable Umatrix
3. goto https://www.ssllabs.com/ssltest/viewMyClient.html and see the depreciated ciphers detected
4. Disable Umatrix & Try again. Note browser reports correctly safe and secure browser specified ciphers.
Forced entries includie ssl3, Tls1.0, Tls1.1.

Looks like a devistating security flaw! BE CAREFUL with your online banking PEOPLE!

Supporting evidence
Umatrix Enabled: https://image.ibb.co/ide4fU/Umatrix_Enabled.png
Umatrix Disabled: https://image.ibb.co/hWhPfU/Umatrix_Disabled.png

Your environment
uMatrix version: Latest 1.3.14
Browser Name and version: Latest Firefox / Waterfox / Chromium, same issue in all.
Operating System and version: Windows 7

**Comment by rugabunda** [comment]
Video evidence: https://vimeo.com/289712821

**Comment by rugabunda** [comment]
The guy goes on about whitelisting cloudflare scripts, whatever that means. I have disabled every hosts file every option in umatrix, it makes zero difference.

**Comment by jspenguin2017** [comment]
I have no plan in forking uMatrix.

**Comment by rugabunda** [comment]
Ok i see, had to whitelist it, they were right for once, nice! my mistake!
