### ISSUE TITLE
Element Picker & Zapper don't always load when clicking them

### ISSUE THREAD

**Issue by rugabunda** [NanoAdblocker/NanoCore#210]
### Describe the issue (Required)
Element picker and zapper fail to initiate when clicked.

### Screenshots (Required)

Video: https://vimeo.com/289953494

### Screenshot of console (Required, press `F12` to open the console)

https://image.ibb.co/iT82LU/test.png

### URLs where this issue occurs (Required if applicable)
any

### Anything else you believe to be useful (Optional)
This has been happening on and off for months and months.

#### Environment (Required)

- Operating System and Version:  Windows 7 SP1 64
- Browser and Version: Chromium Version 69.0.3497.92 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.66
- Nano Defender Version: 15.0.0.45

#### Your filter lists (Required)
 "plowe-0",
    "fanboy-annoyance",
    "malware-1",
    "malware-0",
    "disconnect-malvertising",
    "fanboy-enhanced",
    "easyprivacy",
    "adguard-spyware",
    "easylist",
    "adguard-generic",
    "awrl-0",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-filters",
    "nano-whitelist",
    "nano-filters",
    "nano-defender",
    "user-filters"

#### Your custom filters (Required if you have any)

wish i could

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/45575067-6d358d80-b82f-11e8-9d7b-9024baef663b.png)

Disable your other extensions one by one and see which one is causing problem.

**Comment by rugabunda** [comment]
I have, doesn't make a difference.

**Comment by rugabunda** [comment]
Restarting nano, and the browser doesn't cut it.

**Comment by rugabunda** [comment]
I also had this time with ublock as well

**Comment by rugabunda** [comment]
just finished updating chrome and starting a fresh profile also.

**Comment by jspenguin2017** [comment]
Where did you get your browser?

**Comment by jspenguin2017** [comment]
Is it a custom build?

**Comment by rugabunda** [comment]
the top of: https://chromium.woolyss.com/ here is my capture network log chrome-net-export-log.json  https://www.file-upload.com/d9un0xhfw8gs

**Comment by jspenguin2017** [comment]
Are you sure those builds are any good? 
As far as I tested, it works perfectly fine on Google Chrome on Windows and Ubuntu, and Chromium on Ubuntu.

**Comment by rugabunda** [comment]
reinstalling nano fixed the issue.

**Comment by jspenguin2017** [comment]
OK, closing then. You must have something that corrupted the files.
