### ISSUE TITLE
[Breakage] facebook.com

### ISSUE THREAD

**Issue by Daniel-USA** [NanoAdblocker/NanoCore#212]
follow whitehouse.gov on facebook.
turn on nanoblocker
all whitehouse.gov posts now get removed

Why? How do I stop this.

**Comment by Daniel-USA** [comment]
the information in that panel is indecipherable. I'm just going to switch back to UblockOrigin since they don't block the posts from the President and his staff. Someone that does filters for y'all, obviously has an issue with American politics and thought it would be wise to add them into a filter.

**Comment by jspenguin2017** [comment]
@Daniel-USA Once the out-of-the-box filters get updated, uBO will do the same: 
![image](https://user-images.githubusercontent.com/7283682/45881402-48c63d80-bd68-11e8-852e-bac121d10cd1.png)

@okiehsch 
It seems some legit links in Facebook has a tracking parameter: 
![image](https://user-images.githubusercontent.com/7283682/45881292-fbe26700-bd67-11e8-84d7-98929d149ac0.png)

Fix (or remove the bad rule): 
```
facebook.com#@#div[id^="hyperfeed_story_id_"]:has(a[href*="utm_campaign"])
```

**Comment by jspenguin2017** [comment]
@Daniel-USA Once the out-of-the-box filters get updated, uBO will do the same. If you don't want to be productive, you're not welcomed here.

**Comment by mapx-** [comment]
the same filter is in easylist too
`facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href*="utm_campaign"])`

so maybe we can remove the uBo filter but add the exception too

**Comment by jspenguin2017** [comment]
@mapx- OK, sounds good. Also FYI @ryanbr

**Comment by Daniel-USA** [comment]
Productive? I have no idea what any of this jargon means. I am just a user. I gave you my information. I can not help you any further. It is not my fault your filters discriminate a political group. At least I posted about it to raise awareness.

**Comment by jspenguin2017** [comment]
@Daniel-USA If there is a problem, report it and that's it. If you can't help finding the bad rule, just say you don't know what to do. Don't bring politics into this. If you choose to continue to bring politics into my repositories, you will be banned.
