### ISSUE TITLE
checkboxes vanish zoom level chromium

### ISSUE THREAD

**Issue by trevuchet** [NanoAdblocker/NanoCore#217]
### Describe the issue (Required)

"zoom" level 100% checkboxes for filter lists vanish if checked.  Visible if unchecked.  Reveal at 90% or less, or 110% or more.

### Screenshots (Required)

![1 at zoom 110 pct](https://user-images.githubusercontent.com/43896890/46565241-3dbff100-c8c2-11e8-8454-db4d9f21d5f0.png)

![2 100 pct](https://user-images.githubusercontent.com/43896890/46565242-3dbff100-c8c2-11e8-9ea7-fad319b81c23.png)

### Screenshot of console (Required, press `F12` to open the console)

how do I actuate F12 on this 27" inch iMac?  both command and control modifiers do nothing to impede volume increase.option f12 opens a system widget.  fn f12 does nothing.  

burger, developer tools, console?

![3 console](https://user-images.githubusercontent.com/43896890/46565243-3dbff100-c8c2-11e8-80b2-a495e18586ef.png)

### URLs where this issue occurs (Required if applicable)

n/a

#### Environment (Required)

- Operating System and Version: macos mojave
- Browser and Version: ungoogled chromium 68.0.3440.106-1
- Nano Adblocker Version: 1.0.0.69
- Nano Defender Version (Optional if you are not using it): 15.0.0.51

#### Your filter lists (Required)

Is screenshot the least painful way to provide this?

![screen shot 2018-10-05 at 5 17 49 pm](https://user-images.githubusercontent.com/43896890/46565304-ac9d4a00-c8c2-11e8-83e9-d6863daf1303.png)

#### Your custom filters (Required if you have any)

someday I'll be savvy

**Comment by jspenguin2017** [comment]
Can't reproduce with official Chrome / Chromium build. Report to your browser maintainer. 
![image](https://user-images.githubusercontent.com/7283682/46565744-56370800-c8d0-11e8-81a7-ac7a1de7f09c.png)
