### ISSUE TITLE
you can implement a error loging?

### ISSUE THREAD

**Issue by mat41997** [NanoAdblocker/NanoCore#22]
because, i have crash
![2017-12-11 04_27_38-nano panel sterowania](https://user-images.githubusercontent.com/5884000/33814635-d9af1c58-de2b-11e7-93ad-b3673a1004b9.png)

to reproduct
+ i dont't know
+ i try update my filters
`https://raw.githubusercontent.com/mat41997/polish-ads-filter/patch-8/inside-filters/adblock_wewnetrzne.txt`
+ and crash has close my nano adblocker

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.7
Nano Defender 13.0
Chrome 63.0.3239.84
Win10

i don't know how do i can give more information

**Comment by jspenguin2017** [comment]
I won't be able to do any logging if Chrome process dies, that is beyond control of JavaScript. 
A tab can only crash if: 
- Chrome is bugged
- You ran out of RAM (this can be caused by JS)

I didn't change anything of third party filter page yet, I don't see how can it crash.

**Comment by mat41997** [comment]
i have the latest stable chrome
i have 16gb ram

**Comment by jspenguin2017** [comment]
Latest stable doesn't mean it can't be bugged, does it happen consistently or that's the only time?

**Comment by mat41997** [comment]
only this time

**Comment by jspenguin2017** [comment]
Chrome crash is beyond my control.
