### ISSUE TITLE
RawGit is shutting down

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#220]
RawGit will stop working in about a year. Got to update those URLs... 

cc @gorhill

**Comment by jspenguin2017** [comment]
cc @collinbarrett of `filterlists.com`
cc @farrokhi of `IRN: Adblock-Iran`

**Comment by farrokhi** [comment]
Are you aware of (or have any recommendation on) any replacement service? Unfortunately access to `raw.githubusercontent.com` is not possible from certain countries, this was why we used RawGit.

**Comment by gwarser** [comment]
https://rawgit.com/ proposes some replacements.

**Comment by jspenguin2017** [comment]
I'm looking at GitCDN, but we might want to ask the owner first.

**Comment by jspenguin2017** [comment]
Note that jsDelivr and UNPKG *will* work for delivering filter lists, just we might want to ask them first, because obviously they are designed to delivery JavaScript libraries, not filter lists.

**Comment by jspenguin2017** [comment]
@DandelionSprout 

- Dropbox - Let's not
- AWS - You'll have better luck with your wallet with OVH or Scaleway, they offer unlimited bandwidth
- 000webhost - It's too slow, I tried to host a website with it, and oh boy it's trash; it might be OK for a small filter that only a few people use, but 20+ mil users of uBO will be too much for it

**Comment by jspenguin2017** [comment]
Gorhill was worried that GitHub/GitLab may ask us to host filters elsewhere. So we want to have a plan B in case things go wrong. 

The raw file access feature of GitHub/GitLab is not really designed to be CDN, so we want to use a real CDN to minimize the chance that we'll have to move on short notice.

**Comment by collinbarrett** [comment]
Even setting using GitHub as a CDN aside, with the recent [CHEF-KOCH debacle](https://github.com/collinbarrett/FilterLists/issues/584#issuecomment-430613675), list maintainers hosting on GitHub should unfortunately be a bit concerned...

**Comment by farrokhi** [comment]
GitCDN seems to be a hassle-free replacement of RawGit for now. I just opened a PR on the main uBlock repo: https://github.com/gorhill/uBlock/pull/3738

**Comment by jspenguin2017** [comment]
@collinbarrett Eh... Got to put [this](https://github.com/NanoAdblocker/NanoCore/issues/218) on the priority list.

**Comment by mikhoul** [comment]
**jsdeliver** accept **any kind of files** (Including filters), they have even made a landing page to welcome Rawgit Users.

https://www.jsdelivr.com/rawgit

Regards :octocat:

**Comment by jspenguin2017** [comment]
@DandelionSprout I have backups and mirrors of all default assets, and the full commit history of uAssets. 

I think the biggest problem is to create an up-to-date copy of issues. It's not that hard to dump existing issues, but it's a bit difficult to keep the dump to up date.

**Comment by DandelionSprout** [comment]
I also propose the unilateral keeping of backups of others' filter lists, be it without or without outright permission from a list's owner, especially for those lists that have reasonably open-sourced licences. Randomly-picked examples of Git-based lists that currently have no backups listed in the Assets lists, include *hufilter*, *EasyList Hebrew*, *Frellwit's Swedish Filter*, and *EasyList Italy*, among dozens of others.

Conversely (or even additionally), some popular lists that are hosted on limited-userbase sites, can have already-existing Git mirrors added for them. *MVPS Hosts* comes to mind, for which a perfectly good (as far as I can tell) mirror exists at https://raw.githubusercontent.com/StevenBlack/hosts/master/data/mvps.org/hosts.

An additional side effect of doing this, is that with ≥1 mirror for each list, if not even ≥2, then most cases of end-users having problems with updating their lists would disappear almost overnight. If I interpret farrokhi correctly, then a lot of lists that currently are only hosted on raw.githubusercontent.com, cannot be accessed in e.g. Iran; which means that by adding various mirrors for those lists, then they can be accessed and updated by users in pretty much every country on Earth.

**Comment by DandelionSprout** [comment]
If it's needed, and if the idea doesn't sound repulsive to you guys (e.g. jspenguin2017 and @gorhill), then I myself could easily set up mirrors for various lists on Repo.or.cz and/or GitCDN fairly soon (Possibly even tonight), which could then be added to the assets.json files.

**Comment by jspenguin2017** [comment]
I have the code ready to mirror any filter, but the current repository structure design is kind of bad... https://github.com/NanoMeow/MDLMirror

Ideally we want to pull all filters into a central repository that is not on GitHub. We don't want one point of failure.

**Comment by mikhoul** [comment]
BTW I've modified an old userscript that added a button to Github to have a direct link to "Rawgit" now it work again but use GitCDN.   https://greasyfork.org/en/scripts/373361-github-gitcdn-button


![image](https://user-images.githubusercontent.com/5678673/47115612-16a3e080-d22d-11e8-910b-03d8c30ad951.png)

**Comment by DandelionSprout** [comment]
Testing that script out a bit, I'm impressed that it also accounts for `!#include` tags, as far as I can tell. This isn't a critical thing for me personally, but for people who e.g. can access `github.com` but not `raw.githubusercontent.com` (e.g. Iranians, and Westeners on some school networks), that button could mean the world for them.

**Comment by jspenguin2017** [comment]
https://github.com/gorhill/uBlock/pull/3739

**Comment by DandelionSprout** [comment]
>When GitHub removes an user, I don't think those CDNs will keep serving the content for long.

I have now done a bit of additional testing of Repo.or.cz, and am very glad to be able to say that their mirrors do *not* get deleted when the GitHub source repo is. I've been able to confirm this by making https://repo.or.cz/RepoOrCz-deletion-test-repo.git, whose source repo link was deleted soon after the mirror was created. Since Repo.or.cz updates its mirrors every 60~90min, this means that it doesn't try to delete mirrors that it detects as having dead source links. Moreover, there's an option for repo owners (i.e. those who know editing password) to change the source repo link, in case a list's main repo is simply moved.

And to demonstrate the ease of making mirrors there, I've set up https://repo.or.cz/Adblock-list-backups-Frellwits-filter-lists.git, whose raw version of the SWE list at https://repo.or.cz/Adblock-list-backups-Frellwits-filter-lists.git/blob_plain/refs/heads/master:/Frellwits-Swedish-Filter.txt seems to work perfectly well for me.

Note 1: Repo.or.cz does not have a user system for mirror repos that I'm aware of. Instead, editing privileges are based on per-repo passwords. I've set up the SWE repo mirror above with a 45-character password that includes non-ASCII characters (A scenario that I think that very few password cracker tools have been set up for), but am not sure how I'd go about with sharing the passwords of this and of future mirrors with relevant people (e.g. you, gorhill, the lists' original owners, etc.) in a sufficiently secretive way.

Note 2: Repo.or.cz mirrors are not updated instantly, and may therefore be very slightly behind GitHub and GitCDN on the newest file updates. Additionally, their About page says that their server rack isn't a particularly powerful one. As such, I'd list repo.or.cz links below GitHub and GitCDN links in assets.json files.

**Comment by DandelionSprout** [comment]
While doing research on a pull for the assets.json files (Presumably that of uBO), I stumbled across https://notabug.org, as it was being used by the LVT list, and which **also** allows for hassle-free and free-of-cost mirroring. Suddenly I feel that we've got a lot of good options on our table now.

**Comment by Snapy** [comment]
I'm surprised `raw.githack.com` hasn't been mentioned. Quoting their website
> The idea of this service is inspired from rawgit.com (formerly rawgithub.com). I just realized that using a whole framework (node.js with express.js) for such simple thing as requests proxying is overkilling, and made same stuff using nginx only. 
RawGit supports only GitHub while raw.githack.com supports Bitbucket and GitLab as well. 

Also you should know that GitCDN also has a `gitcdn.link` domain.

**Comment by jspenguin2017** [comment]
- [ ] Update `assets.json` to add links to GitCDN when possible
- [ ] Update ND installation guide
- [ ] Add announcement on ND home page

**Comment by jspenguin2017** [comment]
@Snapy I don't think we can easily serve latest version with `githack`. They cache the files for way too long.

**Comment by jspenguin2017** [comment]
We can also use jsDelivr and UNPKG. We do want to have as many mirrors as possible. 

We do need to mirror those filters that are not on GitHub onto GitHub first. Anyone want to do it or should I do it? 

---

I've been looking into how to mirror GitHub issues, and it seems that we'll need WebHook to keep the mirror up to date...

**Comment by DandelionSprout** [comment]
https://github.com/StevenBlack/hosts/tree/master/data has mirrors of MVPS, Dan Pollock, and Peter Lowe's List.

It's unfortunately way beyond my skills to figure out how to use GitHub as a mirror host for all the rest of the non-GitHub lists.

**Comment by DandelionSprout** [comment]
>We can also use jsDelivr and UNPKG. We do want to have as many mirrors as possible.

That's also great, although I haven't looked into those sites just yet.

**Comment by jspenguin2017** [comment]
@DandelionSprout 
I'll be like this one: https://github.com/NanoMeow/MDLMirror
Except that it'll be one repository for all filters.

**Comment by DandelionSprout** [comment]
In comparison, NotABug mirrors can be set to sync as often as every hour (The default is 8 hours), and Repo.or.cz syncs every ca. 75min. As such, users that have connection issues with the source link *and* who need the newest version of a list, could be mildly inconvenienced by having 24~48hr old versions of frequently updated lists.

**Comment by KonoromiHimaries** [comment]
https://raw.githack.com/ he look good

**Comment by DandelionSprout** [comment]
Jspenguin seems to have written off Githack as an option for now, at least for GitHub lists.

Taking a quick look through Peerpad, I can't find any ways to view documents on it in raw mode, which is kind-of a make-or-break if they're meant to be subscribable by adblockers. It also doesn't seem to allow easy file mirroring, which rules out having me use it for my lists, at least.

**Comment by KonoromiHimaries** [comment]
> Taking a quick look through Peerpad, I can't find any ways to view documents on it in raw mode, which is kind-of a make-or-break if they're meant to be subscribable by adblockers. It also doesn't seem to allow easy file mirroring, which rules out having me use it for my lists, at least.

you can report this sugestion here https://github.com/ipfs-shipyard/peer-pad/issues

**Comment by DandelionSprout** [comment]
I have my eyes set on NotABug and (to an increasingly smaller degree) Repo.or.cz, but if we were to need *even more* places to back up lists in a subscribable format, then I'll make sure to report it there. 👍

**Comment by neoascetic** [comment]
@jspenguin2017 [rawgithack](https://github.com/neoascetic/rawgithack) now correctly caches `master` branch for 5 minutes, even for CDN URLs.

**Comment by jspenguin2017** [comment]
@neoascetic Oh, that's great! Thanks!

**Comment by jspenguin2017** [comment]
Alright, I got time to test all of them out, here's the summary: 

GitLab CE: Written in Ruby, so that goes out of the window. 
RhodeCode CE: Written in Python, straight into the recycle bin. 

GitBucket: Scala on Java VM, uses quite a bit of memory (300MB+ idle). Easy reverse proxy configuration. Two sets of labels for issues (normal labels and priority labels). 
![image](https://user-images.githubusercontent.com/7283682/47598739-e4e1f680-d95d-11e8-8d2f-49c27e95f9a5.png)

*Edit in progress...*

**Comment by jspenguin2017** [comment]
**GitBucket**: Scala on Java VM, uses quite a bit of memory (300MB+ idle). Easy reverse proxy configuration. Two sets of labels for issues (normal labels and priority labels). 

<details>

![image](https://user-images.githubusercontent.com/7283682/47598739-e4e1f680-d95d-11e8-8d2f-49c27e95f9a5.png)
![image](https://user-images.githubusercontent.com/7283682/47598744-0fcc4a80-d95e-11e8-9932-11db35774138.png)
![image](https://user-images.githubusercontent.com/7283682/47598754-34c0bd80-d95e-11e8-9785-6f96daa754d6.png)
![image](https://user-images.githubusercontent.com/7283682/47598755-3b4f3500-d95e-11e8-88db-9c5c6104d8fd.png)

</details>

**Comment by jspenguin2017** [comment]
**Gogs**: Written in Go, Gogs is blazing fast while using little memory (50MB idle). Even with the SQLite embedded database, it is *significantly* faster than GitBucket. 

It is, however, not mobile friendly. And lot of configuration need to be changed using the configuration file. 

<details>

![image](https://user-images.githubusercontent.com/7283682/47598819-27580300-d95f-11e8-97ea-5949bb6b4ebb.png)
![image](https://user-images.githubusercontent.com/7283682/47598840-7a31ba80-d95f-11e8-9d01-6aac11ce9133.png)
![image](https://user-images.githubusercontent.com/7283682/47598850-887fd680-d95f-11e8-9972-fa74522ba098.png)

</details>

**Comment by jspenguin2017** [comment]
**Gitea**: A fork of Gogs, also in Go. Uses a little bit more resources, but has more features. 

Pretty mobile friendly, although some places looks a bit weird in mobile mode. Like Gogs, a lot of configuration need to be changed using the configuration file. 

<details>

![image](https://user-images.githubusercontent.com/7283682/47598880-15c32b00-d960-11e8-960c-628a08e24c1e.png)
![image](https://user-images.githubusercontent.com/7283682/47598920-d5b07800-d960-11e8-8e56-6015300e0e90.png)
![image](https://user-images.githubusercontent.com/7283682/47598906-a994f700-d960-11e8-8641-92ed29ae6557.png)
![image](https://user-images.githubusercontent.com/7283682/47598927-e103a380-d960-11e8-9a6e-4bdcd57601a8.png)
![image](https://user-images.githubusercontent.com/7283682/47598932-f678cd80-d960-11e8-8bad-7be774442270.png)

</details>

**Comment by jspenguin2017** [comment]
Overall, I think **Gitea** is the best. The extra features it has are pretty useful.

**Comment by jspenguin2017** [comment]
It appears that Gitea's mirror feature doesn't copy issues... That's unfortunate... I still need to think about how to backup the issues. 

Is there anything else to do beside mirroring all resources in `assets.json`?

**Comment by jspenguin2017** [comment]
Is there anything else to do beside mirroring all resources in `assets.json`?

**Comment by jspenguin2017** [comment]
Alright. I'm closing this then. 

I moved progress tracking for mirroring all resources to another issue: https://github.com/NanoAdblocker/NanoCore/issues/225
