### ISSUE TITLE
add some option for support dynamic change of the filter list url address

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#221]
### Describe the issue (Required)

every time I use peerpad, I have to subscribe to the filter list again
https://ipfs.io/ipns/peerpad.net/#

the idea is to use the rss lists or anything else to control the distribution of filter lists
https://github.com/NanoAdblocker/NanoCore/issues/84#issuecomment-368913749
https://github.com/gorhill/uBlock/issues/3678

potential benefits
- change the development channel of the filter list
- support snapshot and time line option
- support decentralize filters and more..

**Comment by jspenguin2017** [comment]
Just have the "rss channel" be a 301 server, and it already works. Let's not overcomplicate things.
