### ISSUE TITLE
I have the following questions to ask:

### ISSUE THREAD

**Issue by Axaf** [NanoAdblocker/NanoCore#222]
1. I went from uBlock Origin to Nano Adblocker and I wanted to ask you, if I have to follow the following guide here too: https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin
2. Can both Nano Adblocker and Nano Defender be used?

**Comment by jspenguin2017** [comment]
1. No, it's pre-configured. Specifically, ND will emit an event to update configuration of Nano. 
2. Yes. You are supposed to use both.
