### ISSUE TITLE
Any and all websites broken, even new tabs

### ISSUE THREAD

**Issue by bionor** [NanoAdblocker/NanoCore#224]
### Describe the issue (Required)

Any new tab or site is immediately blocked by uBlock origin because of filters by nano defender

### Screenshots (Required)
![screenshot from 2018-10-27 12-29-47](https://user-images.githubusercontent.com/44522860/47602810-11d8ec80-d9e4-11e8-94ba-7e32ce3dfa33.png)
![screenshot from 2018-10-27 12-31-06](https://user-images.githubusercontent.com/44522860/47602828-31701500-d9e4-11e8-95e6-ebec8fcebf2c.png)

### Reproduction Steps (Optional if trivial)

Try opening anything at all and uBlock will block it. Everything worked fine for a long time, suddenly yesterday, nothing works. There may have been an update to the browser (Ubuntu 16.04)

#### Environment (Required)

- Operating System and Version: Ubuntu 16.04
- Browser and Version: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it): 15.0.0.66

**Comment by jspenguin2017** [comment]
I'm releasing the domain, you must update your subscription. Read the announcement for a guide.

**Comment by jspenguin2017** [comment]
There is an explanation inside the filter list.
