### ISSUE TITLE
[feature request] Bring Back Firefox Builds

### ISSUE THREAD

**Issue by mikeloeven** [NanoAdblocker/NanoCore#226]
Just went to update nano ad block only to find there are no longer Firefox builds. Some research revealed that FF support was dropped following addition of Edge EDGE !!! support. Aside from the fact that EDGE IS CANCER!!!. The least useful. least feature rich. sorry excuse for a toy browser designed for mobile devices Edge support should never have been prioritized over Firefox. You should be ashamed of yourself for dropping FF builds in favor of microsoft's abortion of a web browser and bring back FF builds ASAP there very few up to date ad block systems still being maintained for FF and the loss of updates for nano ad-block is catastrophic for the FF community

**Comment by gwarser** [comment]
https://github.com/LiCybora/NanoDefenderFirefox#about-firefox-port

**Comment by jspenguin2017** [comment]
I only have time to maintain builds for 2 browsers, and I chose Chrome and Edge. If you are unhappy about my decision, the fork button is there.

**Comment by mailinglists35** [comment]
now that edge will become basically chrome inside, I hope you find time to revive the firefox release
