### ISSUE TITLE
Problem with gui in opera

### ISSUE THREAD

**Issue by szarekpl** [NanoAdblocker/NanoCore#230]
### Describe the issue (Required)

I installed a nano adblocker and nano defender in the opera (windows). In the latest version of adblocker (this error did not appear before) gui is not displayed correctly.

### Screenshots (Required)

![1](https://user-images.githubusercontent.com/45143552/48672660-04250b80-eb39-11e8-8638-664bfa69a0c2.png)
![main preferences](https://user-images.githubusercontent.com/45143552/48672661-04250b80-eb39-11e8-8248-4db05bdd803b.png)

### Screenshot of console (Required, press `F12` to open the console)

![console](https://user-images.githubusercontent.com/45143552/48672709-93322380-eb39-11e8-8935-759e8ce0753e.png)
 

#### Environment (Required)

- Operating System and Version: windows 7
- Browser and Version: opera 56.0.3051.99
- Nano Adblocker Version: 1.0.0.77
- Nano Defender Version (Optional if you are not using it):  15.0.0.73

**Comment by jspenguin2017** [comment]
It looks like some files are corrupted. Try reinstalling.

**Comment by szarekpl** [comment]
Reinstallation has helped.
