### ISSUE TITLE
How does one make a list become privileged?

### ISSUE THREAD

**Issue by DandelionSprout** [NanoAdblocker/NanoCore#231]
I'm trying to get [this list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sandbox/I%20Don't%20Care%20About%20Cookies%20-%20Nano%20Adblocker%20expansion%20list.txt) to become a privileged list. As it's constructed out of some entries that are currently exclusive to the browser extension version of I Don't Care About Cookies, it uses `nanop-easy-set-cookie.js` extensively, but the entries currently aren't loaded from the list when I import the list into Nano Adblocker.

As such, how do I make a list become privileged in Nano? Bonus points if the list maker can make it privileged for all users of it, as opposed to having it be done on the client-side.

**Comment by jspenguin2017** [comment]
The author of the list need to apply for it by opening an issue here. 

To test it locally, you can make user filters privileged: https://github.com/NanoAdblocker/NanoDoc/blob/master/en/AdvancedSettings.MD#nanomakeuserfiltersprivileged-switch

**Comment by jspenguin2017** [comment]
Make sure to test your rules though, extensions are still way more powerful than a privileged script snippet.

**Comment by DandelionSprout** [comment]
While I am the author of that list, I did originally intend for IDCAC's creator (who my PayPal donation archive tells me is named Daniel Kladnik) to take over the ownership of that list or of a similar one, and to incorporate it into his main list somehow.

So I figured that for all parties involved, I thought it'd be easier for both me and him to create and test various sandbox lists if there was a way to make them privileged, that didn't depend on applications and Nano updates.

Given that he does indeed have an extension that he maintains and prefers over his adblocker list, I'd be surprised if he'd want to deal all that much with extra lists and applications and such, especially if it takes a little extra bit of effort to do so.

I did succeed in setting `nanoMakeUserFiltersPrivileged` to `true`, but sadly that only applies to the "My filters" section.

I suppose that now that you have explained the official method for making a list privileged (By requesting you about it), that this issue can be closed, but I now think it'd be nice to give that a mention in https://github.com/NanoAdblocker/NanoDoc/blob/master/en/AdvancedSettings.MD#nanomakeuserfiltersprivileged-switch, for information's sake. 🙂

**Comment by jspenguin2017** [comment]
I have to review each privileged filters, even if I don't hard code the whitelist, I'll probably still be the only one who can change it. 

I will add it to the doc.

**Comment by jspenguin2017** [comment]
As a side note, the whitelist is currently hard coded here: https://github.com/NanoAdblocker/NanoCore2/blob/master/src/js/nano-background.js

**Comment by jspenguin2017** [comment]
It's pretty easy to implement so why not...

`nanoMakeThirdPartyFiltersPrivileged` is now available starting v1.0.0.79b1.
