### ISSUE TITLE
new polish anti-adblock list

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#232]
### Describe the issue (Required)
<https://www.certyficate.it/polskie-filtry-anti-adblock-brak-wsparcia-w-polskich-filtrach-szanowni-nasi-drodzy-od-07-12-2018-nastapia-zmiany-w-oficjalnych-polskich-filtrach/>

<https://github.com/MajkiIT/polish-ads-filter/commit/5d223956a55f7fa143903a0bc4a29405a933b8bb>

moved to

<https://github.com/olegwukr/polish-privacy-filters/blob/master/anti-adblock.txt>

**Comment by jspenguin2017** [comment]
@gorhill

**Comment by jspenguin2017** [comment]
@okiehsch
