### ISSUE TITLE
NanoAdblocker is preventing some page to load entirely.

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoCore#234]
### Describe the issue (Required)
Some site doesn't load at all because of NanoAdblocker.

### Screenshots (Required)

https://imgur.com/a/eOqP0ua

### Screenshot of the console (Required, press `F12` to open the console)

https://imgur.com/a/7Ho6Qtb

### URLs where this issue occurs (Required if applicable)
torrentz2.eu    I guess? there could be more tho.

### Reproduction Steps (Optional if trivial)

Well, just go to torrentz2.eu then search a random (actual) thing then click on any of the results It'll show a blank page.

### Anything else you believe to be useful (Optional)

Disabling NanoAdblocker makes everything work again (but it brings back the ads of course).

#### Environment (Required)

- Operating System and Version: Windows 10 enterprise 1803
- Browser and Version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.83
- Nano Defender Version (Optional if you are not using it): 15.0.0.81

#### Your filter lists (Required)

! 11/27/2018, 2:39:42 AM http://www.spaste.com/p/?c=H5C2vB0279
www.spaste.com##[href^="https://www.mrskin.com/tour"] > font

! 11/27/2018, 2:39:50 AM http://www.spaste.com/p/?c=H5C2vB0279
www.spaste.com###template-contactform-message > h5

! 11/27/2018, 2:40:02 AM http://www.spaste.com/p/?c=H5C2vB0279
www.spaste.com##[href="javascript:showhide('deals')"] > font

! 11/27/2018, 2:40:11 AM http://www.spaste.com/p/?c=H5C2vB0279
www.spaste.com##b

! 11/27/2018, 2:40:20 AM http://www.spaste.com/p/?c=H5C2vB0279
www.spaste.com###deals > h5

! 11/27/2018, 2:45:54 AM https://torrentz2.eu/search?f=Windows+10+Pro+X64+RS4+incl+Office+2016+en-US+AUG+2018+%7BGen2%7D
torrentz2.eu##.HalfRRRAcceptableAd > h3

! 11/27/2018, 2:46:10 AM https://torrentz2.eu/search?f=Windows+10+Pro+X64+RS4+incl+Office+2016+en-US+AUG+2018+%7BGen2%7D
torrentz2.eu##.HalfRRRAcceptableAd > dl:nth-of-type(1)

! 11/27/2018, 2:46:31 AM https://torrentz2.eu/search?f=Windows+10+Pro+X64+RS4+incl+Office+2016+en-US+AUG+2018+%7BGen2%7D
torrentz2.eu##dl:nth-of-type(2)

! 11/27/2018, 2:46:40 AM https://torrentz2.eu/search?f=Windows+10+Pro+X64+RS4+incl+Office+2016+en-US+AUG+2018+%7BGen2%7D
torrentz2.eu##.sl

! 12/14/2018, 1:05:52 AM https://zooqle.com/young-justice-2010-season-1-s01-1080p-bdrip-x265-hevc-10bit-aac-wi180.html#mediainfo
zooqle.com##[href^="https://resentalinterms.info/simani"]

! 12/16/2018, 10:33:30 PM https://www.file-upload.com/jv6rwac4iy0h
||www.file-upload.com/down1.png$image

**Comment by mapx-** [comment]
remove all your personal filters for `torrentz2` then test again

**Comment by jspenguin2017** [comment]
Can't reproduce, you changed some configuration that broke it, try factory reset. 
![image](https://user-images.githubusercontent.com/7283682/50223117-85013e00-0357-11e9-9901-5a7dc715c5f1.png)

**Comment by Cyberavater** [comment]
Reinstalled the NanoAdblocker still the same issue N yes I also tried removing my personal filters.

**Comment by Cyberavater** [comment]
I did the factory reset from the settings still no luck.

**Comment by mapx-** [comment]
Are you using some other blocking extension ?

**Comment by Cyberavater** [comment]
Yeah, Many Userscripts from Tempermonkey. But, I also tested turning it off still no luck.

**Comment by jspenguin2017** [comment]
Can't reproduce, I need a specific test link.

**Comment by Cyberavater** [comment]
I see... Well, I just blocked it in torrentz2.eu for now. Maybe some solution can be found later.

**Comment by Cyberavater** [comment]
Reinstalling Chrome solved the problem.

**Comment by Cyberavater** [comment]
I see, well it would've been nice if I could use both but I think I'll just have to make do.

**Comment by gwarser** [comment]
Grammarly sets new class `<html lang="en" class="gr__torrentz2_eu">`

and uBO filters has this:

> Static filter `torrentz2.*##[class]:has-text(/Protect your privacy/i)` found in:
> uBlock filters 


Use: `torrentz2.eu#@#[class]:has-text(/Protect your privacy/i)`

**Comment by Cyberavater** [comment]
OMG!!! it works!!! how did U do it?? Many many thanx to U @gwarser !

**Comment by gwarser** [comment]
Another extension with problems https://chrome.google.com/webstore/detail/torrentz2-magnet-links-%20/ldknhpjddofdohocbhakahagoepainmo

@mapx- `torrentz2.*##[class]:not(body):not(html):has-text(/Protect your privacy/i)` should be OK

**Comment by gwarser** [comment]
@mapx- again. `torrentz2.*##[class]:not(body):not(html):has-text(Sponsored)` this time.
