### ISSUE TITLE
Nano DOM Inspector no property save exception CSS filters

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoCore#244]
### Describe the issue (Required)

Added exception works property after I modify  something in My Filters panel (e.g. add enter and save changes) or restart browser.

### Screenshots (Required)

N/A

### Screenshot of console (Required, press `F12` to open the console)

N/A

### URLs where this issue occurs (Required if applicable)

`https://www.oleole.pl/`

### Reproduction Steps (Optional if trivial)

1. Add to my filters (or subscribe by create file with filters - before reprodce bug / glitch):

   ```
   oleole.pl,wishbone.pl##html:style(overflow: auto !important;)
   ```

1. Open website

1. After open Nano logger, open Nano DOM inspector

1. Try disable added filter, save proposed exception filter and after refresh website still have filter / still detected in DOM inspector.

#### Environment (Required)

- Operating System and Version: Windows 7
- Browser and Version:  Chrome 72
- Nano Adblocker Version: 1.0.0.87
- Nano Defender Version (Optional if you are not using it): N/A

#### Your filter lists (Required)

Nano Adblocker default

#### Your custom filters (Required if you have any)

N/A

**Comment by jspenguin2017** [comment]
The DOM Inspector added extra `www.` to the filter. 

@gorhill FYI.

**Comment by krystian3w** [comment]
BTW:

uBO do not have this glitch.

**Comment by jspenguin2017** [comment]
Could be user stylesheet related, the backup code path might be broken... 
Yea, it does work in uBO. It's kind of weird.

**Comment by jspenguin2017** [comment]
Yea, NVM. I see what's wrong now.

**Comment by jspenguin2017** [comment]
After performing the reproduction steps, two errors are collected (both Nano and uBO), not sure if it's a problem. 
![image](https://user-images.githubusercontent.com/7283682/52832335-4bb62780-3095-11e9-959d-ec28dfeea8a2.png)
![image](https://user-images.githubusercontent.com/7283682/52832338-51137200-3095-11e9-9bbf-c5732ea61b89.png)

**Comment by jspenguin2017** [comment]
The issue specific to Nano (the third error) is fixed. 

Thanks for the report.
