### ISSUE TITLE
Problem with uBlock Origin

### ISSUE THREAD

**Issue by mehdisarvari** [NanoAdblocker/NanoCore#245]
I have no trouble installing my plugin.
But when it comes to training the sources
I add the uBlock Origin plugin. Sites do not work
http://uupload.ir/files/u19a_q.jpg

**Comment by jspenguin2017** [comment]
Fill the template.

**Comment by mehdisarvari** [comment]
> 
> 
> Fill the template.

I did not understand. You teach. Thankful

**Comment by jspenguin2017** [comment]
Fill this: https://github.com/NanoAdblocker/NanoCore/blob/master/.github/ISSUE_TEMPLATE.TXT

**Comment by mehdisarvari** [comment]
### Describe the issue (Required)
I have no trouble installing my plugin Works fine
But when you add sources to the uBlock Origin plugin, I do not have any functionality.


### Screenshots (Required)
http://uupload.ir/files/u19a_q.jpg

### URLs where this issue occurs (Required if applicable)
https://firmware.gem-flash.com

#### Environment (Required)
- Operating System and Version: 
windows 10 64bit
- Browser and Version: firefox 65.0.1 64bit
uBlock Origin 1.18.4

**Comment by jspenguin2017** [comment]
What do you mean by "I do not have any functionality"? The website works fine for me.

**Comment by mehdisarvari** [comment]
It does not work for me
For example, this site is not open to me
https://firmware.gem-flash.com
But when I install the plugin NanoAdblocker The site opens.

**Comment by jspenguin2017** [comment]
The site works fine with uBO or Nano. Try to factory reset your uBO installation.
