### ISSUE TITLE
Missing chromium zip assets in releases v1.0.0.88

### ISSUE THREAD

**Issue by kowith337** [NanoAdblocker/NanoCore#247]
### Describe the issue (Required)
Normally, every releases will have 3-4 items
- `chromium.zip`
- `edge.zip`
- `Source Code (zip)`
- `Source Code (tar.gz)`

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/16535467/53168104-7a3f7f80-360c-11e9-9a5a-de5f6e7b9970.png)

### URLs where this issue occurs (Required if applicable)
`https://github.com/NanoAdblocker/NanoCore/releases/tag/v1.0.0.88`

**Comment by jspenguin2017** [comment]
Thanks. Fixed.
