### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by LiCybora** [NanoAdblocker/NanoCore#249]
There are currently 2 privacy policies. One is general description for both NA and ND found in edge build [here](https://github.com/NanoAdblocker/NanoCore/blob/master/notes/install-in-edge.MD#privacy-policy), and another is for quick issue reporter in ND repo. The later one is already recently updated, while the former one is somehow obsolete and edge specified (though it is supposed for edge). E.g.: Debug-related code already gone during build time and shouldn't have first-party connection anymore. 

Maybe we can remove those descriptions which are not applicable and generalize the policy to all platform?

Edit: Not only about privacy policy, but some user(s) doubt for the permission we ask for. Maybe also include the permission we used for in some page (just as [uBO](https://github.com/gorhill/uBlock/wiki/Permissions) ?).

**Comment by jspenguin2017** [comment]
> while the former one is somehow obsolete

How did you conclude that? 

> Debug-related code already gone during build time and shouldn't have first-party connection anymore.

Sure, but if you load the extension in debug mode, then debug code would still be there. 

> generalize the policy to all platform?

The policy is general and could apply to all platforms. However, only Microsoft Store requires it, and that's why it is placed in the Edge-specific document. 

> Maybe also include the permission we used for in some page

https://github.com/NanoAdblocker/NanoDoc/blob/master/en/Index.MD#other-details

**Comment by LiCybora** [comment]
> How did you conclude that?

I just base on the debug code to come up with that. But you are right, this does not contradict anything written before. Thanks for clarification and I will close this issue.
