### ISSUE TITLE
Cosmetic filtering is not working reliably

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#257]
We became aware that cosmetic filtering is not functioning properly when an Internet page is opened by a local file. We're investigating this issue. UserCSS patch has been disabled in the meantime.

**Comment by jspenguin2017** [comment]
Ruling out browser bug.

**Comment by jspenguin2017** [comment]
uBO 1.18.8 confirmed broken.

**Comment by jspenguin2017** [comment]
uBO 1.18.4 confirmed working.

**Comment by jspenguin2017** [comment]
Diff: https://github.com/gorhill/uBlock/compare/1.18.4...1.18.6

**Comment by jspenguin2017** [comment]
Issue not reproducible when Logger is open.

**Comment by jspenguin2017** [comment]
@gorhill 

Reproduce: 

1. Add `youtube.com##html`
2. Go to `https://youtube.com/` to verify that the page content is hidden
3. Save `<a href="https://youtube.com/" target="_blank" rel="noopener">click</a>` to a local file and open it
4. Go to `chrome://restart`
5. Click the link
6. The page content is showing

Note: Not reproducible when Logger is open. Not reproducible on version `1.18.4`.

**Comment by gwarser** [comment]
[rdk@off uBlock-git]$ git bisect good && ./tools/make-chromium.sh
1c26afe874001c024113ad6a9adf99fb347612a8 is the first bad commit
commit 1c26afe874001c024113ad6a9adf99fb347612a8
Author: Raymond Hill <rhill@raymondhill.net>
Date:   Wed Feb 20 08:51:14 2019 -0500

    Remove caching the result of domain extraction from hostname
    
    With the new PSL implementation, benchmarks do not show benefit
    from caching the domain extracted from a hostname for later
    reuse -- the caching seems to even add an overhead instead with
    the new publicSuffixList implementation.

:040000 040000 fdb88d9d07a58e008062747802b455d6a26e812b b98dbe1c5e67127d8268a4a600124a031833d51a M      src

**Comment by gorhill** [comment]
> Remove caching the result of domain extraction from hostname

Weird, I am unable to explain how not caching the base domain name can cause an issue.

**Comment by gorhill** [comment]
Beside the repro case here, what real cases are being brought forth? I am trying to evaluate whether this needs an emergency fix.

**Comment by gwarser** [comment]
No need to restart. I can reproduce by clicking (left or middle - always opens new tab) link from local file (from STR). Generic cosmetic filters seems to be applied. Only specific are not. Cannot reproduce on links from bookmarks/newtab.

**Comment by gwarser** [comment]
Something is mixed with partyness. On old builds last 'doc' is 1p. On new 3p.

![Screenshot_20190402_163926-1](https://user-images.githubusercontent.com/886325/55411989-e942b900-5566-11e9-8bdb-838d120da3b0.png)

![Screenshot_20190402_164107](https://user-images.githubusercontent.com/886325/55411996-ee076d00-5566-11e9-86a8-678baf29f66d.png)

**Comment by gorhill** [comment]
> Something is mixed with partyness.

So it seems the content scripts are injected before the PSL is ready, hence leading to `www.youtube.com` being seen as 3rd-party to `youtube.com` (because base domain is `domain || hostname`, and `domain === ''` will be returned if PSL is not ready.

**Comment by jspenguin2017** [comment]
@gwarser That's the change that broke it? How is that even possible? 

-----

> @gorhill 
> what real cases are being brought forth

This is a real case, I use local HTML files regularly. 

-----

> @gorhill 
> So it seems the content scripts are injected before the PSL is ready

How long does it take for PSL to be ready? I can reproduce even if I wait 10 seconds.

**Comment by gorhill** [comment]
> How long does it take for PSL to be ready?

Never mind, I misunderstood this was occurring at browser launch. I can reproduce.

**Comment by jspenguin2017** [comment]
Confirmed working. Closing.
