### ISSUE TITLE
Yandex browser i don't can add a new filter list

### ISSUE THREAD

**Issue by mat41997** [NanoAdblocker/NanoCore#26]
1.
i don't see a button to i can add a filter list
![screenshot_2017-12-12-02-24-52](https://user-images.githubusercontent.com/5884000/33862800-d4f18854-dee4-11e7-9811-6c665869a790.png)

![screenshot_2017-12-12-02-24-59](https://user-images.githubusercontent.com/5884000/33862808-dfd889ac-dee4-11e7-8604-c6f4019a031f.png)

2.
and on this site
`https://www.certyficate.it/adblock/`
buttons subscribe probably don't works on yandex browser
![screenshot_2017-12-12-02-30-33](https://user-images.githubusercontent.com/5884000/33862766-b1d61ccc-dee4-11e7-9a1a-3d9acd18709e.png)

Nano Adblocker 1.0.0.9
Nano Defender 13.0

My ua from
`http://www.whatsmyua.info/`

```
Mozilla/5.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 YaBrowser/17.10.2.145.00 Mobile Safari/537.36
```

**Comment by mat41997** [comment]
i have this same problem on my chrome in windows
![2017-12-12 02_39_20-nano panel sterowania](https://user-images.githubusercontent.com/5884000/33863053-3b613bce-dee6-11e7-9d71-4d63b2857446.png)

**Comment by mat41997** [comment]
ohh.. i think you can relocate the button "accept the filter list"

**Comment by jspenguin2017** [comment]
It's a fork of uBO, and I haven't mess with the dashboard.
