### ISSUE TITLE
A search bar for searching rules in filters.

### ISSUE THREAD

**Issue by lancelot-moon** [NanoAdblocker/NanoCore#260]
uBO has the search bar for searching rules in filters.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/1XE0dP6.png)
</details><br/>

May Nano give the search bar?

Thanks.

**Comment by jspenguin2017** [comment]
Press `Ctrl+F` to bring it up. 
![image](https://user-images.githubusercontent.com/7283682/55678671-ede6d480-58ba-11e9-9362-c1f5dbc51204.png)
