### ISSUE TITLE
Question: Why does this exist?

### ISSUE THREAD

**Issue by jerkstore369** [NanoAdblocker/NanoCore#265]
What's wrong with ublock origin? I don't get it.

**Comment by jspenguin2017** [comment]
Then don't use it. I want a better syntax highlighter.

**Comment by DandelionSprout** [comment]
I would also say that there's a few other enthusiast-aimed features as well, such as easier integration with Nano Defender, the non-inclusion of non-HTTPS lists, and better/more settings in the Advanced Settings menu.
