### ISSUE TITLE
Add a value option to autoCommentFilterTemplate to generate the full URL as a comment

### ISSUE THREAD

**Issue by DandelionSprout** [NanoAdblocker/NanoCore#267]
### Describe the issue (Required)

When I create entries through the element picker, the URL comment above it only shows the core domain, and not the entire URL. I have modified `autoCommentFilterTemplate` to only use `{{origin}}`, but I wish for a value along the lines of `{{fullorigin}}` that would display the entire URL of where the entry was created, which [uBO's wiki says is currently not possible](https://github.com/gorhill/uBlock/wiki/Advanced-settings#autocommentfiltertemplate).

Such a value would've been a considerable timesaver for my work on Nano Placeholder Buster, among other places where I have to provide example links when I submit things (e.g. uAssets).

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/22780683/58375888-e1e3ce80-7f5d-11e9-8a9c-f1e787791279.png)

### Screenshot of console (Required, press `F12` to open the console)

(Doesn't seem to be relevant to this issue.)

### URLs where this issue occurs (Required if applicable)

Practically everywhere, but let's use `https://www.howtogeek.com/360938/no-microsoft-isnt-turning-windows-10-into-a-paid-subscription-service/` as the example page for this issue.

### Reproduction Steps (Optional if trivial)

1) Ensure that `My Filters` is empty.
1.5) If *Advanced Settings* are turned on: Ensure that `autoCommentFilterTemplate` contains `{{origin}}` as one of its values.
2) Go to `https://www.howtogeek.com/360938/no-microsoft-isnt-turning-windows-10-into-a-paid-subscription-service/`.
3) Open the element picker tool.
4) Hide whichever thing on the page, e.g. `##article`.
5) Go back to `My Filters`.
6) See that the auto-generated comment above the entry shows `! https://www.howtogeek.com` instead of `! https://www.howtogeek.com/360938/no-microsoft-isnt-turning-windows-10-into-a-paid-subscription-service`.

### Anything else you believe to be useful (Optional)

This most likely applies to uBO as well, but I get the personal perception that you're more open to new ideas than what gorhill is, so I'm suggesting it to you first.

#### Environment (Required)

- Operating System and Version: Windows 10 May 2019 Update
- Browser and Version: Chrome 74.0.3729.169 64-bit
- Nano Adblocker Version: 1.0.0.112
- Nano Defender Version (Optional if you are not using it): 15.0.0.147

#### Your filter lists (Required)

(Doesn't seem to be relevant to this issue.)

#### Your custom filters (Required if you have any)

None at the time of the test.

#### Your other extensions (Required if you have any)

![image](https://user-images.githubusercontent.com/22780683/58375946-2754cb80-7f5f-11e9-94d6-a894c1b856ba.png)

**Comment by jspenguin2017** [comment]
Sure, should be an easy change.

**Comment by jspenguin2017** [comment]
The new option will be `{{nanoHref}}`, case sensitive.

**Comment by jspenguin2017** [comment]
Will be available on next release. 
![image](https://user-images.githubusercontent.com/7283682/58376634-2a829400-7f2c-11e9-8c86-570868005d7a.png)
