### ISSUE TITLE
Logger enhancements

### ISSUE THREAD

**Issue by hjyoung1** [NanoAdblocker/NanoCore#269]
Can you please make some enhancements for mobile users 
![Screenshot_20190610-141338__01__01](https://user-images.githubusercontent.com/45882061/59186495-9f8ed400-8b90-11e9-91a4-26ce5edbebc3.jpg)
Check red outline part it would be great if logger entries fill whole screen.
Also make logger entries horizontally scrollable so it becomes possible to view full details.
Thanks.

**Comment by jspenguin2017** [comment]
That looks like a browser bug.

**Comment by hjyoung1** [comment]
Ah looks like your correct. I'm using kiwi browser I'll report this to kiwi browser devloper.
But even on other browsers list is not horizontally scrollable.
