### ISSUE TITLE
Mark csp_report as valid in my filters panel

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoCore#273]
### Describe the issue (Required)

Why `csp_report` is marked as invalid option?

### Screenshots (Required)

> ![obraz](https://user-images.githubusercontent.com/35370833/59968400-a119ae00-9539-11e9-9516-cbff42b00d96.png) |
> --- |

### Screenshot of console (Required, press `F12` to open the console)

N/A

### URLs where this issue occurs (Required if applicable)
N/A

### Reproduction Steps (Optional if trivial)

N/A

### Anything else you believe to be useful (Optional)

N/A

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version:  Chrome 75
- Nano Adblocker Version:  1.0.0.115
- Nano Defender Version (Optional if you are not using it):  N/A

#### Your filter lists (Required)

Default

#### Your custom filters (Required if you have any)

N/A

#### Your other extensions (Required if you have any)

N/A

**Comment by jspenguin2017** [comment]
It's not supported by uBlock Origin.

**Comment by jspenguin2017** [comment]
I believe it's part of `$other`, I have to check the code to confirm.

**Comment by jspenguin2017** [comment]
The linter is correct, `csp_report` is not a valid option. 
https://github.com/gorhill/uBlock/blob/a436102ff779531eab9ae32ce5ae03cd415f1a06/src/js/static-net-filtering.js#L1837-L1866
