### ISSUE TITLE
add bogachenko anti-adblock list to filters dashboard

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#274]
https://github.com/bogachenko/fuckfuckadblock

**Comment by jspenguin2017** [comment]
Is it needed? Which website does it fix?

**Comment by KonoromiHimaries** [comment]
@bogachenko

**Comment by bogachenko** [comment]
>Is it needed?

idk. it's up to you

> Which website does it fix?

well, I did not report many sites in uBlockOrigin/uAssets and corrected them myself, although there are also most similar.

**Comment by jspenguin2017** [comment]
I would ask you to report them to uAssets. This looks like duplicated effort for no reason.
