### ISSUE TITLE
"Block element" interface can't be opened

### ISSUE THREAD

**Issue by megamilk1999** [NanoAdblocker/NanoCore#275]
### Describe the issue (Required)
I am not able to open the "Block element..." interface.

### Screenshots (Required)
![Screenshot_7](https://user-images.githubusercontent.com/52380472/60399303-1bf25280-9b52-11e9-8302-a2bab170e543.png)
![Screenshot_1](https://user-images.githubusercontent.com/52380472/60399304-1d237f80-9b52-11e9-92a1-6b1a5252ae44.png)

### Screenshot of console (Required, press `F12` to open the console)
![Screenshot_6](https://user-images.githubusercontent.com/52380472/60399276-b56d3480-9b51-11e9-97fc-2fabab0fdfbc.png)

#### Environment (Required)
- Operating System and Version: Windows 7 Ultimate, SP1
- Browser and Version: Firefox, 67.0.4, 64-bit
- Nano Adblocker Version: 1.0.0.117
- Nano Defender Version (Optional if you are not using it):  15.0.0.153

#### Your filter lists (Required)
Adguard annoyances
Anti-Facebook List
Fanboy's Social Blocking List
#### Your custom filters (Required if you have any)
Adblock the NSA

#### Your other extensions (Required if you have any)
HTTPS Everywhere
Decentraleyes
Facebook Container
Nano Defender
Tampermonkey
Imagus
Private Bookmarks
Image Search Options

**Comment by jspenguin2017** [comment]
Can't reproduce on Chrome. For Firefox-specific issues, report to https://github.com/LiCybora/NanoCoreFirefox/issues
