### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by aelisya** [NanoAdblocker/NanoCore#276]
### Describe the issue (Required)
It would be nice in the extension theme to use the new CSS media function to honor the system color theme (dark or not).

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Examples

**Comment by jspenguin2017** [comment]
Contribution required.

**Comment by aelisya** [comment]
I would look at how the interface works when I have free time
and would make a pull request if I find where add the functions

**Comment by ratatoeey** [comment]
shouldn't it be first supported in [ublock origin](https://github.com/gorhill/uBlock)?

----

regards ratatoeey

**Comment by jspenguin2017** [comment]
Well, you're free to contribute to upstream, but I think either way it needs to be contributed. 

Keep in mind that dark theme is bad for your eyes, and unless you have a pretty advanced device, dark theme isn't going to save meaningful amount of battery. That being said, I'm still willing to entertain the idea as long the implementation is backward compatible and defaults to light theme.

**Comment by llacb47** [comment]
dark theme bad for your eyes?

**Comment by jspenguin2017** [comment]
@llacb47 Yes. 

https://ux.stackexchange.com/questions/53264/dark-or-white-color-theme-is-better-for-the-eyes

> However, most studies have shown that dark characters on a light background are superior to light characters on a dark background

**Comment by aelisya** [comment]
you are wrong, oled laptops consume less with a dark theme because some pixels of the screen are off

**Comment by jspenguin2017** [comment]
@aelisya I wouldn't say I was wrong, I said "unless you have a pretty advanced device", and I would consider OLED devices to be pretty advanced. I know none of my devices have OLED screens.

**Comment by ratatoeey** [comment]
> dark theme bad for your eyes?

It depends. 

so, here are my opinions, that may be right or wrong. but from a quick reading of
- https://ux.stackexchange.com/questions/53264/dark-or-white-color-theme-is-better-for-the-eyes
- https://ux.stackexchange.com/questions/52833/which-color-scheme-to-choose-for-applications-that-require-long-work-hours/52947#52947 
- https://ux.stackexchange.com/questions/8153/what-are-the-negative-and-positive-aspects-of-dark-color-scheme

I can say, to be brief, the most upvoted answers are 100% composed of parroted, incoherent arguments ,ie., stupid. and the studies cited were horribly interpreted to mean that white theme are better on screens. I wasted my time, you can save yours by experimenting on yourself and see what works better for you.

I don't care about white themes on screens, in fact, as they are useless for me, I call them bloat or bug, when I want to save my time.

**Comment by jspenguin2017** [comment]
I like light theme better and I find dark theme harder to read. This does matter to the original request as I will not implement features that I would not use myself. 

As I said, contribution is required for dark theme. There is no point in further discussion in this thread, open a pull request if you wish to contribute.

**Comment by jspenguin2017** [comment]
Looks like this is being implemented upstream. Please contribute to this feature in the upstream project instead.
