### ISSUE TITLE
Issue with translated webpage and Nano Defender

### ISSUE THREAD

**Issue by givemeatip** [NanoAdblocker/NanoCore#283]
### Describe the issue (Required)
So, whenever I use an extension such as Google Translator for Firefox or ImTranslator and try to translate from English to Portuguese the following webpage: https://schuessler-cell-salts.com/facial-diagnosis/index.htm
Firefox starts to become extremely sluggish and if I select any text on the translated webpage, my whole system freezes and the only way to get back is to unplug my computer from power source and restart the system! So, the reason I'm reporting this here as well is because Firefox told one time during these freezes that Nano Defender was slowing down it and asked me if I wanted to disable it temporarily.

### Screenshots (Required)
![site cuja tradução no firefox está bugada](https://user-images.githubusercontent.com/48328287/62645469-a92f8080-b922-11e9-828d-3c74a643eeba.png)

### Screenshot of console (Required, press `F12` to open the console)
![console no site que buga](https://user-images.githubusercontent.com/48328287/62645610-f14ea300-b922-11e9-9bca-a40ef7578b33.png)

### URLs where this issue occurs (Required if applicable)
https://schuessler-cell-salts.com/facial-diagnosis/index.htm
https://translate.google.com/translate?depth=1&hl=pt-BR&rurl=translate.google.com&sl=auto&tl=pt-BR&u=https://schuessler-cell-salts.com/facial-diagnosis/index.htm

### Reproduction Steps (Optional if trivial)

Use Google Translator for Firefox or ImTranslator and try to translate from English to Portuguese the following webpage: https://schuessler-cell-salts.com/facial-diagnosis/index.htmhttps://schuessler-cell-salts.com/facial-diagnosis/index.htm

#### Environment (Required)

- Operating System and Version:  Windows 10 Home 1903
- Browser and Version: Firefox 68.0.1 64-bits
- Nano Adblocker Version: 1.0.0.123
- Nano Defender Version (Optional if you are not using it): 15.0.0.158

#### Your filter lists (Required)

It's default plus I activated the filter "SPA, POR: AdGuard Spanish/Portuguese" as well.

#### Your other extensions (Required if you have any)
Absolute Enable Right Click & Copy	1.3.8	true	{9350bc42-47fb-4598-ae0f-825e3dd9ceba}
Auto Tab Discard	0.3.2.1	true	{c2c003ee-bd69-42a2-b0e9-6f34222cb046}
Bing	1.0	true	bing@search.mozilla.org
DuckDuckGo	1.0	true	ddg@search.mozilla.org
EverSync - Sync bookmarks, backup favorites	18.5.5	true	fvdmedia@gmail.com
Feedly Notifier	2.22.2	true	jid1-BOjn8b0IM7kH2w@jetpack
Feedly Subscribe Button	0.9.0	true	{a8ffd15d-67d0-427f-80ad-07a7d76431e1}
Firefox DevTools ADB Extension	0.0.5	true	adb@mozilla.org
Free Download Manager	3.0.40	true	fdm_ffext2@freedownloadmanager.org
Google	1.0	true	google@search.mozilla.org
HTTPS Everywhere	2019.6.27	true	https-everywhere@eff.org
ImTranslator: Tradutor, Dicionário, Voz	15.27	true	{9AA46F4F-4DC7-4c06-97AF-5035170634FE}
LastPass: Free Password Manager	4.29.0.4	true	support@lastpass.com
Magic Actions for YouTube™	7.8.5.1	true	jid0-UVAeBCfd34Kk5usS8A1CBiobvM8@jetpack
MercadoLivre	1.0	true	mercadolivre@search.mozilla.org
Nano Adblocker	1.0.0.123	true	{af881826-e0f9-4b97-898a-a416dc473545}
Nano Defender	15.0.0.158	true	{fcf60470-b210-4c17-969e-9ae01491071e}
OneTab	1.29	true	extension@one-tab.com
Privacy Badger	2019.7.1.1	true	jid1-MnnxcxisBPnSXQ@jetpack
Proteção Kaspersky	20.0.543.428d-20181114115800	true	light_plugin_F88CEF8523DE460F9FA1D6E48BF8D340@kaspersky.com
Share Buttons	0.9.0	true	{c1cdfdba-cfc9-48f1-9dcf-d7a3d0e3a029}
Twitter	1.0	true	twitter@search.mozilla.org
Wikipedia (pt)	1.0	true	wikipedia@search.mozilla.org

**Comment by LiCybora** [comment]
Are you sure the problem is because of Nano Defender/Adblocker? I can reproduce even with all extension disabled but Translator.  I guess you should report to site, Mozilla or Google for the issue. I tried other site and they are working fine even with all Nano on.

Moreover, your console screenshot is not console but inspector, although not a big deal.

**Comment by jspenguin2017** [comment]
Works fine on Chrome. I don't manage the Firefox port, @LiCybora will help you with that.
