### ISSUE TITLE
Nano Highlighter initial implementation

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#29]
Initial implementation finished. Please open new issues for other problems.

**Comment by jspenguin2017** [comment]
Current profile: 
![image](https://user-images.githubusercontent.com/7283682/33892867-2c397522-df17-11e7-9924-d5cf03f62d1c.png)

**Comment by jspenguin2017** [comment]
uBO's profile: 
![image](https://user-images.githubusercontent.com/7283682/33892980-78151e88-df17-11e7-985e-c20f4f73c0f5.png)

**Comment by jspenguin2017** [comment]
I might have to use a negative look-ahead, but I'm a bit worried about performance as it will have to scan the text twice.

**Comment by jspenguin2017** [comment]
~~Negated domains are not properly handled~~ @ameshkov Shouldn't that be `|` instead of `,`? 
![image](https://user-images.githubusercontent.com/7283682/33963204-66c8ddfe-e011-11e7-85f1-34822f5e8b42.png)
Test cases: 
```
||coinhive.com^$third-party,domain=~cnhv.co,~coinhive.com
```

**Comment by ameshkov** [comment]
Your syntax highlighter is awesome!

**Comment by jspenguin2017** [comment]
Old opening: 

RegExp rules are not properly handled when the RegExp contains `$`. 
![image](https://user-images.githubusercontent.com/7283682/33891644-cd3ba944-df13-11e7-898f-720a9c9a315b.png)
Test cases: 
```
/\.download\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.faith\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.link\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.loan\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.lol\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.men\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.online\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.party\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest
/\.racing\/[0-9]{2,9}\/$/$script,stylesheet,third-party,xmlhttprequest

/http://[a-zA-Z0-9]+\.[a-z]+\/.*(?:[!"#$%&'()*+,:;<=>?@/\^_`{|}~-]).*[a-zA-Z0-9]+/$script,third-party,domain=keezmovies.com|redtube.com|tube8.com|tube8.es|tube8.fr|www.pornhub.com|youporn.com
```

-----

~~Also, these rules are in EasyList but Nano Highlighter marks them as invalid:~~ Those options are not accepted by Nano. 
```
||ngohq.com/images/ad.jpg$~collapse
@@||oload.tv^$genericblock,generichide
@@||openload.co^$genericblock,generichide
@@||streamango.com^$genericblock,generichide
@@||spiegel.de^$genericblock,generichide
```
![image](https://user-images.githubusercontent.com/7283682/33892019-eb7d5604-df14-11e7-90de-675ad37d1b92.png)

-----

`,` in `script:inject` arguments should be treated as operator just like other `,`. 
That's how it's parsed. 

-----

Handle folding of `!#if` preprocessor directive. https://github.com/AdguardTeam/AdguardBrowserExtension/issues/917
Ace's doc on this is pretty non-existent... Might have to read deep into their code. 

-----

Something is not right with Traditional Chinese locale: 
https://github.com/NanoAdblocker/NanoCore/issues/40#issuecomment-352161750

**Comment by jspenguin2017** [comment]
This is fixed: 

RegExp rule highlighting is not properly fixed: 
![image](https://user-images.githubusercontent.com/7283682/34344083-d364efa2-e99e-11e7-91f8-9eac0c2f42bd.png)
Test rules: 
```
/test$/
```

**Comment by ameshkov** [comment]
JFYI,

I've just figured that Ace provides an easy conversion from TextMate language to Ace rules:
https://github.com/ajaxorg/ace/wiki/Importing-.tmtheme-and-.tmlanguage-Files-into-Ace

The thing is that a lot of filters maintainers use external text editors (besides the filters editor inside of a blocker), and most of the popular text editors (Sublime, Atom, VS Code) support TextMate language extensions, so it might useful to use a TM language as the main source for the rules.

I'm planning to experiment with this during the holidays, but anyway, I guess this might be useful to you if you decide to do the same.

Here's a simple VS code language plugin:
https://github.com/ameshkov/VscodeAdblockSyntax

TM language file:
https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/syntaxes/adblock.tmLanguage.json

It's rather simple (as I've just made it) and can only highlight classic elemhide rules:
![](https://uploads.adguard.com/up04_u9ahj_Extension_Development_Host_-_Untitled-1.png)

**Comment by jspenguin2017** [comment]
Filter rules are different than other programming language, it's not something you'd code 100 lines and test them together, I find myself code them in Nano's IDE, test them right away, then paste them into my filter list. Nano will validate and lint it right away with the existing filter parser, which can be a bit difficult to implement in Atom plugin. 

At first, I tried to make a plugin for Atom, but then I couldn't find the proper documentation. Maybe I was missing something...

**Comment by ameshkov** [comment]
> Filter rules are different than other programming language

Take a look at all the languages VS code supports, some of them are very different from imperative languages we are used to:
https://github.com/Microsoft/vscode/tree/master/extensions

> Nano will validate and lint it right away with the existing filter parser, which can be a bit difficult to implement in Atom plugin.

I suppose, that validation and syntax highlighting are different types of tasks indeed. Every editor provides its own way for that. For instance, VS code does it via "language server" extensions. Some obvious mistakes can be highlighted using regular expressions, though.

Regarding Atom, it also supports the TextMate theme conversion:
http://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/

**Comment by Ravizz** [comment]
https://github.com/gorhill/uBlock/issues/3331#issuecomment-364668956

**Comment by elypter** [comment]
if you really want to pick on him then rub it in less direct with a more friendly tone, then nobody can feel offended. but still, i suggest not getting in a fight with them. they are do a lot more good than bad. there are a million better choices. dunno, facebook pages of lobbyists, sociopathic ceos or people wearing socks in sandals.

**Comment by Ravizz** [comment]
Please stop personal attacks/accusations/slanders/harassing into my direction, your behaviour is the same behaviour like the guys's who were harassing me there: https://github.com/gorhill/uBlock/issues/3489 I don't offend anybody, and I have no intention to offend anybody, my comments are not different than comments of other people, since this is just a pure text, I don't know what is yours problem of misinterpreting tone of my comments, and I don't know if that is some kind of emotional problem at yours side, it seems some of people are overreacting here on github. One more situation of this kind and I'm considering contacting github support and reporting being harassed by trolls.

**Comment by jspenguin2017** [comment]
Unless you guys have constructive comments, just don't post it. It's not getting anywhere, and it's not possible to change gorhill's mind, I guess we all know that by now.

**Comment by jspenguin2017** [comment]
I don't mind civil discussions, but the discussion is getting off topic from development of Nano.

**Comment by Ravizz** [comment]
@jspenguin2017 t the link I pasted was related to the title of this thread, so it was not off-topic, and it not meant to be constructive, because I pasted it just for information, coz the issue the link leads to, is closed, so I've just wanted to make sure you won;t miss my comment, as many times in past, in other repos it was hapenning that some people simply don't read or miss comments written in closed threads...

**Comment by jspenguin2017** [comment]
Added preprocessor highlighting
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/917

More complicated preprocessors are not implemented and it looks like they won't be implemented anytime soon, so I'm closing this issue. Please open new issues for other problems.

**Comment by jspenguin2017** [comment]
I'll actually leave this thread open for quick comments, but please report more complicated problems in new issues.
