### ISSUE TITLE
Option to use a PageAction

### ISSUE THREAD

**Issue by Madis0** [NanoAdblocker/NanoCore#292]
### Describe the issue (Required)
Consider allowing the user to switch the button from a browser action to a [page action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction).

Pros:

- Better UI integration as it appears as an address bar icon (like Firefox's Tracking Protection or Brave's protections)
- Can auto-hide on unsupported internal pages

Cons:
- Goes against the principle  "actions that are only relevant to particular pages"
- Useful mainly on Firefox and Vivaldi, most Chromium-based browsers [make both buttons look the same](https://developer.chrome.com/extensions/pageAction)
- No badge support

Previously discussed on https://github.com/gorhill/uBlock/issues/3203, although with a slightly different scope.

_P.S. I did not follow the issue template because this is a _suggestion_ and you don't seem to have a specific issue template for suggestions._

**Comment by jspenguin2017** [comment]
> Better UI integration as it appears as an address bar icon

I don't want it to be in the address bar. 

> Can auto-hide on unsupported internal pages

I want to see the icon all the time. Even on unsupported pages, the popup is still useful. 

> No badge support

Yes, that's a problem, I want the badge.
