### ISSUE TITLE
NanoAdblocker causes internet to "freeze" across entire browser

### ISSUE THREAD

**Issue by judy** [NanoAdblocker/NanoCore#294]
### Describe the issue (Required)

At random, the entire browser will act like the nothing on the Internet is responding. Like the router is frozen for a minute... but I've gone down a rabbit hole to figure out that it's NanoAdblocker.

### Screenshots (Required)

![In the middle of an "outage", this is all that renders when clicking NanoAdblocker.](https://user-images.githubusercontent.com/50157726/69254117-b4ca4e80-0b83-11ea-9a11-1f18180f3ca9.png)

### Screenshot of console (Required, press `F12` to open the console)

![I've pulled up multiple tabs' consoles, but don't see anything out of the ordinary.](https://user-images.githubusercontent.com/50157726/69254142-c0b61080-0b83-11ea-82be-a73315020520.png)

### URLs where this issue occurs (Required if applicable)

All URLs.

### Reproduction Steps (Optional if trivial)

This happens randomly, and I haven't figured out how to reproduce it on demand yet. Which makes this bug all the more irritating.

1. I will click on a link, or open a new tab or window to go to a new address. Nothing out of the ordinary, only regular internet browsing for work.
2. Firefox will start acting like the internet is taking an extremely long time to respond. Not just the link I clicked on, but any other link, opening new windows, etc.
3. Clicking on the NanoAdblocker extension 
4. After roughly 60 seconds or so, NanoAdblocker starts responding, and all of the tabs I opened waiting for the internet to respond, start working at the same time. (I could time this if it would be useful.)

### Anything else you believe to be useful (Optional)

For weeks now, I thought this was my internet connection, either my ISP or my router. Not like the connection has been broken, but like the packets are taking forever to respond, across all open Firefox tabs. The issue acts exactly like that would be the case, and I was preparing to plunk down a ton of money on replacing the router. So here's how I figured out that it's this extension:

Yesterday when it happened, I switched from my MacBook Pro to my PC, and realized that Firefox on it (with NanoAdblocker installed there too) was working just fine. That narrowed it down to the MacBook somehow.

So the second time it happened yesterday, I opened up Chrome, which has uBlock on it. That browser wasn't having issues either. I was also able to use `curl` and `ping` from the terminal without issues, so that narrowed it down to Firefox.

The third time it happened, I opened up a Private Browsing window. The issue **was** happening there. But the only extension I allow to run in Private Browsing was NanoAdblocker. (FWIW, I also have Nano Defender installed and running in Private Browsing, _I haven't ruled it out yet_). So I disabled it from Private Browsing and waited for the fourth time.

When the fourth time happened, I opened a new Private Browsing window in Firefox, and it was able to go to the same link I had been trying. Back in my regular Firefox window, I clicked on NanoAdblocker, and found that it was rendering only the outline of the dropdown, but none of the content inside it was loading.

#### Environment (Required)

- Operating System and Version: macOS Mojave 10.14.6
- Browser and Version: Firefox 70.0.1 (64-bit)
- Nano Adblocker Version: 1.0.0.131
- Nano Defender Version: 15.0.0.170

#### Your filter lists (Required)

![Screenshot 2019-11-20 10 28 15](https://user-images.githubusercontent.com/50157726/69252096-7aab7d80-0b80-11ea-9c16-b457436cc052.png)

#### Your custom filters (Required if you have any)

None here.

#### Your other extensions (Required if you have any)

- 1Password
- Bypass Paywalls
- Facebook Container
- Firefox Multi-Account Containers
- HTTPS Everywhere
- RescueTime for Firefox

Only NanoAdblocker and Nano Defender are enabled to run in Private Browsing.

**Comment by judy** [comment]
Edited bug to add screenshots, as it just happened again.

I'd love to find logs generated by NanoAdblocker to help figure out what's happening, but haven't been able to find any. Not familar with Firefox extension development. If you can send me a location, I can get you any other information you need.

**Comment by jspenguin2017** [comment]
I use my extensions every day on both of my devices, and I have yet to experience something like this. I don't maintain the Firefox build, if this can't be reproduced on Chrome / Chromium, you would have to report it here: https://github.com/LiCybora/NanoCoreFirefox

**Comment by LiCybora** [comment]
> I'd love to find logs generated by NanoAdblocker to help figure out what's happening, but haven't been able to find any. Not familar with Firefox extension development. If you can send me a location, I can get you any other information you need.

You may go `about:debugging#/runtime/this-firefox` and click `Inspect` button for Nano Adblocker to see if there is any error message.

> When the fourth time happened, I opened a new Private Browsing window in Firefox, and it was able to go to the **same link** I had been trying.

Can you provide the link also? I cannot reproduce and never experience on your problem.

**Comment by judy** [comment]
> you would have to report it here

Alright, I'll make the same report there and reference this one.



> Can you provide the link also? I cannot reproduce and never experience on your problem.

The link doesn't matter, this happens regardless of which page I'm on and where I'm going. I'll be searching Google to solve problems at work, or shopping Amazon, or checking Youtube or Hacker News... this is always happening and it doesn't matter where I go.
