### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by haze242** [NanoAdblocker/NanoCore#298]
Periodically, after the launch browser, I see missed ads, open settings, turn to filters, the first second watching a blank space instead of a list of filters, missing even those that default, then they reappear, but 50% - "0 used out of 0".

https://i.imgur.com/QwScZZ6.png

"Purge all cashes" + "Update now" fix the problem, but after restarting browser, it comes back.

Windows 7, Firefox 70, Nano Adblocker v1.0.0.131 (Based on uBlock Origin Version/1.23.0 Commit/a5601b8), suspendTabsUntilReady true

Sorry for my English

**Comment by haze242** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/808

**Comment by jspenguin2017** [comment]
I never experienced this issue on Chromium, for Firefox specific issues, report it here: https://github.com/LiCybora/NanoCoreFirefox/issues
