### ISSUE TITLE
Incompatible with other extensions

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoCore#299]
Issue #234 is reappearing.

**Comment by llacb47** [comment]
You could have just commented on that issue again instead of opening a new issue.

**Comment by Cyberavater** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/367#issuecomment-513564810

**Comment by jspenguin2017** [comment]
Yes, don't dig up old issues. New problem, new issue. 

In the future, I'll have NanoMeow to auto-lock issues that are closed for 7 days.

**Comment by jspenguin2017** [comment]
As for incompatibility with other extensions, it's generally a won't fix.

**Comment by gwarser** [comment]
Add to My filters:

    torrentz2.eu#@#[class]:has-text(Sponsored)
