### ISSUE TITLE
Possible typo “grante” in NanoCore2’s code for nano-grant-fake-notification.js

### ISSUE THREAD

**Issue by roryokane** [NanoAdblocker/NanoCore#301]
This is a probable issue I saw when browsing the code, not an actual issue I got when running and using the extension, so I have no screenshots or reproduction steps.

The problem I saw is in [line 259 of `src/snippets.js` in NanoCore2](https://github.com/NanoAdblocker/NanoCore2/blob/2ba85c82321790e8cc10761a84b974a76bce309c/src/snippets.js#L259):

~~~js
Notification.permission = 'grante';
~~~

With context:

~~~js
// Grant fake notification permission
//
/// nano-grant-fake-notification.js
(() => {
    Notification = function () { };
    Notification.permission = 'default';
    Notification.requestPermission = function (callback) {
        Notification.permission = 'grante'; // ← ← ← THIS IS THE LINE ← ← ←
        if (callback) {
            setTimeout(callback, 0, 'granted');
        }
        return Promise.resolve('granted');
    };
})();
~~~

I don’t know exactly what that code is doing, but my guess is that `'grante'` is a mistake. (If that spelling weren’t a mistake, I would expect the line to have a comment like `// misspelled on purpose in order to …`.) Changing that string to `'granted'` might fix a bug.

### Background

Why was I reading that file when I haven’t even installed the extension yet? My path was as follows:
1. Find [LiCybora/NanoCoreFirefox](https://github.com/LiCybora/NanoCoreFirefox) and read its README
1. Follow the link “[Tweaked filter syntax](https://github.com/NanoAdblocker/NanoCore2/blob/master/notes/filter_syntax.md#filter-syntax)” to the Filter Syntax document
1. Follow the link “[extra resources](https://github.com/NanoAdblocker/NanoCore2/blob/master/src/snippets.js)” to `src/snippets.js`
1. Browse through the code, trying to figure out what it has to do with the concept of extra resources. Then notice that potential typo.

Reading `snippets.js` still hasn’t helped me figure out what kind of feature “extra resources” is – as a separate matter, you might want to reword that link in the Filter Syntax document.

**Comment by llacb47** [comment]
Extra resources is mainly extra scriptlets I think.

**Comment by jspenguin2017** [comment]
Yes, that's a typo, it's now fixed. Thanks for pointing it out. The script snippet in question is not currently used, so I'll wait until next release to ship the fix. 

Extra resources are redirect targets and script snippets that are not included in uBlock Origin by default (thus "extra"), they're intended to be used by advanced users and filters maintainers only.
