### ISSUE TITLE
Tiny text in popup/dashboard with Vivaldi

### ISSUE THREAD

**Issue by neosignal** [NanoAdblocker/NanoCore#302]
Even if I zoom in it always resets to default tiny state.
Sorry if it's not actually a bug but normal behavior, I'm not sure. In chrome the dashboard zoom seems to stay, but the popup is tiny as well.
Vivaldi clean profile, nano defender installed.
![gabbbocakeomblphkmmnoamkioajlkfo 1da98a77c744](https://user-images.githubusercontent.com/48186768/71646310-45c03980-2c9b-11ea-8654-177f3d34cc7c.png)
![Image1](https://user-images.githubusercontent.com/48186768/71646311-45c03980-2c9b-11ea-98fd-622d5e427153.png)

**Comment by jspenguin2017** [comment]
I don't see any issues in your screenshots, the text appear in the expected size and I can read them easily. 

If you're using a high DPI screen, there are sometimes scaling issues, those are bugs with your browser or operating system. Keep in mind that when taking a screenshot on a high DPI screen, it will larger on a normal screen.

**Comment by jspenguin2017** [comment]
Also zoom is handled by your browser, if you'd like your zoom to stay, contact the developers of your browser.

**Comment by neosignal** [comment]
yeah, it's readable, but barely, it's smaller than everything else on a 27' 1440p screen. strange thing, i never had this issue until I reinstalled OS and made a fresh vivaldi profile.
zoom is actually remembered for normal pages, but not in nano for some reason, even if I do zoom it, it always resets. i know it probably won't be fixed in vivaldi or in nano since it looks like i'm the only one with that silly issue, but still, maybe someone out there hacked around it?
![Image1](https://user-images.githubusercontent.com/48186768/71648197-43b7a400-2cb6-11ea-9b70-ad78da076396.png)

**Comment by jspenguin2017** [comment]
Yes, that's definitely a browser bug, report to Vivaldi developers.
