### ISSUE TITLE
Not working on incognito mode of centbrowser

### ISSUE THREAD

**Issue by ts-ts** [NanoAdblocker/NanoCore#303]
NanoAdblocker is not working on incognito mode.

Windows 7 Pro 64bit
Cent Browser 4.1.7.182（Official Build） （64 bit） (portable) (Chromium 78.0.3904.108)
Nano Adblocker 1.0.0.135

**Comment by jspenguin2017** [comment]
I can confirm that it works on Chrome, Chromium, and Edge. You have to contact the developer of your browser.

**Comment by ts-ts** [comment]
I see. Thank you.
