### ISSUE TITLE
lequipe.fr 

### ISSUE THREAD

**Issue by DiaoulDu** [NanoAdblocker/NanoCore#305]
### Describe the issue (Required)
lequipe.fr does not show the same infos whether or not nano adblocker is enabled. This can be verified accessing https://www.lequipe.fr/Football/ and following the link "Voir les directs" which is supposed to give in real-time the evolution of scores during games. When nano adblocker is enabled the scores are sticky and remain updated when disabling nano adb.

### Screenshot of console (Required, press `F12` to open the console)
```
[Nano] Nano Defender Activated :: www.lequipe.fr core.js:43:24
[Nano] Excluded :: uBO-Extra rules-common.js:306:28
Échec du chargement pour l’élément <script> dont la source est « https://www.lequipe.fr/js/app.13e4c1722d20186b65d3.js ». Football:1143:1
Échec du chargement pour l’élément <script> dont la source est « https://www.lequipe.fr/js/vendors.13e4c1722d20186b65d3.js ». Football:1143:1
```

### URLs where this issue occurs (Required if applicable)

`https://www.lequipe.fr/Directs`

### Reproduction Steps (Optional if trivial)
wait till 8:30 pm in order to have games in process

### Anything else you believe to be useful (Optional)
I've tried to report to @LiCybora but unfortunately he does not answer.

#### Environment (Required)

- Operating System and Version: windows 10
- Browser and Version: FF 72.0.1
- Nano Adblocker Version: 1.0.0.134
- Nano Defender Version (Optional if you are not using it): 15.0.0.177

#### Your filter lists (Required)
standard filters only

#### Your other extensions (Required if you have any)

flagfox, don't care about cookies, Neat URL

**Comment by mapx-** [comment]
no direct match now, could you test 
`@@||cdn.by.wonderpush.com/sdk/*/wonderpush$script,domain=lequipe.fr`

**Comment by DiaoulDu** [comment]
I've installed this filter to my personal list. Unfortunately it does not work : currently without nano adblock you can see the games started with the score and with it enabled you just see that english games will start at 20:30 ...
cheers.

**Comment by mapx-** [comment]
if only the score changes real-time it's difficult to test - I was thinking the match time changes too (does not)

**Comment by DiaoulDu** [comment]
No, its easy to test
![withNanoAd](https://user-images.githubusercontent.com/8970219/72840622-edc29480-3c94-11ea-933f-b0b5056024f7.png)
![withoutNanoAd](https://user-images.githubusercontent.com/8970219/72840639-f61acf80-3c94-11ea-81b4-6b7b97f6daf0.png)

**Comment by DiaoulDu** [comment]
first png withNanoAdBlocker, second png without it (works).

**Comment by mapx-** [comment]
I tested in uBo, I get the second pic (scores in red if this is the visual difference between them)

**Comment by DiaoulDu** [comment]
yes scores in red sounds good, so you are saying that it works with uBo and does not with Nano AdBlocker ?

**Comment by mapx-** [comment]
working in uBo - default settings, I don't use nano

**Comment by DiaoulDu** [comment]
Yes true, works also for me with uBo ...
Strange.

**Comment by DiaoulDu** [comment]
Hope jspenguin2017 will take a look ...
thanx mapx-

**Comment by jspenguin2017** [comment]
Can't reproduce. You need to factory reset NA. 
![image](https://user-images.githubusercontent.com/7283682/72850887-627eda00-3c67-11ea-9ca1-2de6f2b21863.png)
![image](https://user-images.githubusercontent.com/7283682/72850897-690d5180-3c67-11ea-9be3-e27d7a6d687c.png)
