### ISSUE TITLE
[Linter] Add warning for `##^` on Chromium

### ISSUE THREAD

**Issue by DandelionSprout** [NanoAdblocker/NanoCore#306]
### Describe the issue (Required)

This may sound strange, but would it be possible to add a note à la `##^ entries will only work in Firefox.` to Nano Adblocker's syntax checker's list of syntax error notes? I am slightly embarrassed to admit it took me almost a year to figure out why I couldn't ever get any `##^` entries I had written to work in Chrome or Vivaldi.

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/22780683/73422080-13e8d400-4328-11ea-986d-3e7f0e9e50e7.png)

### Screenshot of console (Required, press `F12` to open the console)

Same as above.

### URLs where this issue occurs (Required if applicable)

`chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/dashboard.html#1p-filters.html`

### Reproduction Steps (Optional if trivial)

1) Paste `example.org##^script:has-text(exampletext)` (or `tv2.dk##^.twitter-tweet:has-text(realDonaldTrump)` if you need an example that is in actual use) into My Filters, and use the changes.
2) See that no yellow "!" triangle (nor any red "X" triangle) shows up next to the entry.

### Anything else you believe to be useful (Optional)

Nothing that I'm aware of.

#### Environment (Required)

- Operating System and Version: Windows 10 November 2019 Update
- Browser and Version: Chrome 79.0.3945.130 64-bit
- Nano Adblocker Version: 1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.180

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/22780683/73422239-94a7d000-4328-11ea-8aac-befe3024195d.png)

#### Your custom filters (Required if you have any)

`tv2.dk##^.twitter-tweet:has-text(realDonaldTrump)`

#### Your other extensions (Required if you have any)

![image](https://user-images.githubusercontent.com/22780683/73422256-a8533680-4328-11ea-9433-08b33431a329.png)

**Comment by jspenguin2017** [comment]
It will be a warning because the filter compiler accepts the filter even if HTML filtering is not supported. 

Still have to sync locale & test.

**Comment by jspenguin2017** [comment]
Actually it won't load HTML filtering rules into memory on platforms that do not support HTML filtering... I'm not sure if it should be an error or warning, I'll make it a warning for now.
