### ISSUE TITLE
Unzap element on a Nano defended site.

### ISSUE THREAD

**Issue by boywonder1971** [NanoAdblocker/NanoCore#307]
### Describe the issue (Required)
Hello there and wonderful work on this superior adblocker and anti-adblocker software .

I am not so much reporting an issue as I am adding to a wishlist of future features I guess.
Although this feature may be possible now but I have not then been able to figure out quite how to do it.  So here is my explaination.

When I am on a site the has an element that I would like to ad to the block list.  I can create it with the zapper.  Which is absolutely awesome and needed from time to time.  But I would like the ability to do the inverse if it is possible.

So for example I use a website called watchseries.  The address is listed in the url section below.
When u make a account on this website to watch my tv  you can track your shows and episodes you have already watched.  For each show there is a button on the page to track the show.  As well for each episode of the show there is a button to say you have already watched that episode.

Now I love the fact that nano blocker blocks all the ads on this page because they are killer but I find that I have to shut it down for a moment while I press either of the two buttons mentioned above to have them function as intended and then turn the adblocker back on.  It is not a horrible inconvenience but an inconvenience non the less.  So what I was hoping I would have the power to do is to have the whole page blocked as usual but have like a unzap element kind of tool where I can pick those to buttons and add them to a list. So even tho the is being ad-blocked, those buttons would function normally without having to first disable the ad-block and then click my button and the re-enable my ad-blocker. 

If this is currently an ability of the software then please forgive my ignorance because I have not been able to figure out how and crawling the web for an answer did not end fruitfully.

And If this is not currently a feature,  I humbly ask that you may consider it an add-on feature for a future release.  Thanks again so much for the great work.

Can someone please respond to me if this is currently something I can accomplish with the current software at pcperfect.windsor@gmail.com , it would be greatly appreciated.

### Screenshots (Required)
![Project1](https://user-images.githubusercontent.com/35278620/73460906-481fbd00-4347-11ea-994f-7c96c7845068.png)

### URLs where this issue occurs (Required if applicable)
https://www1.swatchseries.to/

#### Environment (Required)
- Operating System and Version:  Windows 7
- Browser and Version: Chrome version Version 79.0.3945.130 (Official Build) (64-bit)
- Nano Adblocker Version:  1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.180

**Comment by mapx-** [comment]
These are filter issues.
Test this filter, tell me if still in trouble:
`@@||swatchseries.to/set-tracked-show$xhr,1p`

**Comment by mapx-** [comment]
@ryanbr

**Comment by jspenguin2017** [comment]
You can "unzap" elements hidden by cosmetic filters with DOM Inspector. You can find it in the Logger.

**Comment by boywonder1971** [comment]
OMG me so DUH... You guys so awesome....the logger thing works like a charm...I knew there must have been a way and my ignorance was mainly cuz my mom and dad were brother and sister ;) Thanks so much do I just close this issue?  I am kind of new to github as well.

**Comment by boywonder1971** [comment]
Btw @mapx- tyvm for your input but im not quite sure how to do what you asked...could you expand on your answer a little more?  So appreciated...

**Comment by mapx-** [comment]
Just add the filter above in your "my filters" tab:

go into options - dashboard - "my filters" tab - add the filter above - click "apply changes" - test the page (refreshing it and click the buttons)

**Comment by boywonder1971** [comment]
@mapx- tyvm bro that works as well for that element.. you guys are the greatest...i wish i could help in the coding...but again me so DUH....but i can spread the word about this awesome software and already have and will continue to do so...about all i can do is that and donate so that comes next....have a great day gents

**Comment by boywonder1971** [comment]
ohh man sorry 1 other thing since the zapper was so easy to learn and felt really intuitive maybe on the same button you could make it zap/unzap and the click create or uncreate lol....wishful thinking maybe...again thanx
and should i close this issue or do you guys do that?

**Comment by mapx-** [comment]
yeah, you can close it
