### ISSUE TITLE
abpchina.org is down

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#310]
`abpchina.org`, which is the `supportURL` of `CHN: EasyList China (中文)` and `instructionURL` of `CHN: CJX's EasyList Lite` is down. 

@gorhill @okiehsch FYI.

**Comment by jspenguin2017** [comment]
Links removed from Nano Core 2 assets manifest. Closing as fixed.

**Comment by llacb47** [comment]
It's up now.

**Comment by jspenguin2017** [comment]
Yea, you're right, it's up again. However, considering they let their their forum to be suspended and they have yet to add HTTPS to their forum, I'll leave the links out of the assets manifest for now.

**Comment by jspenguin2017** [comment]
Yea, you're right, it's up again. However, considering they let their their forum to get suspended and they have yet to add proper HTTPS to their forum (HTTPS works for some pages, but not the homepage), I'll leave the links out of the assets manifest for now.
