### ISSUE TITLE
Add support for Brave adblock

### ISSUE THREAD

**Issue by leobel96** [NanoAdblocker/NanoCore#313]
Please add support for [Brave Browser](https://brave.com/)'s integrated [ad-block](https://github.com/brave/ad-block).

**Comment by jspenguin2017** [comment]
Brave's native `ad-block` module is really fast, but lack many features. I don't think it is a good replacement for uBO's network filtering engine.

**Comment by jspenguin2017** [comment]
Brave's native `ad-block` module is really fast but lack many features. So I don't think it is a good replacement for uBO's network filtering engine.
