### ISSUE TITLE
Nano filters not updating

### ISSUE THREAD

**Issue by ghajini** [NanoAdblocker/NanoCore#314]
### URLs where this issue occurs (Required)
https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt?_=0

https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt?_=0

https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt?_=0

### Screenshots (Required)
![IMG_20200317_183303](https://user-images.githubusercontent.com/20338483/76858640-d7444e00-687d-11ea-9882-81060790333d.jpg)

### Screenshot of console (Required, press `F12` to open the console)
Not possible in firefox android

### Describe the issue (Optional if obvious)

Filter lists not updating
### Reproduction Steps =
Try to update filters,update fails

### Anything else you believe to be useful (Optional)

Blocked by easylist rule  
`/^https?:\/\/.*\.(xyz|site|best|club|space|info|bid)\/.*/$xmlhttprequest,3p`
As per ubo logger

#### Environment (Required)

- Operating System and Version: android 7
- Browser and Version: firefox android stable
- Nano Adblocker Version: using ublock origin
- Nano Defender Version (Optional if you are not using it): 15.0.0.194

#### Your filter lists (Required)
the default settings+those required for nano defender to work

#### Your other extensions (Required if you have any)
Decentraleyes+nano defender

**Comment by jspenguin2017** [comment]
`chrome-extension-scheme` should be whitelisted by default. I can't reproduce the issue even if I add the filter. 
![image](https://user-images.githubusercontent.com/7283682/76866957-79d2e180-682a-11ea-9f64-29d73f2b8a97.png)

**Comment by jspenguin2017** [comment]
If this is a Firefox-specific issue, report to `LiCybora`.
