### ISSUE TITLE
Be able to Nano Defender off [FR]

### ISSUE THREAD

**Issue by VFDan** [NanoAdblocker/NanoCore#316]
Be able to turn off Nano Defender. I want to show some ads on some sites, but can't because of Nano Defender (on Firefox)

**Comment by llacb47** [comment]
Are you talking about Nano adblocker or Nano defender?

To whitelist a site in Nano adblocker, click on the extension icon and click on the power button so it is grayed out.
![image](https://user-images.githubusercontent.com/16567977/77813390-9c60c800-707e-11ea-9eaa-afa996f0bfb7.png)

**Comment by jspenguin2017** [comment]
This is explained in the FAQ: https://jspenguin2017.github.io/uBlockProtector/#common-questions-and-issues

**Comment by VFDan** [comment]
@llacb47 I was talking about Nano Defender

**Comment by VFDan** [comment]
@jspenguin2017 I don't mean whitelist, I just want to be able to turn it off and on (I can remember to turn it back on)

**Comment by jspenguin2017** [comment]
@VFDan Per domain or completely? You can turn it on and off completely in your browser's extensions manager.

**Comment by VFDan** [comment]
@jspenguin2017 Completely, and thanks
