### ISSUE TITLE
Nano Adblocker cannot view EasyList China + EasyList

### ISSUE THREAD

**Issue by Alanomn** [NanoAdblocker/NanoCore#325]
I subscribed to EasyList China + EasyList.
When I want to check this rule,
Click it, a blank page appears, reminding: "Failed to read content, please refresh",Other rules can be viewed.
![ScreenShot00330](https://user-images.githubusercontent.com/12547795/80855769-6fec2d00-8c76-11ea-9ba9-2ba64c730c94.png)
![ScreenShot00331](https://user-images.githubusercontent.com/12547795/80855777-7f6b7600-8c76-11ea-9982-8f3c1d7c04b6.png)

System: win8 64 bit
Browser: Cent Browser version 4.2.10.171 (official version) (64-bit) (portable) (Chromium 80.0.3987.163)
Nano Adblocker v1.0.0.142
EasyList China + EasyList: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

**Comment by gwarser** [comment]
`+` is not encoded to `%2b`

@gorhil

**Comment by jspenguin2017** [comment]
Fix will be available in the next release.

**Comment by Alanomn** [comment]
thank you very much
