### ISSUE TITLE
Add support denyallow

### ISSUE THREAD

**Issue by haze2422** [NanoAdblocker/NanoCore#327]
https://github.com/uBlock-user/uBO-Personal-Filters/issues/11

**Comment by jspenguin2017** [comment]
`$denyallow` is already implemented. Are you sure the filter works at all in uBlock Origin?

**Comment by jspenguin2017** [comment]
The filter behaves the same in uBO. Closing as invalid. 
![image](https://user-images.githubusercontent.com/7283682/81082002-e4f67700-8eaf-11ea-9120-4f4345afc493.png)
