### ISSUE TITLE
[Question/Suggestion?] Filter a certain inline script only 

### ISSUE THREAD

**Issue by marcussacana** [NanoAdblocker/NanoCore#328]
I'm not very good with adblock filter syntaxes, but I have a certain site with a custom anti-adblock script in the html.  

To open the site, we can block all inline scripts, but in that site we must run certain scripts blocks to the site work, And I didn't found a way to select what I want block.

If isn't there a way, why not make the nano defender block all inline scripts, then read all scripts code, filter what we don't need, and inject it in the page?  

I noticied even when I block the inline scripts, I can inject a script using extensions like `Custom JS For Websites`

Also, maybe will be cool do a simlple match and replace in the script, then we can negate simple detections.

**Comment by jspenguin2017** [comment]
Nano Defender has the ability to block or modify specific inline script with `a.beforeScript`. Note that Nano Defender cannot be programmed with adblock filter syntax, it is JavaScript only. Check the source code for more information: https://github.com/jspenguin2017/uBlockProtector/blob/d3d9603cc4c776a488521ccf952e56c56e93bcbd/src/content/core.js#L300

Note that it is been a while since I needed that, and I recommend you to simply report the issue you are facing and have a filters maintainer to take a look. You can find the Quick Issue Reporter by clicking the extension icon of Nano Defender.

**Comment by marcussacana** [comment]
@jspenguin2017 I don't wanna create a new issue only for this same case, so i'm trying ask here,
I research the documentation but I don't found any comments about how to use the beforeScript,
I take a look and the most near filter that I found is the `##script:inject` "most near" because looks like the inject function is defined in the same file...?
But when I tried write `##script:beforeScript` but looks like is wrong (the  syntax highlight stop when I try)

**Comment by llacb47** [comment]
Just open an issue here, we are happy to help you https://github.com/uBlockOrigin/uAssets

**Comment by marcussacana** [comment]
I know, I wanted learn... but forget, I will create the issue

**Comment by llacb47** [comment]
I'm not clear exactly what you want, but this might be helpful.
To "abort" an inline script: https://github.com/gorhill/uBlock/wiki/Resources-Library#acisjs-

To remove an inline script from the page source before it is loaded: https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering

**Comment by marcussacana** [comment]
I see, that's cool, thanks.

**Comment by jspenguin2017** [comment]
> how to use the beforeScript

You need to rebuild Nano Defender yourself if you wish to use `a.beforeScript`. Note that you are expected to be familiar with Chromium extensions development process if you wish to do this. 

But as I mentioned before, it is very likely that you can fix the problem without `a.beforeScript`. 

> I know, I wanted learn...

Take a look at the documentation: 
https://github.com/NanoAdblocker/NanoDoc/blob/master/en/Index.MD

And the source code: 
https://github.com/NanoAdblocker/NanoCore2
https://github.com/gorhill/uBlock

If you are committed to learn, these are the best places to start. 

> I hate fill forms

I hate filling forms too, but if you use the Quick Issue Reporter, you can submit a report with as little as 3 clicks. 

> is one of reason that I wanted learn

Learning how to fix the issues yourself would likely take longer than simply reporting the issues, even filling the forms without Quick Issue Reporter. 

This is not to discourage you to learn something new, but if your only goal is to avoid filling forms, then I highly recommend you to just use the Quick Issue Reporter.

**Comment by marcussacana** [comment]
I see, then is a disabled feature by default, Well, I know a little about write browser extension, 
Well, maybe create the issue can be more fast than rebuild everything, but how I explain, when I saw a site blocking me because of Adblocker I enter in rage, and I want defuse the shit and nothing more, One day, when I used simple adblockers that don't block in-line scripts, only to defuse a the anti-adblocker in one site I create a local proxy server that change the html content of the site requests, Instead of just disable the adblock, I lost 2 days writing that shit, it's just like me haha;
But well, thank you; I think that example that you left to me in the other issue will help me in others sites too.

**Comment by jspenguin2017** [comment]
> then is a disabled feature by default

`a.beforeScript` is enabled in Nano Defender by default. But you need to rebuild Nano Defender to customize it. But as I said, more likely than not, you will not need `a.beforeScript`. The `abort-*` script snippets are usually enough. And as you saw, your issue was fixed without `a.beforeScript`.
