### ISSUE TITLE
Revamp Dashboard with Material Design

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#33]
Any feedback on this? https://github.com/NanoAdblocker/NanoCore/issues/33#issuecomment-352323028

-----

The current dashboard is ugly and glitchy, has hard-to-access buttons, and is not mobile(Yandex)-friendly. (There could be other complications when dealing with mobile browsers, but like all Material Design libraries are responsive)
Should revamp it with clean, responsive, and modern Material Design. 

Also: 
- Make sure browser back button works
- ~~Change last section of third party filters pannel to "For your locale" and "Other locales"~~ Maybe a link to Nano Filter Store? 

 - [ ] Rework Dashboard
 - [ ] Update credits in About page

**Comment by jspenguin2017** [comment]
Also, what about a mini extension store for Nano? Where people can list filters and themes? That will make the third party page nice and tidy, and also help with building a community. 
Maybe we can even have syntax highlighting rules (like lightweight, full highlight, and everywhere in between) and more snippets resources on there.

**Comment by spectatorBH** [comment]
There's already a long standing discussion about possible UI redesign of uBlock0 to make it both more attractive and mobile-friendly (see https://github.com/gorhill/uBlock/issues/1890). Substantial work already has been done by @kazzkiq over there. Although the project seems to be put on hold now since @gorhill recently rejected a major redesign approach. So maybe you can cooperate with @kazzkiq or just pick up where he left off.

**Comment by jspenguin2017** [comment]
Great! I'll definitely keep that in mind! 
Although I'm looking at a beautiful, animated, and modern Material Design, without worrying too much about RAM usage, but I still want it fast though. Light on CPU, reasonable on RAM. 
I'm thinking of making it look like the Chrome settings page, but with always-open right-side navigation menu, and important buttons like update filters, apply, add filters on a fixed nav-bar. Also theme it pale red to fit Nano.

**Comment by jspenguin2017** [comment]
I've been wanting to remake that ugly UI for a long time, this is the next thing on my TODO list!

**Comment by jspenguin2017** [comment]
I'm thinking to only support newer browsers for the new dashboard, if the user wants, he can always switch back to the old one. 
I'm thinking of renaming the tabs: `Settings Filters Rules Whitelist Matrix About` where Filters is 3p filters, Rules is My filters, Matrix is My rules.

**Comment by jspenguin2017** [comment]
After some planning, I think we have 3 choices: 
- Go big, use Polymer
- Go for lightweight, maybe use my homegrown Paper Framework?
- Go with the existing design in that repo and style it for Nano

**Comment by jspenguin2017** [comment]
Hum, doesn't look that good... I need to think about this. 
![image](https://user-images.githubusercontent.com/7283682/34076745-643c65a8-e2ad-11e7-8246-0563ed05ec05.png)

**Comment by mat41997** [comment]
soo big it is

**Comment by jspenguin2017** [comment]
What is too big?

**Comment by mat41997** [comment]
i think you can cut this
![34076745-643c65a8-e2ad-11e7-8246-0563ed05ec05](https://user-images.githubusercontent.com/5884000/34081502-ca6489b4-e34d-11e7-8254-1f2c8ca13891.png)

**Comment by jspenguin2017** [comment]
Hum... maybe collapse it on scroll. could be hard though

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34081559-8a708f98-e30b-11e7-959f-4039c3f7cbe5.png)
![image](https://user-images.githubusercontent.com/7283682/34081564-967e467c-e30b-11e7-9df4-c760eb0df2b4.png)

**Comment by mat41997** [comment]
Great!

**Comment by mat41997** [comment]
the mobile version style is great.
i think the desktop version can be better.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34081615-e2d99fb6-e30c-11e7-9139-20378e014d78.png)

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34082045-664979e6-e314-11e7-8530-2b5baafdeaf7.png)
The 3 big buttons should be accessible now 👍

**Comment by FatOrangutan** [comment]
Curious why you swapped the positions of 'My matrix' and 'Whitelist?'

I think it makes sense to keep 'My rules' and 'My Matrix' together and to have 'Whitelist' as the last (configurable) tab on the page.

Also, not sure about renaming *3rd-party* Filters to *My* Filters.

I like the way it looks though, especially on mobile, and it is great to see that the project is open to design improvements.

**Comment by jspenguin2017** [comment]
"My rules" in uBO only works for advanced users, it is less relevant and I think "My Matrix" is a better name for it, as matrix give a sense of complexity. 
The renaming is definitely debatable, if it is named like this since the beginning of uBO, renaming to "thrid-party filters" would be equally debatable. Got to make a decision eventually, since we are doing a full remake, I'll take the chance to change the wording that I think is awkward.

**Comment by jspenguin2017** [comment]
The problem with tab bar is that it's actually really hard to use on Android, like 2 and half tabs fit on the screen, and you'll end up scrolling it a lot. I think this makes more sense. 
![image](https://user-images.githubusercontent.com/7283682/34082565-0f2be9fa-e31e-11e7-966a-a1b30112244e.png)
![image](https://user-images.githubusercontent.com/7283682/34082567-19542f50-e31e-11e7-884a-832c470f1c38.png)

**Comment by jspenguin2017** [comment]
OK, draft 5: Tab bar like before on desktop, drawer on Android.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34083736-9c886af8-e332-11e7-9d8a-47f9f4f962bd.png)

**Comment by jspenguin2017** [comment]
Maybe a bigger line spacing for Android?

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34089944-f09bb7b0-e370-11e7-9018-834a0d0cd2b3.png)
![image](https://user-images.githubusercontent.com/7283682/34089950-f9b74bde-e370-11e7-9ddf-f51a4006fbbb.png)
![image](https://user-images.githubusercontent.com/7283682/34089961-fef32b9a-e370-11e7-990c-a6b0597561a1.png)

**Comment by mat41997** [comment]
the filters homepage button, where is?

**Comment by jspenguin2017** [comment]
Some settings will be moved, update filters is moved to settings tab and enforcing cosmetic filter will be moved to advanced tab. 
![image](https://user-images.githubusercontent.com/7283682/34187972-38c27534-e4f1-11e7-921f-1049eadda256.png)

**Comment by elypter** [comment]
it would be cool if this would become a reusable library that can be adopted by other extensions or usescripts

**Comment by jspenguin2017** [comment]
The "reusable library" is called Material Design Lite.

**Comment by jspenguin2017** [comment]
The buttons are kind of hard to access on desktop, I'll add shortcut keys for desktop (like `Ctrl+S` for save), for Android, they should be pretty easy to access. 
I'll put this on hold for now because it is taking lots of time, and I don't want to keep other features waiting for too long.
