### ISSUE TITLE
Using Nano Defender to keep universal bypass undetected

### ISSUE THREAD

**Issue by slimpython** [NanoAdblocker/NanoCore#332]
Universal Bypass is an open-source addon which automatically skips annoying link shorteners - https://addons.mozilla.org/en-US/firefox/addon/universal-bypass/

There are some sites like this https://imgur.com/a/s53NUDr which detects it.

**Comment by jspenguin2017** [comment]
That is out of scope. 

As for the specific case, see: https://github.com/NanoAdblocker/NanoFilters/issues/483
