### ISSUE TITLE
[Suggestion] Trigger the execution of userscripts in a similar way as scriptlets

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoCore#34]
I dont know if it is possible to access other browser extensions in away that you could remotely activate userscripts from greasemonkey, tampermonkey or violentmonkey but if possible it would open many opportunities. this would make it much easier to maintain and distribute scriptlets and it would connect two large developer communities. i hope this is not something that got prohobited with firefox 57.

**Comment by jspenguin2017** [comment]
We would need collaboration from them. Nano Defender can alter Nano Adblocker's settings only because Nano Adblocker explicitly allow that.

**Comment by jspenguin2017** [comment]
Those Userscript engines have their own path matching logic, I don't see when would this be needed.

**Comment by elypter** [comment]
there are many scripts that match all website because they do something generic. however they might break something on some sites, are useful depending on content but not tied to a small set of websites, depend on user preference... you could include a huge list of domains in the userscript and try to keep them updated but this doesnt scale very well and there is also no way to switch them on/off in any gui and even if there was then you would have to store that information in a separate file because otherwise it would be overwritten on every update. managing these sorts of problems is the perfect regime for a filterlist based adblocker.

**Comment by jspenguin2017** [comment]
> but this doesnt scale very well

It's up to Userscript manager to optimize that. 

> there is also no way to switch them on/off in any gui

Userscript managers definitely have place to add user-defined white/black list, either way, it's up to Userscript managers to implement an accessible UI. 

Userscript managers can very well carry a efficient filtering engine with them.

**Comment by jspenguin2017** [comment]
It sounds like you should fork an Userscript manager and improve it. 

I personally don't use Userscript, I have all special logics I need packed in one personal extension, it is way more powerful than Userscript and way more reliable too.

**Comment by jspenguin2017** [comment]
I don't thinks this is something Nano should worry about, if Userscript managers don't work well, it's their developer's job to improve them.
