### ISSUE TITLE
[Feature Request] Protect Nano Adblocker With Password

### ISSUE THREAD

**Issue by pc-v2** [NanoAdblocker/NanoCore#345]
### Describe the issue (Required)
i want a feature that secure nano adblocker with password, since i also use this to block certain websites, like porn for example, so my family can't access it

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/58063311/84359483-e9baf300-abf2-11ea-9b94-e16069177087.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/58063311/84359560-022b0d80-abf3-11ea-8445-2e8536b3d622.png)

### URLs where this issue occurs (Required if applicable)
-

### Anything else you believe to be useful (Optional)
-

#### Environment (Required)

- Operating System and Version:  Windows 10 May 2020
- Browser and Version: Mozilla Firefox 77
- Nano Adblocker Version: Nano Adblocker v1.0.0.148
- Nano Defender Version (Optional if you are not using it): -

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/58063311/84359805-5afaa600-abf3-11ea-8255-f23e921161a1.png)

#### Your custom filters (Required if you have any)
https://block.energized.pro/porn/formats/domains.txt

#### Your other extensions (Required if you have any)
-

**Comment by llacb47** [comment]
For your application it's probably better to use pihole.

**Comment by jspenguin2017** [comment]
You should use browser policies instead: 
https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

Unless an extension is force installed via browser policy, it is always possible to uninstall it via the right click context menu, so having a password to protect the settings is not going to help.
