### ISSUE TITLE
Question : do we need to enable “Nano Defender Integration” ?

### ISSUE THREAD

**Issue by freMea** [NanoAdblocker/NanoCore#346]
#### Environment (Required)

- Operating System and Version: Windows 10 1909 pro
- Browser and Version: Vivaldi 3.1.1929.29 (builtin adblocker disabled)
- **Nano Adblocker** Version: 1.0.0.149
- Nano Defender Version: 15.0.0.200

It is stated in the installation page of **Nano Defender** that some extra steps are needed for **uBlockOrigin**. I see the need of enabling _Nano Defender Integration_ list. But nothing is said about if we do need to enable this list in **Nano Adblocker**. The fact that the list exists in it let me think we do.

**Comment by llacb47** [comment]
Yes, it's for integration with Nano Defender.

**Comment by jspenguin2017** [comment]
Nano Defender will automatically enable the list for you. This is tested and confirmed to be working on Chrome, Chromium, and Edge. If it does not work on your browser, you need to enable the list manually in the dashboard.
