### ISSUE TITLE
Nano adblocker causes CPU spike under certain conditions

### ISSUE THREAD

**Issue by llacb47** [NanoAdblocker/NanoCore#348]
### Describe the issue (Required)
Nano adblocker causes Chrome devtools to lag and eat CPU under certain conditions.

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/16567977/86490444-68f4a000-bd35-11ea-9d20-cf707618fd95.png)

### Screenshot of console (Required, press `F12` to open the console)
It's empty

### URLs where this issue occurs (Required if applicable)
`http://example.com`

### Reproduction Steps (Optional if trivial)

1. Add `example.com##*` to my filters
2. Visit `http://example.com`
3. Open devtools

### Anything else you believe to be useful (Optional)

Nano Adblocker adds `display: none!important` as an inline style over and over on the html tag on any site where a filter of type `example.com##*` is applied.

Cannot reproduce CPU spike in uBo or Nano firefox.

#### Environment (Required)

- Operating System and Version: Windows 10 1909
- Browser and Version: Chrome 83.0.4103.116
- Nano Adblocker Version: 1.0.0.149
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

N/A
#### Your custom filters (Required if you have any)

N/A
#### Your other extensions (Required if you have any)
N/A

**Comment by jspenguin2017** [comment]
Hum... Looks like a bug with the pseudo UserCSS engine. 

@gorhill are you still maintaining the pseudo UserCSS engine?

**Comment by gorhill** [comment]
Not really, I really hope to drop it sooner than later. Does Chromium-based Edge support user styles?

If it's for the older Edge, I don't mind a trivial (hopefully) fix.

**Comment by gorhill** [comment]
Frankly I think it's probably best to just drop pseudo user styles and fall back on using `insertCSS()` without the `cssOrigin` parameter, it's not worth maintaining a not trivial code base which is meant for pre-Chromium 63. The only consequence is that whoever uses old versions of Chromium may not have their cosmetic filters being enforced.

**Comment by gorhill** [comment]
Trivially fixed with <https://github.com/gorhill/uBlock/commit/a5ba668c382a3be0ba41ce0f0a69ebb090c260a5>.

Though I will still drop support of the pseudo version in next release.

**Comment by jspenguin2017** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1101473
