### ISSUE TITLE
Custom Lists Are Automatically Added

### ISSUE THREAD

**Issue by det427** [NanoAdblocker/NanoCore#353]
### Describe the issue (Required)
Custom Lists Are Automatically Added

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/32418037/87310022-35064100-c4d2-11ea-87c3-b56fb125ad2d.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/32418037/87310083-4c452e80-c4d2-11ea-9e26-ac4f11d70d2f.png)

### Reproduction Steps (Optional if trivial)
These list were populated without any intervention by me. How/why do these list just show up? Does your program automatically add these lists? If not should I be worried?

#### Environment (Required)

- Operating System and Version: Windows 10 Pro Version 2004
- Browser and Version: Chrome 83.0.4103.116 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.151
- Nano Defender Version (Optional if you are not using it): 15.0.0.201

#### Your filter lists (Required)
![image](https://user-images.githubusercontent.com/32418037/87311232-d4780380-c4d3-11ea-9720-67b51596c777.png)

List filters you have enabled or disabled from the default settings.
-->Enabled Fanboy's Annoyance

#### Your custom filters (Required if you have any)
![image](https://user-images.githubusercontent.com/32418037/87310860-63d0e700-c4d3-11ea-91bb-90d8aade3851.png)

#### Your other extensions (Required if you have any)
Nano Defender, Google Translate, and Honey

**Comment by llacb47** [comment]
You probably added the Honey one. Remove it, it's bad.

Those malware lists are not included in the stock configuration anymore and have been moved to custom section.

**Comment by jspenguin2017** [comment]
Nano never adds custom lists for you, however, it sometimes moves lists in the assets manifest (non-custom lists) to custom lists. If you are unsure why you have custom lists, you should remove them.
