### ISSUE TITLE
Filter Names

### ISSUE THREAD

**Issue by Solarie01** [NanoAdblocker/NanoCore#357]
Hello! I would like to make a simple suggestion! Would it be possible for you to make Nano read the name of the filter lists like the ones in the example below?
![image](https://user-images.githubusercontent.com/70236331/91227939-c685e700-e6fd-11ea-981a-c55b8a49ed6e.png)

**Comment by jspenguin2017** [comment]
See the docs here: https://github.com/NanoAdblocker/NanoDoc/blob/master/en/FilterListAuthoring.MD#-title-title-or--title-title

**Comment by jspenguin2017** [comment]
Also I recommend Nano Defender instead of AAK.
