### ISSUE TITLE
Can't update or add filters

### ISSUE THREAD

**Issue by Grithz** [NanoAdblocker/NanoCore#358]
### Describe the issue (Required)
Can't update and add filters on Google Chrome. I can update and add filters in other browsers while using the same extensions.

### Screenshots (Required)
[https://hizliresim.com/353wEj](https://hizliresim.com/353wEj)
[https://hizliresim.com/xzH5l9](https://hizliresim.com/xzH5l9)
[https://hizliresim.com/7gvtft](https://hizliresim.com/7gvtft)
[https://hizliresim.com/z4KMom](https://hizliresim.com/z4KMom)
[https://hizliresim.com/U8vo6F](https://hizliresim.com/U8vo6F)
### Screenshot of console (Required, press `F12` to open the console)
[https://hizliresim.com/kmR9tJ](https://hizliresim.com/kmR9tJ)
### URLs where this issue occurs (Required if applicable)
[chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/dashboard.html#3p-filters.html](chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/dashboard.html#3p-filters.html)

#### Environment (Required)

- Operating System and Version: Windows 10 64 bit
- Browser and Version: 85.0.4183.102 64 bit
- Nano Adblocker Version: 1.0.0.153
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

#### Your filter lists (Required)
my nano backup: [https://yadi.sk/d/oI6LWn-3TMKrIQ](https://yadi.sk/d/oI6LWn-3TMKrIQ)
List filters you have enabled or disabled from the default settings.
Stated above

#### Your custom filters (Required if you have any)
stated above

#### Your other extensions (Required if you have any)
Other extensions work fine with Nano in other browsers.

**Comment by jspenguin2017** [comment]
I can't reproduce, it works fine for me. Try reinstalling your browser and extensions.

**Comment by Grithz** [comment]
> I can't reproduce, it works fine for me. Try reinstalling your browser and extensions.

I will try. I will inform you if it gets solved.

**Comment by Grithz** [comment]
> I can't reproduce, it works fine for me. Try reinstalling your browser and extensions.

Nano was blocking its own updates. I normally have 3p blocked. I disabled Nano for its own extension page and the updates started working.

**Comment by jspenguin2017** [comment]
`chrome-extension-scheme` should be already whitelisted by default.
