### ISSUE TITLE
open in new tab

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#36]
*Question 1.*
![2017-12-14 06_26_02-nano filter viewer](https://user-images.githubusercontent.com/5884000/33976868-0a521c98-e098-11e7-89c9-a4394c150ac1.png)

i don't see option "open in new tab" or "search in google" how do i can open this link in new tab?

to reproduct
* open a random filter list

*Question 2.*
![2017-12-14 06_34_22-nano filter viewer](https://user-images.githubusercontent.com/5884000/33976998-ebaf4b20-e098-11e7-9e31-77158dee7694.png)
double click not selected a link

---

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by jspenguin2017** [comment]
Oh man, that's really hard to do...

**Comment by LuaTenshi** [comment]
Regex urls and wrap with <a></a>?

**Comment by jspenguin2017** [comment]
Can you show some code example? I'm not sure what you mean.

**Comment by jspenguin2017** [comment]
For open in tab, you can just drag it onto the tab bar. 
I'll see if I can fix double click behavior. Merged into https://github.com/NanoAdblocker/NanoCore/issues/15
