### ISSUE TITLE
These custom filters don't work now in Facebook's NEW UI.

### ISSUE THREAD

**Issue by Shnxxx** [NanoAdblocker/NanoCore#360]
### Describe the issue (Required)
```
/^https?\:\/\/\d+-edge-chat\.(facebook|messenger)\.com\/?/$xmlhttprequest
/^https?\:\/\/\d+-edge-chat\.(facebook|messenger)\.com\/pull\?.*state=offline/$xmlhttprequest

https://www.facebook.com/ajax/mercury/change_read_status.php$xmlhttprequest
https://www.facebook.com/ajax/messaging/typ.php
https://www.messenger.com/ajax/mercury/change_read_status.php$xmlhttprequest
https://www.messenger.com/ajax/messaging/typ.php
```

These filters don't work properly on the new Facebook UI.
In the *OLD UI*, what these filters do is that it prevents the other people to notify them if I am "*Available*", if their message was "*Delivered*", or "*Seen*". Their messages to me will be just labeled as "*Sent*" no matter what. Even if I opened their message and started typing without sending it.

With the *NEW UI*, these filters don't work anymore.

Any help will much be appreciated!

### Screenshots (Required)
**ACCOUNT 1**
I tried sending a message to my dummy account. And it was labeled as "Delivered" immediately.
![image](https://user-images.githubusercontent.com/48496678/93710561-5f334980-fb7a-11ea-9b56-e01a1c7b27fc.png)

**ACCOUNT 2**
Here you could see that I am not opening yet the message.
![image](https://user-images.githubusercontent.com/48496678/93710626-bd602c80-fb7a-11ea-8d35-f08681842cf7.png)

When I open it using the **ACCOUNT 2**,  and go back to **ACCOUNT 1**, it is labeled as "Seen". 
![image](https://user-images.githubusercontent.com/48496678/93710711-44ada000-fb7b-11ea-8cde-c3e83780951b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/48496678/93710777-a79f3700-fb7b-11ea-8f3c-634ea889212c.png)

### URLs where this issue occurs (Required if applicable)
Facebook.com
Messenger.com

### Reproduction Steps (Optional if trivial)

1. Copy the said filters to the "My Filters" under nanoAdblocker options.
2. Send a message to one of your other accounts (dummy or anything)
3. Just open that other account.
4. Go back to the account that you used to send that message and you will see that it is labeled as "Delivered" already. 
5. And when you open it using the other account, and when you go back to the account that you used to send the message, it will be labeled as "Seen".

#### Environment (Required)

- Operating System and Version:  Windows 10 v2004 19041.508
- Browser and Version: Brave (Chromium-based)
- Nano Adblocker Version: v1.0.0.153
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/48496678/93710922-bfc38600-fb7c-11ea-9763-4c9258ea80b7.png)
![image](https://user-images.githubusercontent.com/48496678/93710928-d1a52900-fb7c-11ea-9ec3-c6ea30e13dfd.png)
![image](https://user-images.githubusercontent.com/48496678/93710940-e4b7f900-fb7c-11ea-8e06-ac583a9797e1.png)
![image](https://user-images.githubusercontent.com/48496678/93710950-eed9f780-fb7c-11ea-90c3-46c62ed21acd.png)

#### Your custom filters (Required if you have any)
```
/^https?\:\/\/\d+-edge-chat\.(facebook|messenger)\.com\/?/$xmlhttprequest
/^https?\:\/\/\d+-edge-chat\.(facebook|messenger)\.com\/pull\?.*state=offline/$xmlhttprequest

https://www.facebook.com/ajax/mercury/change_read_status.php$xmlhttprequest
https://www.facebook.com/ajax/messaging/typ.php
https://www.messenger.com/ajax/mercury/change_read_status.php$xmlhttprequest
https://www.messenger.com/ajax/messaging/typ.php
```

#### Your other extensions (Required if you have any)

![image](https://user-images.githubusercontent.com/48496678/93710973-15982e00-fb7d-11ea-8655-3b281103715e.png)

**Comment by jspenguin2017** [comment]
It's up to you to update your custom filters.
