### ISSUE TITLE
Does Nano Adblocker allow hosts to make revenue?

### ISSUE THREAD

**Issue by Danielilson** [NanoAdblocker/NanoCore#361]
This is more of a question but I couldn't find a FAQ section. Does nano adblocker completely stol ads from executing on my browser, or does it just stop me from seeing them, whilst allowing the site host to make revenue? 
Thanks.

**Comment by jspenguin2017** [comment]
Some ads are blocked with network filters (not loaded at all) and some are simply hidden. You can easily whitelist websites you want to support through the extension popup panel (click the extension icon to bring it up). 

You may also find this project interesting: https://github.com/dhowe/AdNauseam

**Comment by jspenguin2017** [comment]
Some ads are blocked with network filters (not loaded at all) and some are simply hidden. Depending on how each website implemented their ads, they may or may not be able to make money from ads impressions. However, you can easily whitelist websites you want to support through the extension popup panel (click the extension icon to bring it up). 

You may also find this project interesting: https://github.com/dhowe/AdNauseam

**Comment by jspenguin2017** [comment]
Some ads are blocked with network filters (not loaded at all), and some are simply hidden. Depending on how each website implemented their ads, they may or may not be able to make money from hidden ads. Note that you can easily whitelist websites you want to support through the extension popup panel (click the extension icon to bring it up). 

You may also find this project interesting: https://github.com/dhowe/AdNauseam

**Comment by Danielilson** [comment]
I see. Could you please explain how to whitelist a site? And is it possible to allow certain ads to run like the panel ads that you can click, but stop the intrusive in-video ads that you can't skip? I'm talking about Crunchy roll here, if you're familiar. I don't even know if they make money from those..

**Comment by jspenguin2017** [comment]
To whitelist a site: 
https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button

To allow only certain ads: 
This is hard, you have to use the Logger to figure out which requests should be allowed, you can learn more here: https://github.com/gorhill/uBlock/wiki/The-logger

I think Crunchyroll bakes their ads into the video stream, were you able to block their video ads?

**Comment by Danielilson** [comment]
Yes, I think they plug in the ads into the stream. Nano was able to block these in-video ads, which is what I wanted

There are still some panel ads though, which I don't mind.
________________________________
