### ISSUE TITLE
[Enhancement] Pinging site rules in filter list page

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#37]
to check this site rule is it available or broken

example.
![2017-12-14 08_54_36-nano filter viewer](https://user-images.githubusercontent.com/5884000/33981345-ca6daa2e-e0ac-11e7-9079-2b0e68273f5f.png)

i can't find any tool to check for availability the website

---

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by jspenguin2017** [comment]
Yes, that is a good idea, although how to implement that is a whole other story.

**Comment by LuaTenshi** [comment]
Found this ( https://jsfiddle.net/GSSCD/203/ ) fiddle thought it may help, it pretty much tries to load the website as an invisible image and is able to see if the site is responsive like that. (Although that could have some other issues such as privacy etc.)

**Comment by jspenguin2017** [comment]
The problem is not pinging the website, it's how to integrate that into the editor.

**Comment by jspenguin2017** [comment]
I don't see much point in implementing a pinging system. If you want to see if that website is up, double click to select it, and drag it to the tabs bar to open it. If you need mass scanning, you should use a native script, which gives you way more control and flexibility.

**Comment by elypter** [comment]
this is something for a server side list manager like what filterlists.com intends to become.

**Comment by jspenguin2017** [comment]
I don't think it's a good idea to give them too much power. Being able to remove any rules they like from filter lists is too much authority. 

I think a tool to quickly lookup which domains are no longer resolvable is a good idea. Although there are catches where `ads.example.com` resolves but `example.com` doesn't. 

Sending test requests will likely to not work from servers, as it's rather easy to know which request comes from data centers. I guess distributing the task isn't a bad idea, but that's for another (native) app or extension.
