### ISSUE TITLE
[Enhancement] Special injector for whitelist

### ISSUE THREAD

**Issue by mat41997** [NanoAdblocker/NanoCore#38]
Example i have a specific channel on youtube, and i don't want blocks ads on this channel.

or i be want unblock a ad in ad

that is a most simple solution to users

**Comment by jspenguin2017** [comment]
There are Userscripts for this, I probably won't add it to Nano.

**Comment by jspenguin2017** [comment]
There is no easy way to unblock just one ad, as I have no way what the ad depend on (which script, which element etc). 
For YouTube, I will not put special feature just for one website.

**Comment by KonoromiHimaries** [comment]
![getadblock](https://user-images.githubusercontent.com/5884000/39003972-5896b72a-43fc-11e8-9f49-c15ac69095bb.png)
`https://blog.getadblock.com/how-to-block-youtube-ads-with-adblock-c1bf528d9536`

adblock has added this functionality

**Comment by jspenguin2017** [comment]
> For YouTube, I will not put special feature just for one website.
