### ISSUE TITLE
userResourcesLocation advanced setting

### ISSUE THREAD

**Issue by lewisje** [NanoAdblocker/NanoCore#42]
### Describe the issue (Required)
I looked through the diffs between this extension and uBlock Origin to see whether the advanced setting `userResourcesLocation` would do anything, or would just be overridden by the built-in resources in Nano Adblocker; it seems as if the former is true (that if that advanced setting points to a URL, then Nano Adblocker loads the uBlock Origin resources, the additional Nano Adblocker resources, and finally the resources from the custom location), but I would like confirmation that this behavior is intended.

### Screenshots (Required)
![nanoadblockerresources](https://user-images.githubusercontent.com/4865237/34024001-dcfabd58-e115-11e7-899e-ffb756e2935a.png)

### Environment (Required)

- Operating System and Version: Windows 10 Version 1709 x64
- Browser and Version: Chrome Stable 63.0.3239.108 x64
- Nano Adblocker Version: 1.0.0.13

#### Your filter lists (Required)
(Is this really required when the question is just about how something else entirely works?)

**Comment by jspenguin2017** [comment]
Nano will load: 
uBO Resources -> Nano Extra -> User Resources

Name collision will cause last entry to override previous ones. 
Nano does not take over that settings, it is handled properly.
