### ISSUE TITLE
Cryptocurrency (Bitcoin) Mining Protection List 

### ISSUE THREAD

**Issue by xqk94524** [NanoAdblocker/NanoCore#48]
the [Cryptocurrency (Bitcoin) Mining Protection List](https://cdn.adblockcdn.com/filters/nominers.txt), is one of the optional lists disponible for [Adblock](https://getadblock.com/).

looks interesting for incorporate at Nano filters

**Comment by jspenguin2017** [comment]
I think Resource Abuse list covers most of it...

**Comment by xqk94524** [comment]
I saw now, this filter is most covered by others, is redundant
