### ISSUE TITLE
Add unload warning when there are unsaved change

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#5]
Use `beforeunload` event to warn user about unsaved changes. 

Upstream: https://github.com/gorhill/uBlock/issues/3271

**Comment by jspenguin2017** [comment]
A proper system is being implemented in the new dashboard.

**Comment by KonoromiHimaries** [comment]
i think the save session `asynch` can be better solution at this.
+ button restart to before
+ save edit in real time

**Comment by jspenguin2017** [comment]
Like hot exit?

**Comment by jspenguin2017** [comment]
I won't make hot exit, as if I leave without saving, I expect it to not save. 
Maybe we can add an option for that in the future, because the nature of the dashboard (you expect what it shows is what is actually applied), chances are I will only add unload warning, but not hot exit.

**Comment by jspenguin2017** [comment]
This landed in new dashboard, need to back-port to old one.

**Comment by jspenguin2017** [comment]
Landed in Nano Core 2.
