### ISSUE TITLE
Unofficial Nano Adblocker on AMO

### ISSUE THREAD

**Issue by FatOrangutan** [NanoAdblocker/NanoCore#53]
https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker/

From the same person as the unofficial Nano Defender.

**Comment by jspenguin2017** [comment]
I'm not too worried, as unchanged, it violates AMO's policy, should be taken down soon.

**Comment by jspenguin2017** [comment]
Well, he did accomplish one thing... I'll get an official version up.

**Comment by jspenguin2017** [comment]
OK, I have an official version up: https://addons.mozilla.org/en-US/firefox/addon/real-nano-adblocker/

**Comment by jspenguin2017** [comment]
Actually, I just re-checked the code, the remote code fetching flag is set properly, apparently the logic is in the Chromium vAPI script.

**Comment by Salin1810** [comment]
Now, he was removed https://addons.mozilla.org/en-US/firefox/addon/nano-adblocker/

**Comment by jspenguin2017** [comment]
OK, good.
