### ISSUE TITLE
[Enhancement] Select filters profile

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#56]
i use a many filters list in my dashboards

and i don't have a time to deselect all of this filters list in the dashboard

i think the profile selector is the best solution of the i have

example.
![2017-12-22 09_13_42-](https://user-images.githubusercontent.com/5884000/34290616-c2983524-e6f8-11e7-937d-149e14bcdb90.png)

like this design
![selrolemodule](https://user-images.githubusercontent.com/5884000/34291863-9d19f53e-e6fe-11e7-932a-7b8c67016f6a.png)

**Comment by jspenguin2017** [comment]
Eh... You got good ideas, but they are all so freaking hard to implement...

**Comment by jspenguin2017** [comment]
I think you should use browser profile if you need this.

**Comment by KonoromiHimaries** [comment]
you can unchek all of this filters 5-6 times in one hour every day?
![ublock-origin-blocklists](https://user-images.githubusercontent.com/5884000/34753413-1215fb5e-f5b8-11e7-8400-70f2852db833.png)

**Comment by jspenguin2017** [comment]
You shouldn't need to swap them a lot, if you do find yourself regularly doing so, the browser profile can solve the issue. 
I'm still considering this one, a per-domain profile is probably not going to happen, no decision for general profile yet. I'll think about this.

**Comment by elypter** [comment]
i would prefer collapsible groups so you don't run out of vertical space so easily.

**Comment by jspenguin2017** [comment]
That would still not fit in the popup. Groups can be collapsed in the third party filters panel.

**Comment by Ravizz** [comment]
> @KonoromiHimaries : deselect all of this filters list in the dashboard
> @jspenguin2017 : the browser profile can solve the issue.

Another way is just to simply use backups in Settings pane: 
- create several backups before, each with custom lists, save each to different txt file using "Create backup" button 
- and then just switch between backups at any moment using "Restore backup" button
