### ISSUE TITLE
[feature suggestion] Allow usage on the new tab page on firefox

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoCore#59]
there are a few elements that are rather annoying and i would like to delete them but the picker doesnt show up

**Comment by jspenguin2017** [comment]
New tab page is protected and no extension can alter it, I think you can completely replace the page, but not change it. It's another BS security that Mozilla put in. You can't block the tracking script on AMO neither, that page is protected too. Oh, and it's a third party (Google) tracking script.

**Comment by elypter** [comment]
thats unfortunate but thanks for considering. i guess, thanks, mozilla!
