### ISSUE TITLE
[Feature request] Option to disregard all exception filters in filter lists

### ISSUE THREAD

**Issue by sebast889** [NanoAdblocker/NanoCore#61]
I asked about this to be in uBO but gorhill is hesitant to add it in uBO. I just came across your fork and has some pretty good upgrades here from what I can see is unavailable in uBO. I am wondering if you are willing to add this feature in NanoAdblocker. It can be a very useful way for users to be able to choose whether they want to use only the block filters and not the whitelist filters that can let through ads/tracking scripts. There is more info and discussion about the reasons for a feature like this here: https://github.com/gorhill/uBlock/issues/3353

**Comment by jspenguin2017** [comment]
It's not hard to do, but this can break things really badly.

**Comment by sebast889** [comment]
It can cause breakage but it's never a default option and the user must go out of their way to enable/toggle it so I don't think that's a problem. Maybe a way so this option can only be used when 'I am an advanced user' is ticked.

**Comment by elypter** [comment]
if the maintainer of a single filterlist wants to break things then he easily can already. if many filterlists are bundled in a metalist then it would be a lot saver if the maintainer checks the list regularly. if one of the lists becomes malicious he can remove it quickly. that would drastically reduce the risk because now not any of the lists can fuck things up but only the metalist maintainer.

**Comment by jspenguin2017** [comment]
I think it'll be a pain to implement it correctly, just a global whitelist toggle is not hard.

**Comment by sebast889** [comment]
Ideally a per-filter option like a small icon/toggle button next each filter list name would be best. But if that's not possible I still think a global disable whitelisted filters option (excluding the whitelisted filters created by the user) is still useful.

**Comment by jspenguin2017** [comment]
It's not impossible, but hard, and there are more features that are more useful that I want to implement.

**Comment by sebast889** [comment]
Ok sure, then it's probably best to focus on the more important features first and then come back to this. I don't think this feature is needed urgently or anything but it would be nice to see this implemented.

**Comment by jspenguin2017** [comment]
I need compile flag for other features too, one more flag doesn't change anything. 
It will be a global flag though, so when turned on, it affects all filter lists except `My filters`. 
I think maybe 3 people will be using that feature, so a per-list switch is probably never going to happen.

**Comment by jspenguin2017** [comment]
Hi, this landed in commit 7a0da35964f04e53fa608205f12b9e9fc8a0f93a, can you test? 

A pre-compiled binary is attached here if you don't want to build it yourself: 
[Nano_Chromium.zip](https://github.com/NanoAdblocker/NanoCore/files/1587974/Nano_Chromium.zip)

**Comment by jspenguin2017** [comment]
Changes: https://github.com/NanoAdblocker/NanoCore/pull/67/files

**Comment by jspenguin2017** [comment]
I did some testing, seems to work, marked as fixed unless you have further concerns.

**Comment by sebast889** [comment]
Away from home right now but just tested your build on a site and it works well :) Only thing is it is hard to differentiate between the actual block filters and the whitelisted filters that show up as block filters. Is it possible to show some kind of indicator that this is blocked because of the whitelist toggle? Maybe to add "_nanoIgnoreThirdPartyWhitelist" to the filter origin (when you click the URL in the logger to show which filter list a filter is from)?

Other than that, it's working as expected and I'll be testing it more over the next week, nice work @jspenguin2017!
