### ISSUE TITLE
[suggestion] Change the color of the ON/OFF button to something different

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoCore#62]
this would make it more obvious to people that they are using a different addon than ublock and give the changes in the fork some visual reference. even if it is just a color change this would make it quite recognizable and make it feel different.

**Comment by jspenguin2017** [comment]
Yea, I probably will change it to a list buttons like every other adblocker. Not a priority for now.

**Comment by jspenguin2017** [comment]
The extension icon is really different, and the black bar above the button says Nano Adblocker, I think it's obvious enough. I *might* change the popup in the future, but no plan for now as uBO's popup works pretty well.
