### ISSUE TITLE
Few questions about Nano Adblocker.

### ISSUE THREAD

**Issue by Piter432** [NanoAdblocker/NanoCore#63]
I have few questions about Nano Adblocker:

1. I'm using uBO-Extra & uBO-Scope with uBO. Do I need to disable one of this uBO's additional extensions to make Nano Adblocker work properly?
2. Will you bring back the old way to manage custom filters lists? I hate the new way introduced in uBO 1.11.0.
3. In "My filters" tab there's this: "Nano Adblocker comes with two sets of resources: uBlock Origin Resources and Nano Adblocker Extra Resources". Is this mean that uBO comes by default with its resources in .txt file or do I need to add the uBO's resources in .txt file to uBO's advanced settings, 'cause I'm not sure if adding it there was good idea :/
4. How's with VIVALDI support? Is there no bugs or glitches specific for VIVALDI? I'm asking, 'cause I'm going to move to VIVALDI from chrome, when VIVALDI Sync will be ready for its stable release (1.14).

Thanks for any reply 😃

**Comment by jspenguin2017** [comment]
1. You can still use uBO-Scope, Nano Defender replaces uBO-Extra. 
2. I'm not sure what is the old way, do you still have a screenshot? 
3. uBO only have its own resource file built in, where Nano has a few extra resources. No action needed, everything is coded in. If you want to use Nano's resources in uBO, then you need to use advanced settings to load that. 
4. I don't know, never tried that.

**Comment by Piter432** [comment]
1. If I remember correctly, uBO-Extra has IL defuser. I understood that Nano Defender has it also?
2. I took screenshot just now, but I remember how it worked. Maybe you will now remind something: 
![2017-12-24 22 35 43 ubo 1 10 0](https://user-images.githubusercontent.com/5713816/34329375-b08527fa-e8fd-11e7-8b14-dc1395b4499e.png)

Btw. I see you've forked uBlockProtector repo, I suppose the fork is the new home for Nano Defender, right?

**Comment by jspenguin2017** [comment]
1. Yes. 
2. Eh... Probably won't fix in favor of Nano's new dashboard.

**Comment by jspenguin2017** [comment]
The new Nano Defender repository is for Firefox build.

**Comment by Piter432** [comment]
> 2. Eh... Probably wontfix in favor of Nano's new dashboard.

Easy, I'm just asking 😉 If you need to focus on new dashboard, don't worry, do your best 🙂
