### ISSUE TITLE
script:inject with only negated domains cause cosmetic filtering engine to crash

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#68]
Tracking issue for Nano, upstream: https://github.com/gorhill/uBlock/issues/3375

**Comment by Piter432** [comment]
Looks like it's fixed 😛

**Comment by jspenguin2017** [comment]
Yea, it's fixed upstream, but I'm too scared to pull the update.

**Comment by Piter432** [comment]
Why?

**Comment by jspenguin2017** [comment]
I think the update will break more than it fixes.

**Comment by jspenguin2017** [comment]
Marking as fixed as I will be pulling upstream change soon.
