### ISSUE TITLE
[Firefox] Extension pages do not get the NanoAdblocker favicon

### ISSUE THREAD

**Issue by FatOrangutan** [NanoAdblocker/NanoCore#71]
### Describe the issue (Required)
E.g. https://github.com/NanoAdblocker/NanoCore/blob/master/src/dashboard.html#L9 sets favicon as img/icon_16.png. This file doesn't exist. Similar issues with [logger](https://github.com/NanoAdblocker/NanoCore/blob/master/src/logger-ui.html#L8) etc.

### Screenshots (Required)
![capture](https://user-images.githubusercontent.com/8336638/34401448-67d02ade-ebc1-11e7-9d6b-ed3908fa9d5f.PNG)

**Comment by jspenguin2017** [comment]
Forgot to test that on Firefox, works properly on Chrome though.
