### ISSUE TITLE
`localhost##` causes an error to be logged to the background console

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#77]
Also need to investigate: 
```
localhost#?# - Compiled to FilterPlainPrefix0
localhost#^# - Compiled to FilterGeneric

localhost#$# - Filter discarded
localhost##^ - Filter discarded
```

Compiled data: 
![image](https://user-images.githubusercontent.com/7283682/34473475-69ff0b46-ef30-11e7-880e-7f8e0db4ca7c.png)
```
[0,102957015971486,[2,"localhost#?#"]]
/* end of network - start of cosmetic */

```
```
[0,102957015971486,[9,"localhost#^#",0]]
/* end of network - start of cosmetic */

```

**Comment by jspenguin2017** [comment]
cc @gorhill 
I'm not sure if this is intended behavior, but `localhost##` is not flagged as invalid by cosmetic filter parser seems to be a bug. 
![image](https://user-images.githubusercontent.com/7283682/34473723-62265c82-ef33-11e7-920d-f2b516b557b6.png)
Also reproduced in 1.14.23.10 of uBO.

**Comment by gorhill** [comment]
It's definitely not a valid cosmetic filter, but I think it should be accepted as a valid static network filter:

    new URL('http://localhost/##allo');

    hash: "##allo"
    host: "localhost"
    hostname: "localhost"
    href: "http://localhost/##allo"
    origin: "http://localhost"
    password: ""
    pathname: "/"
    port: ""
    protocol: "http:"
    search: ""

**Comment by jspenguin2017** [comment]
`localhost##allo` would be parsed as cosmetic filter though. 
`||localhost/index.php##allo` will also be parsed as cosmetic filter...

**Comment by jspenguin2017** [comment]
Chrome indeed accept `##test` as hash. Although I think that's against the standard. 
![image](https://user-images.githubusercontent.com/7283682/34473926-d0ecda54-ef35-11e7-9c02-df346e3bf162.png)

**Comment by gorhill** [comment]
Sure but my point is whatever is rejected should just be passed to the next stage, not second guess whoever created the filter in the first place. Worst case, the filter is a mistake and it accomplishes nothing, best case, the filter is not an error and it accomplishes what the creator wanted.

You suggest we treat is as invalid cosmetic filter?

**Comment by jspenguin2017** [comment]
Either way is OK, but I think it should be fixed *right*, having things like `||` and `/` clearly indicate the filter is not a cosmetic filter, if you are going with accept `localhost##` as network filter, I guess `||localhost/index.php##allo` should be accepted as network filter as well. 

I don't think we'll ever need `example.com##` to be a network filter, I'd say just discard it from cosmetic filter parser.

**Comment by jspenguin2017** [comment]
This should be related to https://github.com/uBlockOrigin/uBlock-issues/issues/1038 and will be fixed soon. 

---

@uBlock-user 

> Because of lack of installation of dev-builds to catch these bugs. 

This specific issue was known for quite some time, and I added a linter rule specifically for it. The issue was not fixed before because we thought it would only affect network filters that try to match hashes. 

![image](https://user-images.githubusercontent.com/7283682/82152242-26c2de00-981d-11ea-9f5a-94a044c97e2d.png)

---

@gorhill 

The issues that I recently reported are discovered when I was executing my test plan, I think creating a test plan for uBO might be a good addition to the dev builds. Test plans can be created by people without coding knowledge, so a lot more people would be able to contribute to it.

**Comment by gorhill** [comment]
I always wish that uBO would have its own test suite, but frankly I wouldn't know where to start. There were [talks about this in the past](https://github.com/uBlockOrigin/uBlock-issues/issues/36) but the issue died.

**Comment by uBlock-user** [comment]
> Because of lack of installation of dev-builds to catch these bugs.

> This specific issue was known for quite some time

That is a general statement towards all the new bugs propagating after the release of stable, not specifically towards the bug you filed and directed at kulfoon's argument.

**Comment by jspenguin2017** [comment]
@gorhill 

Writing automated tests takes time, sometimes longer than writing the code itself. To have a set of robust tests with good coverage, you are looking at 2 to 3 lines of test for each line of code. Writing tests is usually easier but that is still a lot of work. I recommend manual test plans instead, which can be developed and executed by volunteers with limited to no coding experience. 

For reference, here is my test plan: 
https://github.com/NanoAdblocker/NanoCore2/blob/master/notes/sanity_tests.md
