### ISSUE TITLE
Script snippets injection does not work on localhost

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#78]
Although `localhost` is special, script snippets injection is the only thing that does not work as intended. 

In `nano.cosmeticFilteringEngine.retrieveDomainSelectors`: 
```js
        // https://github.com/chrisaljoudi/uBlock/issues/188
        // Special bucket for those filters without a valid domain name as per PSL
        if ( (bucket = this.proceduralFilters.get(this.noDomainHash)) ) {
            bucket.retrieve(hostname, proceduralSet);
        }
```
There is a special check for `localhost` when retrieving procedural selectors, however, when retrieving script snippets, in `nano.cosmeticFilteringEngine.retrieveUserScripts`: 
```js
    // Explicit (hash is domain).
    var selectors = new Set(),
        bucket;
    if ( (bucket = this.userScripts.get(domain)) ) {
        bucket.retrieve(hostname, selectors);
    }
    if ( entity !== '' && (bucket = this.userScripts.get(entity)) ) {
        bucket.retrieve(entity, selectors);
    }
    for ( var selector of selectors ) {
        this._lookupUserScript(selector, reng, toInject);
    }
```
Hash for `localhost` is `-`, which is not equal to the the domain, `localhost`.

**Comment by jspenguin2017** [comment]
cc @gorhill 
Do you consider this intended behavior? 

This also remind me that running tests on a localhost server is not a wise choice... This will make the test engine so much more complex as I need to relay requests between the Express server and Puppeteer request interceptor. 
How far did you get with your testing tool?

**Comment by gorhill** [comment]
I'm pretty sure this is fixed in uBO's dev build.

**Comment by jspenguin2017** [comment]
Confirmed fixed.
