### ISSUE TITLE
How to keep ublock origin and use nano filters?

### ISSUE THREAD

**Issue by zum4** [NanoAdblocker/NanoCore#81]
How to keep ublock origin and use nano filters?

**Comment by jspenguin2017** [comment]
There isn't an easy way as Nano filters are not always designed to work with uBO. 
See https://github.com/NanoAdblocker/NanoCore/blob/master/Notes/FilterIncompatibility.MD for more details.

**Comment by zum4** [comment]
Thank you but i will keep uBo instead of a bad fork.

**Comment by jspenguin2017** [comment]
If you believe that, you shouldn't use Nano's filters neither.

**Comment by KonoromiHimaries** [comment]
@zum4 
> Thank you but i will keep uBo instead of a bad fork.

you can report any `bad bugs` of this `bad fork`
in this way `bad fork` can be better
