### ISSUE TITLE
Add a key for default update period in case a filter list loses `! Expires` header

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoCore#85]
Nano Mirror servers will insert `! Expires: 1 day` too all filters it mirrors, however, when a failover happens, the update delay may not be refreshed in the case where the original filter doesn't have `! Expires` header. 
Need to add a key to `assets.json` that is the update period to fallback to when a filter list loses its `! Expires` header. 

---

TODO: 
- [x] Implement update delay restore
- [x] Proper server side HTTP Keep-Alive configuration

**Comment by KonoromiHimaries** [comment]
you can add support to minimal `! Expires: 1 minute` time?
i think for specializations filter list this is the best
example. for list `sponsored articles`

**Comment by jspenguin2017** [comment]
No, that's too much. I'll lower the limit to 2 hours for filter lists that support differential update.

**Comment by elypter** [comment]
maybe do it if the server specifically allows it

**Comment by jspenguin2017** [comment]
You should be using WebSocket if you want a 1 minute update period.

**Comment by KonoromiHimaries** [comment]
@jspenguin2017 
> No, that's too much. I'll lower the limit to 4 hours for filter lists that support differential update.

`https://www.wykop.pl/link/4100183/nieetyczna-reklama-nazwa-pl-w-serwisie-wykop-pl/`

**Comment by jspenguin2017** [comment]
If you need to change the rule 1000 times in 7 hours, then chances are you need a better rule. If you have a human committing that, like does he even sleep or eat? If it's handled by an automation script, we can probably make a script snippet for that. 

What I will do is the following: 
- If the filter is a normal filter, the lower cap is 1 day *unless* the server specified a *larger* delay though `X-Nano-Min-Expires` header, the new lower cap is rounded *up* to the nearest day
- If the filter is a differential updated filter, the lower cap is 8 hours, *unless* the server specified *another* lower cap though `X-Nano-Min-Expires` header, where the serve can specify a minimum of 1 hour

If 1 hour is too long, then you really need to find a better rule.

**Comment by elypter** [comment]
too small update intervals are also problematic because they allow to track how long which ip is online and when. maybe even track users that switch ips if the filter is being updated exactly 1 hour after the last time. you should not subscribe to an untrustworthy list maintainer anyway but this is a side effect most users would not expect.

**Comment by KonoromiHimaries** [comment]
> too small update intervals are also problematic because they allow to track how long which ip is online and when. maybe even track users that switch ips if the filter is being updated exactly 1 update interval after the last one. you should not subscribe to an untrustworthy list maintainer anyway but this is a side effect most users would not expect.

I think that every user should be able to choose the minimum refresh time for the filter list

**Comment by elypter** [comment]
i think there should be some randomization if there isnt already. even with long update intervalls you could track people over days if the update is accurate to minutes or even seconds.

**Comment by jspenguin2017** [comment]
Yea, a jitter is a good idea, because it's accurate to milliseconds for now.

**Comment by jspenguin2017** [comment]
I changed `autoUpdatePeriod` to 4 hours, this allows differential update to be more continuous and will prevent abuse of users: The user needs to give consent in addition to the server. 
This doesn't cover the case where the browser is restarted though, but I'd say it's good enough. 
I'm planning on implementing the same failover logic for differential update (failover resets the accelerated update period).

**Comment by jspenguin2017** [comment]
I'm setting up webhooks and other stuff. First test run has now started.

**Comment by jspenguin2017** [comment]
Expire header restore is already implemented, for mirror server, I think RawGit should be better.
