### ISSUE TITLE
Add report button to popup panel

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#86]
With filters, the problem is that, if one of the lists it will break down. people turn off adblock on this site.

Nobody submits broken pages to the authors of the lists.

The problem is getting worse, for example, the last incident with the mbank
`https://www.wykop.pl/link/4094131/brak-mozliwosci-zalogowania-do-mbanku-z-wlaczonym-ublockiem/`

i think you can add a button to report broken site centrally for filters maintainers
example.
![2018-01-08 15_35_43-](https://user-images.githubusercontent.com/5884000/34675449-f3e518a6-f489-11e7-9987-540fe964b661.png)

**Comment by jspenguin2017** [comment]
I definitely have that in mind.

**Comment by elypter** [comment]
if multiple people report a problem then a script can guess which list the problem is in. maybe also add a soft-off button that switches off every filter that is more prone to break something than others.

**Comment by jspenguin2017** [comment]
Can someone help me investigate how the report button works in AdBlock / ABP / Adguard? 
Do they just send you to the forum or it is close to a one-click report?

**Comment by jspenguin2017** [comment]
How does this look? 
![image](https://user-images.githubusercontent.com/7283682/35025447-d0e19044-fb02-11e7-8fa0-abdc5480b8dd.png)

**Comment by kah0922** [comment]
Definitely the bug. It gives a clearer indication of the intended purpose.

**Comment by elypter** [comment]
according to abp their report contains this
`<report type="false negative">
<window url="https://www.mtbs3d.com/phpBB/viewforum.php?f=*"/>
<subscriptions>
<subscription id="https://easylist-downloads.adblockplus.org/exceptionrules.txt" version="201801170901" lastDownloadAttempt="-19" lastDownloadSuccess="-19" softExpiration="73967" hardExpiration="172781" downloadStatus="synchronize_ok" disabledFilters="0"/>
<subscription id="https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt" version="201801170900" lastDownloadAttempt="-18" lastDownloadSuccess="-18" softExpiration="95450" hardExpiration="172782" downloadStatus="synchronize_ok" disabledFilters="0"/></subscriptions>
<adblock-plus version="3.0.2" locale="de"/>
<application name="Firefox" version="57.0.1" vendor="" userAgent="Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:57.0) Gecko/20100101 Firefox/57.0"/>
<platform name="Gecko" version="57.0"/>
<comment>comment sample</comment>
<email>test@example.com</email></report>`

so it sends what lists the user has activated. the user only gets asked if its a false positive or a false negative and if he wants to add a comment and an email. this is what the show report button says. i didnt inspect if abp is honest

**Comment by elypter** [comment]
adguard offers more options like connection with github account, manual selection of filters and version, an option to mark the link as nsfw,  a little troubleshooting in the beginning(have you updated your filters and disabled custom filters?) and requires a screenshot. it didnt have an option to show the source of the report.

**Comment by elypter** [comment]
both send you through several steps to add information. none of them requires captchas. they might only do when you send too many reports.

**Comment by elypter** [comment]
i think nano adblocker requires a different approach. all these adblockers use a narrow band of filterlists so it is easy for them to decide which list needs fixing. if you use 20 filters in nano and many people do then it will be hard to distinguish which list causes a problem(in the case of a false positive or a broken site). i suggest that nano blocker should give the option to debug the problem by intelligently switching of lists until the problem disappears. it should do this with not tool many steps(not one step for each activated list) to narrow down the problem without too much work. this would not be a 100% hit but rather a hint that it is one of a bunch of filters. but if multiple users report the issue and nano blocker choses different filters to deactivate for each user then you could detect the pattern on the server side

**Comment by jspenguin2017** [comment]
I'll probably use a rate limiter, it's usually more effective than CAPTCHA. 

I don't think I have enough users to run a sophisticated algorithm on server side. So I'll start with a plain simple bug reporter. I can add more logic to deal with known / repeated cases later. 

Collecting test data is definitely going to help to narrow the problem down to one filter, although that does require quite a bit of work to implement properly, and 99% of the time just the test link will suffice. The vast majority of users won't add more than 4 or 5 filters than default.

**Comment by elypter** [comment]
when you chose an issue tracker i suggest to use one that allows to have multiple projects and the possibility to move bugs between them. the idea is that filterlist maintainers could register to the tracker and work together to fix conflicts and to move filters to the list they fit in the best. this also allows to open a bug report even when it is not clear yet which list it should belong to and move it once that has been figured out.

**Comment by jspenguin2017** [comment]
Do you have a recommendation?

**Comment by elypter** [comment]
not, really. i dont know much more from the systems than you do from reporting a few bugs. there is an overview on wikipedia https://en.wikipedia.org/wiki/Comparison_of_issue-tracking_systems but it doesnt inform you about most of the features. if you cannot find one that has all of the features they might exist as plugins. if they dont, i think it is still easier to write a plugin yourself than to start a whole new system from scratch. for the domain grouping you can maybe use some auto merging functionality if it exists. so the first user to report a domain creates an issue and all following get merged as comments. btw, cant you just send the User Agent as part of the report? the user doesn't have any interest in faking it and if he had he could do anyway. if it is for the rate limiting i think this is better done by the webserver.

**Comment by jspenguin2017** [comment]
I need a really fast and efficient system to minimize server costs, and it need to run on Debian, Windows is not acceptable. Which means the only acceptable languages are: JavaScript, Java, and Go. C and C++ are also OK although I don't think anyone use them. Since I probably have to modify it, it needs to be open source and probably in JavaScript. 
Any database system is acceptable although MongoDB is preferred. 

Looking thought the list, none seems to fit my needs. 
I don't think I want to have a full issues tracker, as there isn't a reasonable way for me to handle screenshots. 

> for the rate limiting i think this is better done by the webserver

Well, the bug tracking system is done by the webserver as well.

**Comment by elypter** [comment]
Python, Ruby, Perl, and PHP run very well on debian. i find it rather odd using them on windows or use windows for hosting at all. even .NET is possible on linux to some degree with MONO or .NET Core. the other languages are a bit odd except from js in the form of Node.js but i do not see any reason why to limit on any language except from personal preference.

i dont think a decently written issue tracker easily causes performance problems. its a rather low volume application. the choice and configuration of the webserver is more important if at all.

i dont think people having conversations is a huge deal. web forums do exist and they are only about conversation. if its really a big concern then host in a more freedom of speech friendly country.

>Well, the bug tracking system is done by the web server as well. I'm not sure what you mean.

there are methods to limit access through the webserver config that block ddos or misuse before it even hits serverside scripting.

**Comment by jspenguin2017** [comment]
Node is 50 times faster than Python, I can't afford running Python server. 
.NET Core *can* run .NET apps, but not fast. The real .NET runtime is blazing fast on Windows, but my server has 1GB of RAM, so Windows can't even start... 

I don't want a tracker that's *only* good for low volume. It really doesn't matter how well your software is written, if it's in Ruby it WILL be slow beyond reason. 

It's not about freedom of speech, it's about when someone post illegal stuff, the responsibility for distributing the illegal material that is on the host. 

> there are methods to limit access through the webserver config that block ddos or misuse before it even hits serverside scripting.

Example?

**Comment by elypter** [comment]
really? they are both interpreted languages and you can increase speed a lot with things like cython.
btw how fast does it have to be? more than 10 requests/second?

in most countries the responsibility is not on the host. you are just obliged to delete when being asked to but you can get around this by just not allowing uploads. just let people use an image hoster for screenshots.

>Example?

in apache you can do it with mod-security or mod-ratelimit for example and there is also the option of reverse proxies which however cost money but also protect you from ddosing.

**Comment by elypter** [comment]
maybe you could work together with collinbarrett from https://github.com/collinbarrett/FilterLists in this who if i remember correctly also has ideas to streamline filterlist reporting.

**Comment by jspenguin2017** [comment]
JavaScript can be interpreted, just like C++ can be interpreted. JavaScript can be compiled to machine code, Python as well, however, the JIT compiler of Python, PyPy, comes close to V8, the JIT compiler of JavaScript, but still fall short by a good chunk. 

Apache isn't an option, it's too easy to take down the server with Slowloris, even with `mod-security` enabled. Also uBO's 2 seconds delay between filter downloads will just take down an Apache server right away. 
I rather have application code to handle rate limiting, I don't want to be installing 50 different extensions. 

We have a *really* tight budget, so anything that cost extra money isn't an option. I need something that is blazing fast even on really tight memory (512MB including OS). 10 requests per second is definitely unacceptable.

**Comment by jspenguin2017** [comment]
> if i remember correctly also has ideas to streamline filterlist reporting

Ping him over?

**Comment by KonoromiHimaries** [comment]
@jspenguin2017 C1
`https://www.scaleway.com/baremetal-cloud-servers/`

**Comment by jspenguin2017** [comment]
4 ARM Cores... Eh... 
Its unfortunate but my server is designed to *not* scale with CPU core count... Yea that's a bad decision.

**Comment by jspenguin2017** [comment]
I think most people won't bother running though 8 whole steps. That's not better than asking them to come to GitHub. 
I'll have a one-click report with optional additional info, and it's the server's job to guess which report is good and copy it to GitHub.

**Comment by KonoromiHimaries** [comment]
>  although the computing power is kind of bad, 4 ARMv7 cores sounds like a lot but in reality it's nothing.

@jspenguin2017 maybe `2 x86 64bit Cores`
`https://www.scaleway.com/virtual-cloud-servers/`

**Comment by jspenguin2017** [comment]
2 cores, but not 2 functional cores, according to reviews.

**Comment by elypter** [comment]
if i understood this correctly then you are going to use this server for downloading the filterlists too? if that is the case then this is going to be the absolute bottleneck so that other suff doesnt matter in comparison anyway. and you have to handle the limiting with server settings too because itl destroy performance completely if you run a server side script to check permissions for each request. btw at least for the apache mods you can set different limits for different paths.

**Comment by jspenguin2017** [comment]
> this is going to be the absolute bottleneck so that other suff doesnt matter in comparison

How do you know? Have you ever seen my proprietary server code? 

> you have to handle the limiting with server settings too because itl destroy performance completely if you run a server side script to check permissions for each request

How do you know my application script is slower than Apache mods? That would be a valid argument for PHP, not for Node.js.

**Comment by elypter** [comment]
a very overengineered car can be faster than a very poorly engineered jet plane but usually and if built in a meaningful way the jet plane is faster.

**Comment by jspenguin2017** [comment]
You are saying my code is poorly engineered? Don't underestimate me.

**Comment by elypter** [comment]
no, if anything the analogy implies that the mod is written badly. catching a request early on always tends to be more resource preserving than initializing high level interfaces that then deal with it. thats also why even the linux kernel recently included a very early stage filter akin to a firewall that is able to discard packages before it even reaches the network stack. maybe some mods even take use of that. i dont know about ngix but in apache it used to be quite resource intensive to start a php instance. if this is done just to check if it should run then thats a big waste of resources.

**Comment by jspenguin2017** [comment]
You are making assumptions about the software my server used. What is telling you I'm using nginx? The `Server` header? What is telling you that my server is standard compliant? 
I'm using a custom server software, the server and application logic are fused together, none of your arguments apply in this case.

**Comment by elypter** [comment]
i just assumed it because you dont want to use apache and nginx is the second most popular and is also known to be fast. if you are building your own webserver as well then dont have to care about mods anyway. its great and and all that and you are probably learning a lot. im just surprised. im expecting google or facebook to do something like this but not a bugtracker.

**Comment by sebast889** [comment]
I don't know what kind of UI you have in mind but I think adding links to forums.lanik.us and NanoFilters repo will good (and NanoCore if you want people to know where to report bugs about the extension).

**Comment by elypter** [comment]
creating an account for a single report is too much for most people and i can understand it. i have a dozen accounts on bugtrackers that i just made for a single thing.

**Comment by jspenguin2017** [comment]
Hum, I still think thumb down button is better... 
![image](https://user-images.githubusercontent.com/7283682/35312726-2f45c458-007a-11e8-85e1-8ffd3fab7b0e.png)

**Comment by jspenguin2017** [comment]
OK, now, which machine learning library is best for the bug reporting end point?

**Comment by KonoromiHimaries** [comment]
> Hum, I still think thumb down button is better...

for spam report - yes
for bug report - no

**Comment by KonoromiHimaries** [comment]
> Which machine learning library is best for the bug reporting end point? 

I think that there is no the best
choose the one you know best

`https://github.com/josephmisiti/awesome-machine-learning`

**Comment by jspenguin2017** [comment]
If I have not mistaken, Adguard's report button is thumb down. It kind of make sense... 
It's not quite "bug report" button, more like a "not working" button.

**Comment by jspenguin2017** [comment]
Different machine learning algorithms definitely will make a huge difference. I'm thinking of starting with a naive logic and train an AI on the side and see how far that goes... 
I probably should run more than 1 algorithm as I'm not exactly sure which algorithm would make sense for filter reports.

**Comment by jspenguin2017** [comment]
OK, how about this: 
- When on NanoFilters or uAssets issues creation page, the bug icon is shown and clicking it will auto-fill the issue (environment, selected filters, etc)
- When on another website, the flag icon is shown and clicking it will open the quick problem reporter

**Comment by elypter** [comment]
but people should be able to submit more complex information if they want to in the quick reporter too. sometimes problems are only visible under certain conditions.

**Comment by jspenguin2017** [comment]
Quick reports are handled by a bot (either hard coded logic or machine learning), I will accept more info, although how the bot will handle that is another question. If you want to fill a detailed report, just come to GitHub.

**Comment by jspenguin2017** [comment]
I feel like the current server design isn't the best, the database handling isn't ideal... I think I should spend the time fixing the misdesign instead of keep building on something that's not scalable. I need to implement proper async and make the database not based on JSON. 

I also have some technical difficulties with my other tools. I built them with Electron thinking it is cross platform but apparently they won't work on Ubuntu. There are like 5 bug reports open in their repo since December and no one seems to care. It's too slow anyway so I guess I should start learning Qt.

**Comment by elypter** [comment]
i dont know what you use a gui for but i suggest to consider wxwidgets. it is a metatoolkit that renders the application in the native toolkit that the platform offers (gtk on linux but experimental qt support also exists)

**Comment by jspenguin2017** [comment]
I think I know how to design the bug report server now. I'll go with Adguard approach and use GitHub issues tracker as the tracking engine.

**Comment by jspenguin2017** [comment]
It's almost done! There's 2 or 3 more features that I want my bot to have and we'll be ready.

**Comment by jspenguin2017** [comment]
OK, GeoIP system is up now. We should be ready to roll out the report button soon. 

Ideally I want to have a front end server to bounce bad reports, and have a back end server to handle the rest. This way, I can code more aggressively on the front end server; if I accidentally coded a vulnerability, the damage would be limited.

**Comment by elypter** [comment]
an outdated extension should not make the button invisible though. rather trigger an update or ask for it.

**Comment by jspenguin2017** [comment]
There is no easy way for the extension to know whether it is outdated. If it is outdated, the server will simply reject the report.

**Comment by jspenguin2017** [comment]
It's almost ready! https://github.com/NanoMeow/IntegrationServer
I still need: 
- Admin dashboard
- Aggressively reject invalid url (?)
- Outdated extension bouncer (?)

I think I should have the server simply flag invalid urls but not reject them, when I'm sure it's working properly I can switch on the aggressive rejection mode.

**Comment by jspenguin2017** [comment]
Let's just ship the beta in both extensions, what can possibly go wrong? 

I'll worry about the new report server later.
