### ISSUE TITLE
Disable specific filter on single site

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#87]
i think this is the best enhancement

https://github.com/NanoAdblocker/NanoCore/issues/86#issuecomment-356010089

example.
<details>

![2018-01-09 23_52_25-](https://user-images.githubusercontent.com/5884000/34747569-1644c2b0-f599-11e7-8902-fa49d1a1e0d7.png)

</details>

**Comment by jspenguin2017** [comment]
Filter lists can limit the amount of domains each rule apply to with many ways. If you need to set a different set of filter lists for each domain, then chances are the filter lists you are using are kind of broken. 
And there isn't a reasonable way to swap filter lists sets internally.

**Comment by elypter** [comment]
it depends on how the internal data structure of the core looks like if the rules still have a reference to the list they came from then it shouldnt be too hard to just ignore them on a specific website just like you can switch off blocking completely for a site. if the internal structure is just a huge merged and optimized set of rules, which i assume is the case, then you would have to rebuild that internal structure once you click on that button or when you later load that site again or if you leave and all filterlists should be on again. if the performance hit is too great then there are two ways to deal with it. generate an internal structure for each new combination of active lists and keep it for later or use the normal datastructure when all lists are on and if one or more are disabled then execute each least sequentially. this could behave differently than a combined list, like you mentioned, so maybe some sort of hybrid would be needed. so, yeah, not an easy task if my assumptions about the project are correct. but it would still be a very worthwhile feature that you shouldn't give up that easily. maybe gorhills rework of the engine makes this easier to implement.

**Comment by jspenguin2017** [comment]
Whitelist just completely disables filtering, that's different than disable one specific filter list for that domain. 

Currently, if I understood the code right, each filter list will be compiled separately and stored, all selected filters are merged together. The merging process need to be done every time a filter list is turned on or off. 

There are also snapshots of internal states for fast startup. 

> it would still be a very worthwhile feature

I can't think of a single use case. 

> maybe gorhills rework of the engine makes this easier to implement

Did you spelled "harder" wrong?

**Comment by elypter** [comment]
i dont think he wanted whitelisting.

>I can't think of a single use case

if you have experimental or generic filterlists that work well most of the time but occasionally break sites then you want to quickly disable the list for this specific website but not in general and you do not want to go through the dashboard every single time you visit that site again. you should also contact the maintainer but it will take time until it is fixed. you could even just move along and after a few weeks you look up your dynamic rules and post a bug report with all the problems you collected over time but were too lazy to report at that moment.

>Did you spelled "harder" wrong?

well, unlikely but at least possible

**Comment by jspenguin2017** [comment]
Just override the rule with your custom filters, that's what it's for.

**Comment by elypter** [comment]
while still a lot more work than 2 clicks i could do this. most people wont. blocking something with the element hider is something many would be capable but figuring out an exception rule is too much for casual users who just set it up, tweak a few options and select and install a few lists and then call it a day. not everyone is going to read the wiki about the filter syntax and then debug every page that causes problems. giving them a better option than having to switch off Nano Blocker entirely or uninstalling a list just because of one or two false positives would really add some usability benefit.

**Comment by jspenguin2017** [comment]
If you are a casual user, chances are you won't be adding filter lists other than those that come with Nano Adblocker. 
If you are a casual user, chances are you won't be able to know which filter list you have is causing the problem. 
If you can find out which filter list is causing the problem you will be able to set up the exception filter. 

If you absolutely need to toggle between two sets of filters, use browser profile. 

This is non-trivial and only has theoretical use case, I'll decline this feature for now.

**Comment by jspenguin2017** [comment]
What I will do is to add a button in Logger that turns off a rule.

**Comment by KonoromiHimaries** [comment]
mayby quick access to off specific rule on single site

example.
![34747569-1644c2b0-f599-11e7-8902-fa49d1a1e0d7](https://user-images.githubusercontent.com/5884000/34751571-caebaaa8-f5ad-11e7-897a-5062498aa2c2.png)

**Comment by jspenguin2017** [comment]
If you find yourself have to toggle a filter list frequently, then you probably need to figure out what exactly is wrong.

**Comment by elypter** [comment]
you do not only want this when something is wrong. maybe you have a list that implements a night mode and you personally do not want it on a specific site or a floating header that you want for some special use case or you want to allow ads for a site but not tracking and annoyances....

besides that it is great for trouble shooting. you turn off lists as long as the site works again. then you immediately know who to send a bug report to.

**Comment by jspenguin2017** [comment]
If you need a night mode or any other mode, use browser profile. 
For trouble shooting, use the Logger.

**Comment by elypter** [comment]
make a browser profile for every website? thats not practical. you do not need that many tries if you always the disable half of the remaining ones. ~log2(n) turns.

**Comment by KonoromiHimaries** [comment]
an ordinary user will not be able to and will not want to look into the logger.

**Comment by KonoromiHimaries** [comment]
> it gets a bit crowded but you can use collapsible groups

like this?
![34747569-1644c2b0-f599-11e7-8902-fa49d1a1e0d7](https://user-images.githubusercontent.com/5884000/34771376-ae9b3240-f604-11e7-8a81-6ea70d3cac12.png)

**Comment by jspenguin2017** [comment]
You do realize there are over 100 000 rules enabled by default right?

**Comment by jspenguin2017** [comment]
There are well over 10 000 rules affecting every single site. A lot of generic rules in EasyList.

**Comment by KonoromiHimaries** [comment]
hmm.. you can segregate this rules to category and hide
