### ISSUE TITLE
【Question】 Does Nano Adblocker support uBlock Origin Extra?

### ISSUE THREAD

**Issue by 775405984** [NanoAdblocker/NanoCore#88]
uBlock Origin Extra A companion extension to uBlock Origin: to gain ability to foil early hostile anti-user mechanisms working around content blockers.

So, my question is, does Nano Adblocker support uBlock Origin Extra? Does it have any compatibility issue? Do we really need  uBlock Origin Extra after installed Nano Adblocker and Nano Defender and its additional scripts?

**Comment by jspenguin2017** [comment]
Nano Adblocker has Nano Defender and does not rely on an additional copy of uBO-Extra.
