### ISSUE TITLE
blacklist-only blocking mode button

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoCore#91]
can I block ads in the nano adblocker except the BLACK LIST ? because I do not want to harm websites that I will go to once or twice, but I also want to block those that annoy me

**Comment by jspenguin2017** [comment]
You can just whitelist those sites, I won't add a blacklist only mode because how do you know the next website you are visiting is not harmful unless you have checked it?

**Comment by KonoromiHimaries** [comment]
you can block malicious pages despite the black list mode

**Comment by KonoromiHimaries** [comment]
most users don't have any alternative for that and not use any adblock.

**Comment by jspenguin2017** [comment]
How do I know which one is malicious? Unless I apply all the filter rules, I cannot know that. 
With no filters, Nano blocks nothing, if you decide a page should be treated like being whitelisted unless it is explicitly blacklisted, then I cannot apply filter rules, thus, cannot block malware domains.

**Comment by KonoromiHimaries** [comment]
maybe, you can apply all the filter rules, and whitelisted the non-aggressive ads?

**Comment by jspenguin2017** [comment]
How do I know what is non-aggressive ads? You need another filter list for that. (EasyList Exception filter?)
