### ISSUE TITLE
leechall.download

### ISSUE THREAD

**Issue by adreporter** [NanoAdblocker/NanoCore#92]
Hi, I'm using Nano Adblocker and Nano Defender.
Just out of curiosity, do you sometimes have problems solving Google reCAPTCHAs?
After solving it and clicking on "I'm not a robot", the check mark becomes green, but the problem is that I have to solve it again because it says the captcha was incorrect, even if the check mark was green.
Am I the only one?

**Comment by jspenguin2017** [comment]
Well, I need a test link.

**Comment by adreporter** [comment]
For example: http://leechall.download/go/aHR0cDovL2xpbmtzaHJpbmsubmV0LzlsZjE0
If you won't have any problems with these 5 sites with captcha, well then it's something wrong with my Google Chrome.

**Comment by jspenguin2017** [comment]
Well, works for me...
