### ISSUE TITLE
Describe if the Nano Adblock fork is synced with the latest version of uBO

### ISSUE THREAD

**Issue by davidhedlund** [NanoAdblocker/NanoCore#96]
If I'm correct, then it's worth adding this to https://jspenguin2017.github.io/uBlockProtector/, https://github.com/NanoAdblocker/NanoCore, and/or https://addons.mozilla.org/en-US/firefox/addon/real-nano-adblocker/
> Nano Adblocker is not a straight fork of uBlock Origin; instead, it is a parallel effort that works closely with and re-bases in synchronization on the latest uBlock Origin as the upstream supplier, with patches merged upstream whenever possible.

**Comment by jspenguin2017** [comment]
I can't add it to the extension description, it doesn't fit in the box. 
I'll consider it for the README file.

**Comment by jspenguin2017** [comment]
I'm not sure what is a `straight fork`, can you elaborate? 
I pull upstream features and updates as I see fit, there is no guarantee that all latest features will land in Nano. 
Honestly I'm not sure if I'll PR to upstream, due to gorhill's attitude towards new features.

**Comment by davidhedlund** [comment]
Please see https://directory.fsf.org/wiki/IceCat from which I modified the text that I suggested.

**Comment by jspenguin2017** [comment]
Well, you can't just copy some random text off somewhere and expect it to fit Nano. 
Won't fix.

**Comment by davidhedlund** [comment]
I would like Nano Adblocker to be based on the latest version of uBO all the time + modifications.

**Comment by jspenguin2017** [comment]
I have my decisions and gorhill has his, if you disagree with both, well, you can always fork yourself. 
The version of uBO that Nano is based on is in the about tab of the dashboard, it is usually close to tip-of-tree of uBO, although I will remove features as I see fit.

**Comment by davidhedlund** [comment]
Thanks, good to know.
